services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pass}
      POSTGRES_DB: ${DB_DATABASE:-vite_et_gourmand}
    ports:
      - '${DB_HOST_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_DATABASE:-vite_et_gourmand}']
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: michalhosna/adminer
    restart: unless-stopped
    ports:
      - '8089:8080'
    environment:
      ADMINER_DRIVER: pgsql
      ADMINER_SERVER: postgres
      ADMINER_DB: ${DB_DATABASE:-vite_et_gourmand}
      ADMINER_USERNAME: ${DB_USERNAME:-postgres}
      ADMINER_PASSWORD: ${DB_PASSWORD:-pass}
      ADMINER_AUTOLOGIN: 1
      ADMINER_NAME: Vite et Gourmand
    depends_on:
      - postgres

  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-pass}
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD:-pass}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME:-root}:${MONGO_ROOT_PASSWORD:-pass}@mongo:27017/?authSource=admin
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

volumes:
  postgres_data:
  mongo_data:
