/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

/**
 * @summary Auth - Login
 */

export const zodPublicAuthLoginBody = zod.object({
  email: zod.string().email(),
  password: zod.string().min(1),
});

export const zodPublicAuthLoginResponse = zod.object({
  accessToken: zod.string(),
});

/**
 * @summary Auth - Register
 */
export const zodPublicAuthRegisterBodyPasswordRegExp = new RegExp(
  "^(?=.\*[a-z])(?=.\*[A-Z])(?=.\*[\\d\\W_])[a-zA-Z\\d\\W_]{8,}$",
);

export const zodPublicAuthRegisterBody = zod.object({
  email: zod.string().email(),
  password: zod.string().regex(zodPublicAuthRegisterBodyPasswordRegExp),
  firstName: zod.string().min(1),
  lastName: zod.string().min(1),
  phone: zod.string().nullish(),
  address: zod.string().nullish(),
  city: zod.string().nullish(),
  postalCode: zod.string().nullish(),
});

/**
 * @summary Auth - Refresh token
 */
export const zodPublicAuthRefreshBody = zod.object({
  accessToken: zod.string().optional(),
});

export const zodPublicAuthRefreshResponse = zod.object({
  accessToken: zod.string(),
});

/**
 * @summary Auth - Logout
 */
export const zodPublicAuthLogoutResponse = zod.object({
  message: zod.string(),
  code: zod.string(),
});

/**
 * @summary Auth - Request password reset
 */
export const zodPublicAuthResetPasswordRequestBody = zod.object({
  email: zod.string().email(),
});

export const zodPublicAuthResetPasswordRequestResponse = zod.object({
  message: zod.string(),
  code: zod.string(),
});

/**
 * @summary Auth - Reset password
 */

export const zodPublicAuthResetPasswordBodyPasswordRegExp = new RegExp(
  "^(?=.\*[a-z])(?=.\*[A-Z])(?=.\*[\\d\\W_])[a-zA-Z\\d\\W_]{8,}$",
);

export const zodPublicAuthResetPasswordBody = zod.object({
  token: zod.string().min(1),
  password: zod.string().regex(zodPublicAuthResetPasswordBodyPasswordRegExp),
});

export const zodPublicAuthResetPasswordResponse = zod.object({
  code: zod.string(),
  message: zod.string(),
});

/**
 * @summary Auth - Validate account
 */

export const zodPublicAuthValidateAccountBody = zod.object({
  token: zod.string().min(1),
});

export const zodPublicAuthValidateAccountResponse = zod.object({
  message: zod.string(),
  code: zod.string(),
});

/**
 * @summary Auth - Resend validation email
 */
export const zodPublicAuthResendValidationBody = zod.object({
  email: zod.string().email().optional(),
  token: zod.string().optional(),
});

export const zodPublicAuthResendValidationResponse = zod.object({
  message: zod.string(),
  code: zod.string(),
});

/**
 * @summary Auth - Set employee password
 */

export const zodPublicAuthSetEmployeePasswordBodyNewPasswordRegExp = new RegExp(
  "^(?=.\*[a-z])(?=.\*[A-Z])(?=.\*[\\d\\W_])[a-zA-Z\\d\\W_]{8,}$",
);

export const zodPublicAuthSetEmployeePasswordBody = zod.object({
  token: zod.string().min(1),
  newPassword: zod
    .string()
    .regex(zodPublicAuthSetEmployeePasswordBodyNewPasswordRegExp),
});

export const zodPublicAuthSetEmployeePasswordResponse = zod.object({
  code: zod.string(),
  message: zod.string(),
});

/**
 * @summary Menu - List available menus (public, filterable)
 */
export const zodPublicMenuGetAllQueryLimitMax = 100;

export const zodPublicMenuGetAllQueryOffsetMin = 0;

export const zodPublicMenuGetAllQueryParams = zod.object({
  theme: zod.string().optional(),
  dietaryRegimeId: zod.string().uuid().optional(),
  priceMax: zod.number().nullish(),
  priceMin: zod.number().nullish(),
  maxMinPersons: zod.number().nullish(),
  limit: zod.number().min(1).max(zodPublicMenuGetAllQueryLimitMax).optional(),
  offset: zod.number().min(zodPublicMenuGetAllQueryOffsetMin).nullish(),
  sortBy: zod
    .enum(["name", "price", "minPersons", "createdAt", "updatedAt"])
    .optional(),
  sortOrder: zod.enum(["ASC", "DESC"]).optional(),
});

export const zodPublicMenuGetAllResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      name: zod.string(),
      description: zod.string().nullable(),
      theme: zod.string().nullable(),
      price: zod.number(),
      minPersons: zod.number(),
      maxPersons: zod.number().nullable(),
      stock: zod.number().nullable(),
      isAvailable: zod.boolean(),
      imageUrl: zod.string().nullable(),
    }),
  ),
  totalCount: zod.number(),
});

/**
 * @summary Menu - Get a menu detail (public)
 */
export const zodPublicMenuGetOneParams = zod.object({
  id: zod.string().uuid(),
});

export const zodPublicMenuGetOneResponse = zod.object({
  id: zod.string().uuid(),
  name: zod.string(),
  description: zod.string().nullable(),
  theme: zod.string().nullable(),
  price: zod.number(),
  minPersons: zod.number(),
  maxPersons: zod.number().nullable(),
  stock: zod.number().nullable(),
  conditions: zod.string().nullable(),
  imageUrl: zod.string().nullable(),
  isAvailable: zod.boolean(),
  createdAt: zod.string().datetime({}),
  updatedAt: zod.string().datetime({}),
  dishes: zod.array(
    zod.object({
      id: zod.string().uuid(),
      name: zod.string(),
      category: zod.enum(["entree", "plat", "dessert"]),
      description: zod.string().nullable(),
      price: zod.number().nullable(),
      allergens: zod.array(
        zod.object({
          id: zod.string().uuid(),
          name: zod.string(),
          icon: zod.string().nullable(),
        }),
      ),
    }),
  ),
  dietaryRegimes: zod.array(
    zod.object({
      id: zod.string().uuid(),
      name: zod.string(),
    }),
  ),
});

/**
 * @summary Allergen - List allergens (public, used for filters)
 */
export const zodPublicAllergenGetAllResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      name: zod.string(),
      icon: zod.string().nullable(),
      createdAt: zod.string().datetime({}),
    }),
  ),
  totalCount: zod.number(),
});

/**
 * @summary Dietary Regime - List dietary regimes (public, used for filters)
 */
export const zodPublicDietaryRegimeGetAllResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      name: zod.string(),
      description: zod.string().nullable(),
      createdAt: zod.string().datetime({}),
    }),
  ),
  totalCount: zod.number(),
});

/**
 * @summary Delivery zone - List active zones (public)
 */
export const zodPublicDeliveryZoneGetAllResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      name: zod.string(),
      postalCode: zod.string().nullable(),
      city: zod.string().nullable(),
      distanceKm: zod.number(),
      isActive: zod.boolean(),
      createdAt: zod.string().datetime({}),
    }),
  ),
  totalCount: zod.number(),
});

/**
 * @summary Delivery zone - Calculate delivery fee for a zone or postal code (public)
 */
export const zodPublicDeliveryZoneCalculatePriceBodyPostalCodeMax = 20;

export const zodPublicDeliveryZoneCalculatePriceBody = zod.object({
  deliveryZoneId: zod.string().uuid().optional(),
  postalCode: zod
    .string()
    .min(1)
    .max(zodPublicDeliveryZoneCalculatePriceBodyPostalCodeMax)
    .optional(),
});

export const zodPublicDeliveryZoneCalculatePriceResponse = zod.object({
  zoneId: zod.string().uuid(),
  zoneName: zod.string(),
  city: zod.string().nullable(),
  distanceKm: zod.number(),
  deliveryFee: zod.number(),
});

/**
 * @summary Order - Create a guest order (public)
 */

export const zodPublicOrderCreateGuestBodyGuestNameMax = 255;

export const zodPublicOrderCreateGuestBodyGuestPhoneMax = 50;

export const zodPublicOrderCreateGuestBodyDeliveryPostalCodeMax = 20;

export const zodPublicOrderCreateGuestBodyDeliveryAddressMax = 255;

export const zodPublicOrderCreateGuestBodyDeliveryCityMax = 255;

export const zodPublicOrderCreateGuestBodyNotesMax = 2000;

export const zodPublicOrderCreateGuestBody = zod.object({
  items: zod
    .array(
      zod.object({
        menuId: zod.string().uuid(),
        quantity: zod.number().min(1),
      }),
    )
    .min(1),
  guestEmail: zod.string().email(),
  guestName: zod.string().min(1).max(zodPublicOrderCreateGuestBodyGuestNameMax),
  guestPhone: zod
    .string()
    .max(zodPublicOrderCreateGuestBodyGuestPhoneMax)
    .optional(),
  deliveryZoneId: zod.string().uuid().optional(),
  deliveryPostalCode: zod
    .string()
    .min(1)
    .max(zodPublicOrderCreateGuestBodyDeliveryPostalCodeMax)
    .optional(),
  deliveryAddress: zod
    .string()
    .max(zodPublicOrderCreateGuestBodyDeliveryAddressMax)
    .optional(),
  deliveryCity: zod
    .string()
    .max(zodPublicOrderCreateGuestBodyDeliveryCityMax)
    .optional(),
  deliveryDate: zod.string().date().optional(),
  notes: zod.string().max(zodPublicOrderCreateGuestBodyNotesMax).optional(),
});

/**
 * @summary Review - List approved reviews (public)
 */
export const zodPublicReviewGetApprovedQueryLimitMax = 50;

export const zodPublicReviewGetApprovedQueryParams = zod.object({
  limit: zod
    .number()
    .min(1)
    .max(zodPublicReviewGetApprovedQueryLimitMax)
    .optional(),
});

export const zodPublicReviewGetApprovedResponseItemsItemRatingMax = 5;

export const zodPublicReviewGetApprovedResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      firstName: zod.string().nullable(),
      rating: zod
        .number()
        .min(1)
        .max(zodPublicReviewGetApprovedResponseItemsItemRatingMax),
      comment: zod.string().nullable(),
      createdAt: zod.string().datetime({}),
    }),
  ),
});

/**
 * @summary Contact - Send a message (public)
 */
export const zodPublicContactSendBodyNameMax = 255;

export const zodPublicContactSendBodyEmailMax = 255;

export const zodPublicContactSendBodyPhoneMax = 50;

export const zodPublicContactSendBodySubjectMax = 255;

export const zodPublicContactSendBodyMessageMax = 5000;

export const zodPublicContactSendBody = zod.object({
  name: zod.string().min(1).max(zodPublicContactSendBodyNameMax),
  email: zod.string().email().max(zodPublicContactSendBodyEmailMax),
  phone: zod.string().max(zodPublicContactSendBodyPhoneMax).optional(),
  subject: zod.string().max(zodPublicContactSendBodySubjectMax).optional(),
  message: zod.string().min(1).max(zodPublicContactSendBodyMessageMax),
});

/**
 * @summary CMS - Get page content (public)
 */
export const zodPublicPageContentGetQueryPageMax = 100;

export const zodPublicPageContentGetQuerySectionMax = 100;

export const zodPublicPageContentGetQueryParams = zod.object({
  page: zod.string().min(1).max(zodPublicPageContentGetQueryPageMax),
  section: zod
    .string()
    .min(1)
    .max(zodPublicPageContentGetQuerySectionMax)
    .optional(),
});

export const zodPublicPageContentGetResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      page: zod.string(),
      section: zod.string(),
      content: zod.record(zod.string(), zod.unknown()),
      updatedAt: zod.string().datetime({}),
      updatedBy: zod.string().uuid().nullable(),
    }),
  ),
});

/**
 * @summary CMS - List operating hours (public)
 */
export const zodPublicOperatingHoursGetAllResponseItemsItemDayOfWeekMin = 0;
export const zodPublicOperatingHoursGetAllResponseItemsItemDayOfWeekMax = 6;

export const zodPublicOperatingHoursGetAllResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      dayOfWeek: zod
        .number()
        .min(zodPublicOperatingHoursGetAllResponseItemsItemDayOfWeekMin)
        .max(zodPublicOperatingHoursGetAllResponseItemsItemDayOfWeekMax),
      openTime: zod.string().nullable(),
      closeTime: zod.string().nullable(),
      isClosed: zod.boolean(),
    }),
  ),
});

/**
 * @summary Healthcheck - Check API health
 */
export const zodPublicHealthcheckResponse = zod.object({
  message: zod.string(),
  timestamp: zod.string(),
  uptime: zod.number(),
});
