/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AxiosRequestConfig, AxiosResponse, AxiosInstance } from "axios";

import type {
  HealthcheckResponse,
  PublicAllergenGetAll200,
  PublicAuthLogin200,
  PublicAuthLoginBody,
  PublicAuthLogout200,
  PublicAuthRefresh200,
  PublicAuthRefreshBody,
  PublicAuthRegister201,
  PublicAuthRegisterBody,
  PublicAuthResendValidation200,
  PublicAuthResendValidationBody,
  PublicAuthResetPasswordBody,
  PublicAuthResetPasswordRequest200,
  PublicAuthResetPasswordRequestBody,
  PublicAuthSetEmployeePasswordBody,
  PublicAuthValidateAccount200,
  PublicAuthValidateAccountBody,
  PublicContactSend201,
  PublicContactSendBody,
  PublicDeliveryZoneCalculatePrice200,
  PublicDeliveryZoneCalculatePriceBody,
  PublicDeliveryZoneGetAll200,
  PublicDietaryRegimeGetAll200,
  PublicMenuGetAll200,
  PublicMenuGetAllParams,
  PublicMenuGetOne200,
  PublicOperatingHoursGetAll200,
  PublicOrderCreateGuest201,
  PublicOrderCreateGuestBody,
  PublicPageContentGet200,
  PublicPageContentGetParams,
  PublicReviewGetApproved200,
  PublicReviewGetApprovedParams,
  ResetPasswordResponse,
  SetEmployeePasswordResponse,
} from ".././models";

export const getPublicApiCollection = (axios: AxiosInstance) => {
  /**
   * @summary Auth - Login
   */
  const publicAuthLogin = <TData = AxiosResponse<PublicAuthLogin200>>(
    publicAuthLoginBody: PublicAuthLoginBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(`/api/public/auth/login`, publicAuthLoginBody, options);
  };
  /**
   * @summary Auth - Register
   */
  const publicAuthRegister = <TData = AxiosResponse<PublicAuthRegister201>>(
    publicAuthRegisterBody: PublicAuthRegisterBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(
      `/api/public/auth/register`,
      publicAuthRegisterBody,
      options,
    );
  };
  /**
   * @summary Auth - Refresh token
   */
  const publicAuthRefresh = <TData = AxiosResponse<PublicAuthRefresh200>>(
    publicAuthRefreshBody: PublicAuthRefreshBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(
      `/api/public/auth/refresh`,
      publicAuthRefreshBody,
      options,
    );
  };
  /**
   * @summary Auth - Logout
   */
  const publicAuthLogout = <TData = AxiosResponse<PublicAuthLogout200>>(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(`/api/public/auth/logout`, undefined, options);
  };
  /**
   * @summary Auth - Request password reset
   */
  const publicAuthResetPasswordRequest = <
    TData = AxiosResponse<PublicAuthResetPasswordRequest200>,
  >(
    publicAuthResetPasswordRequestBody: PublicAuthResetPasswordRequestBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(
      `/api/public/auth/reset-password-request`,
      publicAuthResetPasswordRequestBody,
      options,
    );
  };
  /**
   * @summary Auth - Reset password
   */
  const publicAuthResetPassword = <
    TData = AxiosResponse<ResetPasswordResponse>,
  >(
    publicAuthResetPasswordBody: PublicAuthResetPasswordBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(
      `/api/public/auth/reset-password`,
      publicAuthResetPasswordBody,
      options,
    );
  };
  /**
   * @summary Auth - Validate account
   */
  const publicAuthValidateAccount = <
    TData = AxiosResponse<PublicAuthValidateAccount200>,
  >(
    publicAuthValidateAccountBody: PublicAuthValidateAccountBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(
      `/api/public/auth/validate-account`,
      publicAuthValidateAccountBody,
      options,
    );
  };
  /**
   * @summary Auth - Resend validation email
   */
  const publicAuthResendValidation = <
    TData = AxiosResponse<PublicAuthResendValidation200>,
  >(
    publicAuthResendValidationBody: PublicAuthResendValidationBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(
      `/api/public/auth/resend-validation`,
      publicAuthResendValidationBody,
      options,
    );
  };
  /**
   * @summary Auth - Set employee password
   */
  const publicAuthSetEmployeePassword = <
    TData = AxiosResponse<SetEmployeePasswordResponse>,
  >(
    publicAuthSetEmployeePasswordBody: PublicAuthSetEmployeePasswordBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(
      `/api/public/auth/set-employee-password`,
      publicAuthSetEmployeePasswordBody,
      options,
    );
  };
  /**
   * @summary Menu - List available menus (public, filterable)
   */
  const publicMenuGetAll = <TData = AxiosResponse<PublicMenuGetAll200>>(
    params?: PublicMenuGetAllParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/public/menu`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  /**
   * @summary Menu - Get a menu detail (public)
   */
  const publicMenuGetOne = <TData = AxiosResponse<PublicMenuGetOne200>>(
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/public/menu/${id}`, options);
  };
  /**
   * @summary Allergen - List allergens (public, used for filters)
   */
  const publicAllergenGetAll = <TData = AxiosResponse<PublicAllergenGetAll200>>(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/public/allergen`, options);
  };
  /**
   * @summary Dietary Regime - List dietary regimes (public, used for filters)
   */
  const publicDietaryRegimeGetAll = <
    TData = AxiosResponse<PublicDietaryRegimeGetAll200>,
  >(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/public/dietary-regime`, options);
  };
  /**
   * @summary Delivery zone - List active zones (public)
   */
  const publicDeliveryZoneGetAll = <
    TData = AxiosResponse<PublicDeliveryZoneGetAll200>,
  >(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/public/delivery-zone`, options);
  };
  /**
   * @summary Delivery zone - Calculate delivery fee for a zone or postal code (public)
   */
  const publicDeliveryZoneCalculatePrice = <
    TData = AxiosResponse<PublicDeliveryZoneCalculatePrice200>,
  >(
    publicDeliveryZoneCalculatePriceBody: PublicDeliveryZoneCalculatePriceBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(
      `/api/public/delivery-zone/calculate-price`,
      publicDeliveryZoneCalculatePriceBody,
      options,
    );
  };
  /**
   * @summary Order - Create a guest order (public)
   */
  const publicOrderCreateGuest = <
    TData = AxiosResponse<PublicOrderCreateGuest201>,
  >(
    publicOrderCreateGuestBody: PublicOrderCreateGuestBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(`/api/public/order`, publicOrderCreateGuestBody, options);
  };
  /**
   * @summary Review - List approved reviews (public)
   */
  const publicReviewGetApproved = <
    TData = AxiosResponse<PublicReviewGetApproved200>,
  >(
    params?: PublicReviewGetApprovedParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/public/review`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  /**
   * @summary Contact - Send a message (public)
   */
  const publicContactSend = <TData = AxiosResponse<PublicContactSend201>>(
    publicContactSendBody: PublicContactSendBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(`/api/public/contact`, publicContactSendBody, options);
  };
  /**
   * @summary CMS - Get page content (public)
   */
  const publicPageContentGet = <TData = AxiosResponse<PublicPageContentGet200>>(
    params: PublicPageContentGetParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/public/page-content`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  /**
   * @summary CMS - List operating hours (public)
   */
  const publicOperatingHoursGetAll = <
    TData = AxiosResponse<PublicOperatingHoursGetAll200>,
  >(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/public/operating-hours`, options);
  };
  /**
   * @summary Healthcheck - Check API health
   */
  const publicHealthcheck = <TData = AxiosResponse<HealthcheckResponse>>(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/public/healthcheck`, options);
  };
  return {
    publicAuthLogin,
    publicAuthRegister,
    publicAuthRefresh,
    publicAuthLogout,
    publicAuthResetPasswordRequest,
    publicAuthResetPassword,
    publicAuthValidateAccount,
    publicAuthResendValidation,
    publicAuthSetEmployeePassword,
    publicMenuGetAll,
    publicMenuGetOne,
    publicAllergenGetAll,
    publicDietaryRegimeGetAll,
    publicDeliveryZoneGetAll,
    publicDeliveryZoneCalculatePrice,
    publicOrderCreateGuest,
    publicReviewGetApproved,
    publicContactSend,
    publicPageContentGet,
    publicOperatingHoursGetAll,
    publicHealthcheck,
  };
};
export type PublicAuthLoginResult = AxiosResponse<PublicAuthLogin200>;
export type PublicAuthRegisterResult = AxiosResponse<PublicAuthRegister201>;
export type PublicAuthRefreshResult = AxiosResponse<PublicAuthRefresh200>;
export type PublicAuthLogoutResult = AxiosResponse<PublicAuthLogout200>;
export type PublicAuthResetPasswordRequestResult =
  AxiosResponse<PublicAuthResetPasswordRequest200>;
export type PublicAuthResetPasswordResult =
  AxiosResponse<ResetPasswordResponse>;
export type PublicAuthValidateAccountResult =
  AxiosResponse<PublicAuthValidateAccount200>;
export type PublicAuthResendValidationResult =
  AxiosResponse<PublicAuthResendValidation200>;
export type PublicAuthSetEmployeePasswordResult =
  AxiosResponse<SetEmployeePasswordResponse>;
export type PublicMenuGetAllResult = AxiosResponse<PublicMenuGetAll200>;
export type PublicMenuGetOneResult = AxiosResponse<PublicMenuGetOne200>;
export type PublicAllergenGetAllResult = AxiosResponse<PublicAllergenGetAll200>;
export type PublicDietaryRegimeGetAllResult =
  AxiosResponse<PublicDietaryRegimeGetAll200>;
export type PublicDeliveryZoneGetAllResult =
  AxiosResponse<PublicDeliveryZoneGetAll200>;
export type PublicDeliveryZoneCalculatePriceResult =
  AxiosResponse<PublicDeliveryZoneCalculatePrice200>;
export type PublicOrderCreateGuestResult =
  AxiosResponse<PublicOrderCreateGuest201>;
export type PublicReviewGetApprovedResult =
  AxiosResponse<PublicReviewGetApproved200>;
export type PublicContactSendResult = AxiosResponse<PublicContactSend201>;
export type PublicPageContentGetResult = AxiosResponse<PublicPageContentGet200>;
export type PublicOperatingHoursGetAllResult =
  AxiosResponse<PublicOperatingHoursGetAll200>;
export type PublicHealthcheckResult = AxiosResponse<HealthcheckResponse>;
