/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AxiosRequestConfig, AxiosResponse, AxiosInstance } from "axios";

import type {
  AdminAllergenCreate201,
  AdminAllergenCreateBody,
  AdminAllergenDelete200,
  AdminAllergenGetAll200,
  AdminAllergenGetAllParams,
  AdminAllergenUpdate200,
  AdminAllergenUpdateBody,
  AdminContactMessageDelete200,
  AdminContactMessageGetAll200,
  AdminContactMessageGetAllParams,
  AdminContactMessageMarkRead200,
  AdminDeliveryZoneCreate201,
  AdminDeliveryZoneCreateBody,
  AdminDeliveryZoneDelete200,
  AdminDeliveryZoneGetAll200,
  AdminDeliveryZoneGetAllParams,
  AdminDeliveryZoneUpdate200,
  AdminDeliveryZoneUpdateBody,
  AdminDietaryRegimeCreate201,
  AdminDietaryRegimeCreateBody,
  AdminDietaryRegimeDelete200,
  AdminDietaryRegimeGetAll200,
  AdminDietaryRegimeGetAllParams,
  AdminDietaryRegimeUpdate200,
  AdminDietaryRegimeUpdateBody,
  AdminDishCreate201,
  AdminDishCreateBody,
  AdminDishDelete200,
  AdminDishGetAll200,
  AdminDishGetAllParams,
  AdminDishGetOne200,
  AdminDishUpdate200,
  AdminDishUpdateBody,
  AdminEmployeeCreate201,
  AdminEmployeeCreateBody,
  AdminEmployeeDeactivate200,
  AdminEmployeeGetAll200,
  AdminEmployeeGetAllParams,
  AdminEmployeeReactivate200,
  AdminMenuCreate201,
  AdminMenuCreateBody,
  AdminMenuDelete200,
  AdminMenuGetAll200,
  AdminMenuGetAllParams,
  AdminMenuGetOne200,
  AdminMenuUpdate200,
  AdminMenuUpdateBody,
  AdminOperatingHoursGetAll200,
  AdminOperatingHoursUpsert200,
  AdminOperatingHoursUpsertBody,
  AdminOrderGetAll200,
  AdminOrderGetAllParams,
  AdminOrderGetOne200,
  AdminOrderUpdateStatus200,
  AdminOrderUpdateStatusBody,
  AdminPageContentGetAll200,
  AdminPageContentGetAllParams,
  AdminPageContentUpsert200,
  AdminPageContentUpsertBody,
  AdminReviewApprove200,
  AdminReviewDelete200,
  AdminReviewGetAll200,
  AdminReviewGetAllParams,
  AdminStatsOrdersByMenu200,
  AdminStatsOrdersByMenuParams,
  AdminStatsRevenueByMenu200,
  AdminStatsRevenueByMenuParams,
} from ".././models";

export const getAdminApiCollection = (axios: AxiosInstance) => {
  /**
   * @summary Employee - List (admin)
   */
  const adminEmployeeGetAll = <TData = AxiosResponse<AdminEmployeeGetAll200>>(
    params?: AdminEmployeeGetAllParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/admin/employee`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  /**
   * @summary Employee - Create (admin)
   */
  const adminEmployeeCreate = <TData = AxiosResponse<AdminEmployeeCreate201>>(
    adminEmployeeCreateBody: AdminEmployeeCreateBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(`/api/admin/employee`, adminEmployeeCreateBody, options);
  };
  /**
   * @summary Employee - Deactivate (admin)
   */
  const adminEmployeeDeactivate = <
    TData = AxiosResponse<AdminEmployeeDeactivate200>,
  >(
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(
      `/api/admin/employee/${id}/deactivate`,
      undefined,
      options,
    );
  };
  /**
   * @summary Employee - Reactivate (admin)
   */
  const adminEmployeeReactivate = <
    TData = AxiosResponse<AdminEmployeeReactivate200>,
  >(
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(
      `/api/admin/employee/${id}/reactivate`,
      undefined,
      options,
    );
  };
  /**
   * @summary Stats - Orders by menu (admin)
   */
  const adminStatsOrdersByMenu = <
    TData = AxiosResponse<AdminStatsOrdersByMenu200>,
  >(
    params?: AdminStatsOrdersByMenuParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/admin/stats/orders-by-menu`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  /**
   * @summary Stats - Revenue by menu (admin)
   */
  const adminStatsRevenueByMenu = <
    TData = AxiosResponse<AdminStatsRevenueByMenu200>,
  >(
    params?: AdminStatsRevenueByMenuParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/admin/stats/revenue-by-menu`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  /**
   * @summary Allergen - List allergens (admin)
   */
  const adminAllergenGetAll = <TData = AxiosResponse<AdminAllergenGetAll200>>(
    params?: AdminAllergenGetAllParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/admin/allergen`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  /**
   * @summary Allergen - Create (admin)
   */
  const adminAllergenCreate = <TData = AxiosResponse<AdminAllergenCreate201>>(
    adminAllergenCreateBody: AdminAllergenCreateBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(`/api/admin/allergen`, adminAllergenCreateBody, options);
  };
  /**
   * @summary Allergen - Update (admin)
   */
  const adminAllergenUpdate = <TData = AxiosResponse<AdminAllergenUpdate200>>(
    id: string,
    adminAllergenUpdateBody: AdminAllergenUpdateBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.put(
      `/api/admin/allergen/${id}`,
      adminAllergenUpdateBody,
      options,
    );
  };
  /**
   * @summary Allergen - Delete (admin)
   */
  const adminAllergenDelete = <TData = AxiosResponse<AdminAllergenDelete200>>(
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.delete(`/api/admin/allergen/${id}`, options);
  };
  /**
   * @summary Dietary Regime - List (admin)
   */
  const adminDietaryRegimeGetAll = <
    TData = AxiosResponse<AdminDietaryRegimeGetAll200>,
  >(
    params?: AdminDietaryRegimeGetAllParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/admin/dietary-regime`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  /**
   * @summary Dietary Regime - Create (admin)
   */
  const adminDietaryRegimeCreate = <
    TData = AxiosResponse<AdminDietaryRegimeCreate201>,
  >(
    adminDietaryRegimeCreateBody: AdminDietaryRegimeCreateBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(
      `/api/admin/dietary-regime`,
      adminDietaryRegimeCreateBody,
      options,
    );
  };
  /**
   * @summary Dietary Regime - Update (admin)
   */
  const adminDietaryRegimeUpdate = <
    TData = AxiosResponse<AdminDietaryRegimeUpdate200>,
  >(
    id: string,
    adminDietaryRegimeUpdateBody: AdminDietaryRegimeUpdateBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.put(
      `/api/admin/dietary-regime/${id}`,
      adminDietaryRegimeUpdateBody,
      options,
    );
  };
  /**
   * @summary Dietary Regime - Delete (admin)
   */
  const adminDietaryRegimeDelete = <
    TData = AxiosResponse<AdminDietaryRegimeDelete200>,
  >(
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.delete(`/api/admin/dietary-regime/${id}`, options);
  };
  /**
   * @summary Dish - List (admin)
   */
  const adminDishGetAll = <TData = AxiosResponse<AdminDishGetAll200>>(
    params?: AdminDishGetAllParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/admin/dish`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  /**
   * @summary Dish - Create (admin)
   */
  const adminDishCreate = <TData = AxiosResponse<AdminDishCreate201>>(
    adminDishCreateBody: AdminDishCreateBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(`/api/admin/dish`, adminDishCreateBody, options);
  };
  /**
   * @summary Dish - Get one (admin)
   */
  const adminDishGetOne = <TData = AxiosResponse<AdminDishGetOne200>>(
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/admin/dish/${id}`, options);
  };
  /**
   * @summary Dish - Update (admin)
   */
  const adminDishUpdate = <TData = AxiosResponse<AdminDishUpdate200>>(
    id: string,
    adminDishUpdateBody: AdminDishUpdateBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.put(`/api/admin/dish/${id}`, adminDishUpdateBody, options);
  };
  /**
   * @summary Dish - Delete (admin)
   */
  const adminDishDelete = <TData = AxiosResponse<AdminDishDelete200>>(
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.delete(`/api/admin/dish/${id}`, options);
  };
  /**
   * @summary Menu - List (admin)
   */
  const adminMenuGetAll = <TData = AxiosResponse<AdminMenuGetAll200>>(
    params?: AdminMenuGetAllParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/admin/menu`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  /**
   * @summary Menu - Create (admin)
   */
  const adminMenuCreate = <TData = AxiosResponse<AdminMenuCreate201>>(
    adminMenuCreateBody: AdminMenuCreateBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(`/api/admin/menu`, adminMenuCreateBody, options);
  };
  /**
   * @summary Menu - Get one (admin)
   */
  const adminMenuGetOne = <TData = AxiosResponse<AdminMenuGetOne200>>(
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/admin/menu/${id}`, options);
  };
  /**
   * @summary Menu - Update (admin)
   */
  const adminMenuUpdate = <TData = AxiosResponse<AdminMenuUpdate200>>(
    id: string,
    adminMenuUpdateBody: AdminMenuUpdateBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.put(`/api/admin/menu/${id}`, adminMenuUpdateBody, options);
  };
  /**
   * @summary Menu - Delete (admin)
   */
  const adminMenuDelete = <TData = AxiosResponse<AdminMenuDelete200>>(
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.delete(`/api/admin/menu/${id}`, options);
  };
  /**
   * @summary Delivery zone - List zones (admin)
   */
  const adminDeliveryZoneGetAll = <
    TData = AxiosResponse<AdminDeliveryZoneGetAll200>,
  >(
    params?: AdminDeliveryZoneGetAllParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/admin/delivery-zone`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  /**
   * @summary Delivery zone - Create (admin)
   */
  const adminDeliveryZoneCreate = <
    TData = AxiosResponse<AdminDeliveryZoneCreate201>,
  >(
    adminDeliveryZoneCreateBody: AdminDeliveryZoneCreateBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(
      `/api/admin/delivery-zone`,
      adminDeliveryZoneCreateBody,
      options,
    );
  };
  /**
   * @summary Delivery zone - Update (admin)
   */
  const adminDeliveryZoneUpdate = <
    TData = AxiosResponse<AdminDeliveryZoneUpdate200>,
  >(
    id: string,
    adminDeliveryZoneUpdateBody: AdminDeliveryZoneUpdateBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.put(
      `/api/admin/delivery-zone/${id}`,
      adminDeliveryZoneUpdateBody,
      options,
    );
  };
  /**
   * @summary Delivery zone - Delete (admin)
   */
  const adminDeliveryZoneDelete = <
    TData = AxiosResponse<AdminDeliveryZoneDelete200>,
  >(
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.delete(`/api/admin/delivery-zone/${id}`, options);
  };
  /**
   * @summary Order - List (admin)
   */
  const adminOrderGetAll = <TData = AxiosResponse<AdminOrderGetAll200>>(
    params?: AdminOrderGetAllParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/admin/order`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  /**
   * @summary Order - Get an order detail (admin)
   */
  const adminOrderGetOne = <TData = AxiosResponse<AdminOrderGetOne200>>(
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/admin/order/${id}`, options);
  };
  /**
   * @summary Order - Update status (admin)
   */
  const adminOrderUpdateStatus = <
    TData = AxiosResponse<AdminOrderUpdateStatus200>,
  >(
    id: string,
    adminOrderUpdateStatusBody: AdminOrderUpdateStatusBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.patch(
      `/api/admin/order/${id}/status`,
      adminOrderUpdateStatusBody,
      options,
    );
  };
  /**
   * @summary Review - List all reviews for moderation (staff)
   */
  const adminReviewGetAll = <TData = AxiosResponse<AdminReviewGetAll200>>(
    params?: AdminReviewGetAllParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/admin/review`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  /**
   * @summary Review - Approve a review (staff)
   */
  const adminReviewApprove = <TData = AxiosResponse<AdminReviewApprove200>>(
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(`/api/admin/review/${id}/approve`, undefined, options);
  };
  /**
   * @summary Review - Delete a review (staff)
   */
  const adminReviewDelete = <TData = AxiosResponse<AdminReviewDelete200>>(
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.delete(`/api/admin/review/${id}`, options);
  };
  /**
   * @summary Contact - List contact messages (staff)
   */
  const adminContactMessageGetAll = <
    TData = AxiosResponse<AdminContactMessageGetAll200>,
  >(
    params?: AdminContactMessageGetAllParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/admin/contact-message`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  /**
   * @summary Contact - Mark a message as read (staff)
   */
  const adminContactMessageMarkRead = <
    TData = AxiosResponse<AdminContactMessageMarkRead200>,
  >(
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(
      `/api/admin/contact-message/${id}/read`,
      undefined,
      options,
    );
  };
  /**
   * @summary Contact - Delete a message (staff)
   */
  const adminContactMessageDelete = <
    TData = AxiosResponse<AdminContactMessageDelete200>,
  >(
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.delete(`/api/admin/contact-message/${id}`, options);
  };
  /**
   * @summary CMS - List page content (staff)
   */
  const adminPageContentGetAll = <
    TData = AxiosResponse<AdminPageContentGetAll200>,
  >(
    params?: AdminPageContentGetAllParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/admin/page-content`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  /**
   * @summary CMS - Upsert a page content section (staff)
   */
  const adminPageContentUpsert = <
    TData = AxiosResponse<AdminPageContentUpsert200>,
  >(
    adminPageContentUpsertBody: AdminPageContentUpsertBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.put(
      `/api/admin/page-content`,
      adminPageContentUpsertBody,
      options,
    );
  };
  /**
   * @summary CMS - List operating hours (staff)
   */
  const adminOperatingHoursGetAll = <
    TData = AxiosResponse<AdminOperatingHoursGetAll200>,
  >(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/admin/operating-hours`, options);
  };
  /**
   * @summary CMS - Upsert operating hours (staff)
   */
  const adminOperatingHoursUpsert = <
    TData = AxiosResponse<AdminOperatingHoursUpsert200>,
  >(
    adminOperatingHoursUpsertBody: AdminOperatingHoursUpsertBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.put(
      `/api/admin/operating-hours`,
      adminOperatingHoursUpsertBody,
      options,
    );
  };
  return {
    adminEmployeeGetAll,
    adminEmployeeCreate,
    adminEmployeeDeactivate,
    adminEmployeeReactivate,
    adminStatsOrdersByMenu,
    adminStatsRevenueByMenu,
    adminAllergenGetAll,
    adminAllergenCreate,
    adminAllergenUpdate,
    adminAllergenDelete,
    adminDietaryRegimeGetAll,
    adminDietaryRegimeCreate,
    adminDietaryRegimeUpdate,
    adminDietaryRegimeDelete,
    adminDishGetAll,
    adminDishCreate,
    adminDishGetOne,
    adminDishUpdate,
    adminDishDelete,
    adminMenuGetAll,
    adminMenuCreate,
    adminMenuGetOne,
    adminMenuUpdate,
    adminMenuDelete,
    adminDeliveryZoneGetAll,
    adminDeliveryZoneCreate,
    adminDeliveryZoneUpdate,
    adminDeliveryZoneDelete,
    adminOrderGetAll,
    adminOrderGetOne,
    adminOrderUpdateStatus,
    adminReviewGetAll,
    adminReviewApprove,
    adminReviewDelete,
    adminContactMessageGetAll,
    adminContactMessageMarkRead,
    adminContactMessageDelete,
    adminPageContentGetAll,
    adminPageContentUpsert,
    adminOperatingHoursGetAll,
    adminOperatingHoursUpsert,
  };
};
export type AdminEmployeeGetAllResult = AxiosResponse<AdminEmployeeGetAll200>;
export type AdminEmployeeCreateResult = AxiosResponse<AdminEmployeeCreate201>;
export type AdminEmployeeDeactivateResult =
  AxiosResponse<AdminEmployeeDeactivate200>;
export type AdminEmployeeReactivateResult =
  AxiosResponse<AdminEmployeeReactivate200>;
export type AdminStatsOrdersByMenuResult =
  AxiosResponse<AdminStatsOrdersByMenu200>;
export type AdminStatsRevenueByMenuResult =
  AxiosResponse<AdminStatsRevenueByMenu200>;
export type AdminAllergenGetAllResult = AxiosResponse<AdminAllergenGetAll200>;
export type AdminAllergenCreateResult = AxiosResponse<AdminAllergenCreate201>;
export type AdminAllergenUpdateResult = AxiosResponse<AdminAllergenUpdate200>;
export type AdminAllergenDeleteResult = AxiosResponse<AdminAllergenDelete200>;
export type AdminDietaryRegimeGetAllResult =
  AxiosResponse<AdminDietaryRegimeGetAll200>;
export type AdminDietaryRegimeCreateResult =
  AxiosResponse<AdminDietaryRegimeCreate201>;
export type AdminDietaryRegimeUpdateResult =
  AxiosResponse<AdminDietaryRegimeUpdate200>;
export type AdminDietaryRegimeDeleteResult =
  AxiosResponse<AdminDietaryRegimeDelete200>;
export type AdminDishGetAllResult = AxiosResponse<AdminDishGetAll200>;
export type AdminDishCreateResult = AxiosResponse<AdminDishCreate201>;
export type AdminDishGetOneResult = AxiosResponse<AdminDishGetOne200>;
export type AdminDishUpdateResult = AxiosResponse<AdminDishUpdate200>;
export type AdminDishDeleteResult = AxiosResponse<AdminDishDelete200>;
export type AdminMenuGetAllResult = AxiosResponse<AdminMenuGetAll200>;
export type AdminMenuCreateResult = AxiosResponse<AdminMenuCreate201>;
export type AdminMenuGetOneResult = AxiosResponse<AdminMenuGetOne200>;
export type AdminMenuUpdateResult = AxiosResponse<AdminMenuUpdate200>;
export type AdminMenuDeleteResult = AxiosResponse<AdminMenuDelete200>;
export type AdminDeliveryZoneGetAllResult =
  AxiosResponse<AdminDeliveryZoneGetAll200>;
export type AdminDeliveryZoneCreateResult =
  AxiosResponse<AdminDeliveryZoneCreate201>;
export type AdminDeliveryZoneUpdateResult =
  AxiosResponse<AdminDeliveryZoneUpdate200>;
export type AdminDeliveryZoneDeleteResult =
  AxiosResponse<AdminDeliveryZoneDelete200>;
export type AdminOrderGetAllResult = AxiosResponse<AdminOrderGetAll200>;
export type AdminOrderGetOneResult = AxiosResponse<AdminOrderGetOne200>;
export type AdminOrderUpdateStatusResult =
  AxiosResponse<AdminOrderUpdateStatus200>;
export type AdminReviewGetAllResult = AxiosResponse<AdminReviewGetAll200>;
export type AdminReviewApproveResult = AxiosResponse<AdminReviewApprove200>;
export type AdminReviewDeleteResult = AxiosResponse<AdminReviewDelete200>;
export type AdminContactMessageGetAllResult =
  AxiosResponse<AdminContactMessageGetAll200>;
export type AdminContactMessageMarkReadResult =
  AxiosResponse<AdminContactMessageMarkRead200>;
export type AdminContactMessageDeleteResult =
  AxiosResponse<AdminContactMessageDelete200>;
export type AdminPageContentGetAllResult =
  AxiosResponse<AdminPageContentGetAll200>;
export type AdminPageContentUpsertResult =
  AxiosResponse<AdminPageContentUpsert200>;
export type AdminOperatingHoursGetAllResult =
  AxiosResponse<AdminOperatingHoursGetAll200>;
export type AdminOperatingHoursUpsertResult =
  AxiosResponse<AdminOperatingHoursUpsert200>;
