/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

/**
 * @summary Employee - List (admin)
 */
export const zodAdminEmployeeGetAllQueryLimitMax = 100;

export const zodAdminEmployeeGetAllQueryOffsetMin = 0;

export const zodAdminEmployeeGetAllQueryParams = zod.object({
  isActive: zod.enum(["true", "false"]).optional(),
  search: zod.string().optional(),
  limit: zod
    .number()
    .min(1)
    .max(zodAdminEmployeeGetAllQueryLimitMax)
    .optional(),
  offset: zod.number().min(zodAdminEmployeeGetAllQueryOffsetMin).nullish(),
  sortBy: zod
    .enum(["email", "lastName", "firstName", "createdAt", "updatedAt"])
    .optional(),
  sortOrder: zod.enum(["ASC", "DESC"]).optional(),
});

export const zodAdminEmployeeGetAllResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      email: zod.string().email(),
      firstName: zod.string(),
      lastName: zod.string(),
      role: zod.enum(["USER", "EMPLOYEE", "ADMIN"]),
      isActive: zod.boolean(),
      emailVerified: zod.boolean(),
      createdAt: zod.string().datetime({}),
      updatedAt: zod.string().datetime({}),
    }),
  ),
  totalCount: zod.number(),
});

/**
 * @summary Employee - Create (admin)
 */
export const zodAdminEmployeeCreateBodyFirstNameMax = 255;

export const zodAdminEmployeeCreateBodyLastNameMax = 255;

export const zodAdminEmployeeCreateBodyPhoneMax = 50;

export const zodAdminEmployeeCreateBody = zod.object({
  email: zod.string().email(),
  firstName: zod.string().min(1).max(zodAdminEmployeeCreateBodyFirstNameMax),
  lastName: zod.string().min(1).max(zodAdminEmployeeCreateBodyLastNameMax),
  phone: zod.string().min(1).max(zodAdminEmployeeCreateBodyPhoneMax).nullish(),
});

/**
 * @summary Employee - Deactivate (admin)
 */
export const zodAdminEmployeeDeactivateParams = zod.object({
  id: zod.string().uuid(),
});

export const zodAdminEmployeeDeactivateResponse = zod.object({
  id: zod.string().uuid(),
  email: zod.string().email(),
  firstName: zod.string(),
  lastName: zod.string(),
  role: zod.enum(["USER", "EMPLOYEE", "ADMIN"]),
  admin: zod.boolean(),
  phone: zod.string().nullable(),
  address: zod.string().nullable(),
  city: zod.string().nullable(),
  postalCode: zod.string().nullable(),
  isActive: zod.boolean(),
  emailVerified: zod.boolean(),
  preferredLanguage: zod.string(),
  lastLoginAt: zod.string().datetime({}).nullable(),
  createdAt: zod.string().datetime({}),
  updatedAt: zod.string().datetime({}),
});

/**
 * @summary Employee - Reactivate (admin)
 */
export const zodAdminEmployeeReactivateParams = zod.object({
  id: zod.string().uuid(),
});

export const zodAdminEmployeeReactivateResponse = zod.object({
  id: zod.string().uuid(),
  email: zod.string().email(),
  firstName: zod.string(),
  lastName: zod.string(),
  role: zod.enum(["USER", "EMPLOYEE", "ADMIN"]),
  admin: zod.boolean(),
  phone: zod.string().nullable(),
  address: zod.string().nullable(),
  city: zod.string().nullable(),
  postalCode: zod.string().nullable(),
  isActive: zod.boolean(),
  emailVerified: zod.boolean(),
  preferredLanguage: zod.string(),
  lastLoginAt: zod.string().datetime({}).nullable(),
  createdAt: zod.string().datetime({}),
  updatedAt: zod.string().datetime({}),
});

/**
 * @summary Stats - Orders by menu (admin)
 */
export const zodAdminStatsOrdersByMenuQueryParams = zod.object({
  menuId: zod.string().uuid().optional(),
  from: zod.string().nullish(),
  to: zod.string().nullish(),
});

export const zodAdminStatsOrdersByMenuResponse = zod.object({
  items: zod.array(
    zod.object({
      menuId: zod.string(),
      menuName: zod.string(),
      orderCount: zod.number(),
      totalQuantity: zod.number(),
    }),
  ),
});

/**
 * @summary Stats - Revenue by menu (admin)
 */
export const zodAdminStatsRevenueByMenuQueryParams = zod.object({
  menuId: zod.string().uuid().optional(),
  from: zod.string().nullish(),
  to: zod.string().nullish(),
});

export const zodAdminStatsRevenueByMenuResponse = zod.object({
  items: zod.array(
    zod.object({
      menuId: zod.string(),
      menuName: zod.string(),
      revenue: zod.number(),
    }),
  ),
});

/**
 * @summary Allergen - List allergens (admin)
 */
export const zodAdminAllergenGetAllQueryLimitMax = 100;

export const zodAdminAllergenGetAllQueryOffsetMin = 0;

export const zodAdminAllergenGetAllQueryParams = zod.object({
  search: zod.string().optional(),
  limit: zod
    .number()
    .min(1)
    .max(zodAdminAllergenGetAllQueryLimitMax)
    .optional(),
  offset: zod.number().min(zodAdminAllergenGetAllQueryOffsetMin).nullish(),
  sortBy: zod.enum(["name", "createdAt"]).optional(),
  sortOrder: zod.enum(["ASC", "DESC"]).optional(),
});

export const zodAdminAllergenGetAllResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      name: zod.string(),
      icon: zod.string().nullable(),
      createdAt: zod.string().datetime({}),
    }),
  ),
  totalCount: zod.number(),
});

/**
 * @summary Allergen - Create (admin)
 */
export const zodAdminAllergenCreateBodyNameMax = 255;

export const zodAdminAllergenCreateBodyIconMax = 255;

export const zodAdminAllergenCreateBody = zod.object({
  name: zod.string().min(1).max(zodAdminAllergenCreateBodyNameMax),
  icon: zod.string().max(zodAdminAllergenCreateBodyIconMax).nullish(),
});

/**
 * @summary Allergen - Update (admin)
 */
export const zodAdminAllergenUpdateParams = zod.object({
  id: zod.string().uuid(),
});

export const zodAdminAllergenUpdateBodyNameMax = 255;

export const zodAdminAllergenUpdateBodyIconMax = 255;

export const zodAdminAllergenUpdateBody = zod.object({
  name: zod.string().min(1).max(zodAdminAllergenUpdateBodyNameMax).optional(),
  icon: zod.string().max(zodAdminAllergenUpdateBodyIconMax).nullish(),
});

export const zodAdminAllergenUpdateResponse = zod.object({
  id: zod.string().uuid(),
  name: zod.string(),
  icon: zod.string().nullable(),
  createdAt: zod.string().datetime({}),
});

/**
 * @summary Allergen - Delete (admin)
 */
export const zodAdminAllergenDeleteParams = zod.object({
  id: zod.string().uuid(),
});

export const zodAdminAllergenDeleteResponse = zod.object({
  message: zod.string(),
  code: zod.string(),
});

/**
 * @summary Dietary Regime - List (admin)
 */
export const zodAdminDietaryRegimeGetAllQueryLimitMax = 100;

export const zodAdminDietaryRegimeGetAllQueryOffsetMin = 0;

export const zodAdminDietaryRegimeGetAllQueryParams = zod.object({
  search: zod.string().optional(),
  limit: zod
    .number()
    .min(1)
    .max(zodAdminDietaryRegimeGetAllQueryLimitMax)
    .optional(),
  offset: zod.number().min(zodAdminDietaryRegimeGetAllQueryOffsetMin).nullish(),
  sortBy: zod.enum(["name", "createdAt"]).optional(),
  sortOrder: zod.enum(["ASC", "DESC"]).optional(),
});

export const zodAdminDietaryRegimeGetAllResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      name: zod.string(),
      description: zod.string().nullable(),
      createdAt: zod.string().datetime({}),
    }),
  ),
  totalCount: zod.number(),
});

/**
 * @summary Dietary Regime - Create (admin)
 */
export const zodAdminDietaryRegimeCreateBodyNameMax = 255;

export const zodAdminDietaryRegimeCreateBody = zod.object({
  name: zod.string().min(1).max(zodAdminDietaryRegimeCreateBodyNameMax),
  description: zod.string().nullish(),
});

/**
 * @summary Dietary Regime - Update (admin)
 */
export const zodAdminDietaryRegimeUpdateParams = zod.object({
  id: zod.string().uuid(),
});

export const zodAdminDietaryRegimeUpdateBodyNameMax = 255;

export const zodAdminDietaryRegimeUpdateBody = zod.object({
  name: zod
    .string()
    .min(1)
    .max(zodAdminDietaryRegimeUpdateBodyNameMax)
    .optional(),
  description: zod.string().nullish(),
});

export const zodAdminDietaryRegimeUpdateResponse = zod.object({
  id: zod.string().uuid(),
  name: zod.string(),
  description: zod.string().nullable(),
  createdAt: zod.string().datetime({}),
});

/**
 * @summary Dietary Regime - Delete (admin)
 */
export const zodAdminDietaryRegimeDeleteParams = zod.object({
  id: zod.string().uuid(),
});

export const zodAdminDietaryRegimeDeleteResponse = zod.object({
  message: zod.string(),
  code: zod.string(),
});

/**
 * @summary Dish - List (admin)
 */
export const zodAdminDishGetAllQueryLimitMax = 100;

export const zodAdminDishGetAllQueryOffsetMin = 0;

export const zodAdminDishGetAllQueryParams = zod.object({
  category: zod.enum(["entree", "plat", "dessert"]).optional(),
  isAvailable: zod.enum(["true", "false"]).optional(),
  search: zod.string().optional(),
  limit: zod.number().min(1).max(zodAdminDishGetAllQueryLimitMax).optional(),
  offset: zod.number().min(zodAdminDishGetAllQueryOffsetMin).nullish(),
  sortBy: zod
    .enum(["name", "price", "category", "createdAt", "updatedAt"])
    .optional(),
  sortOrder: zod.enum(["ASC", "DESC"]).optional(),
});

export const zodAdminDishGetAllResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      name: zod.string(),
      description: zod.string().nullable(),
      category: zod.enum(["entree", "plat", "dessert"]),
      price: zod.number().nullable(),
      imageUrl: zod.string().nullable(),
      isAvailable: zod.boolean(),
      createdAt: zod.string().datetime({}),
      updatedAt: zod.string().datetime({}),
    }),
  ),
  totalCount: zod.number(),
});

/**
 * @summary Dish - Create (admin)
 */
export const zodAdminDishCreateBodyNameMax = 255;

export const zodAdminDishCreateBodyPriceMin = 0;

export const zodAdminDishCreateBody = zod.object({
  name: zod.string().min(1).max(zodAdminDishCreateBodyNameMax),
  description: zod.string().nullish(),
  category: zod.enum(["entree", "plat", "dessert"]),
  price: zod.number().min(zodAdminDishCreateBodyPriceMin).nullish(),
  imageUrl: zod.string().nullish(),
  isAvailable: zod.boolean().optional(),
  allergenIds: zod.array(zod.string().uuid()).optional(),
});

/**
 * @summary Dish - Get one (admin)
 */
export const zodAdminDishGetOneParams = zod.object({
  id: zod.string().uuid(),
});

export const zodAdminDishGetOneResponse = zod.object({
  id: zod.string().uuid(),
  name: zod.string(),
  description: zod.string().nullable(),
  category: zod.enum(["entree", "plat", "dessert"]),
  price: zod.number().nullable(),
  imageUrl: zod.string().nullable(),
  isAvailable: zod.boolean(),
  createdAt: zod.string().datetime({}),
  updatedAt: zod.string().datetime({}),
  allergens: zod.array(
    zod.object({
      id: zod.string().uuid(),
      name: zod.string(),
      icon: zod.string().nullable(),
    }),
  ),
});

/**
 * @summary Dish - Update (admin)
 */
export const zodAdminDishUpdateParams = zod.object({
  id: zod.string().uuid(),
});

export const zodAdminDishUpdateBodyNameMax = 255;

export const zodAdminDishUpdateBodyPriceMin = 0;

export const zodAdminDishUpdateBody = zod.object({
  name: zod.string().min(1).max(zodAdminDishUpdateBodyNameMax).optional(),
  description: zod.string().nullish(),
  category: zod.enum(["entree", "plat", "dessert"]).optional(),
  price: zod.number().min(zodAdminDishUpdateBodyPriceMin).nullish(),
  imageUrl: zod.string().nullish(),
  isAvailable: zod.boolean().optional(),
  allergenIds: zod.array(zod.string().uuid()).optional(),
});

export const zodAdminDishUpdateResponse = zod.object({
  id: zod.string().uuid(),
  name: zod.string(),
  description: zod.string().nullable(),
  category: zod.enum(["entree", "plat", "dessert"]),
  price: zod.number().nullable(),
  imageUrl: zod.string().nullable(),
  isAvailable: zod.boolean(),
  createdAt: zod.string().datetime({}),
  updatedAt: zod.string().datetime({}),
  allergens: zod.array(
    zod.object({
      id: zod.string().uuid(),
      name: zod.string(),
      icon: zod.string().nullable(),
    }),
  ),
});

/**
 * @summary Dish - Delete (admin)
 */
export const zodAdminDishDeleteParams = zod.object({
  id: zod.string().uuid(),
});

export const zodAdminDishDeleteResponse = zod.object({
  message: zod.string(),
  code: zod.string(),
});

/**
 * @summary Menu - List (admin)
 */
export const zodAdminMenuGetAllQueryLimitMax = 100;

export const zodAdminMenuGetAllQueryOffsetMin = 0;

export const zodAdminMenuGetAllQueryParams = zod.object({
  theme: zod.string().optional(),
  dietaryRegimeId: zod.string().uuid().optional(),
  priceMax: zod.number().nullish(),
  priceMin: zod.number().nullish(),
  maxMinPersons: zod.number().nullish(),
  search: zod.string().optional(),
  isAvailable: zod.enum(["true", "false"]).optional(),
  limit: zod.number().min(1).max(zodAdminMenuGetAllQueryLimitMax).optional(),
  offset: zod.number().min(zodAdminMenuGetAllQueryOffsetMin).nullish(),
  sortBy: zod
    .enum(["name", "price", "minPersons", "createdAt", "updatedAt"])
    .optional(),
  sortOrder: zod.enum(["ASC", "DESC"]).optional(),
});

export const zodAdminMenuGetAllResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      name: zod.string(),
      description: zod.string().nullable(),
      theme: zod.string().nullable(),
      price: zod.number(),
      minPersons: zod.number(),
      maxPersons: zod.number().nullable(),
      stock: zod.number().nullable(),
      isAvailable: zod.boolean(),
      imageUrl: zod.string().nullable(),
    }),
  ),
  totalCount: zod.number(),
});

/**
 * @summary Menu - Create (admin)
 */
export const zodAdminMenuCreateBodyNameMax = 255;

export const zodAdminMenuCreateBodyThemeMax = 255;

export const zodAdminMenuCreateBodyPriceMin = 0;

export const zodAdminMenuCreateBodyStockMin = 0;

export const zodAdminMenuCreateBody = zod.object({
  name: zod.string().min(1).max(zodAdminMenuCreateBodyNameMax),
  description: zod.string().nullish(),
  theme: zod.string().max(zodAdminMenuCreateBodyThemeMax).nullish(),
  price: zod.number().min(zodAdminMenuCreateBodyPriceMin),
  minPersons: zod.number().min(1).optional(),
  maxPersons: zod.number().min(1).nullish(),
  stock: zod.number().min(zodAdminMenuCreateBodyStockMin).nullish(),
  conditions: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
  isAvailable: zod.boolean().optional(),
  dishIds: zod.array(zod.string().uuid()).optional(),
  dietaryRegimeIds: zod.array(zod.string().uuid()).optional(),
});

/**
 * @summary Menu - Get one (admin)
 */
export const zodAdminMenuGetOneParams = zod.object({
  id: zod.string().uuid(),
});

export const zodAdminMenuGetOneResponse = zod.object({
  id: zod.string().uuid(),
  name: zod.string(),
  description: zod.string().nullable(),
  theme: zod.string().nullable(),
  price: zod.number(),
  minPersons: zod.number(),
  maxPersons: zod.number().nullable(),
  stock: zod.number().nullable(),
  conditions: zod.string().nullable(),
  imageUrl: zod.string().nullable(),
  isAvailable: zod.boolean(),
  createdAt: zod.string().datetime({}),
  updatedAt: zod.string().datetime({}),
  dishes: zod.array(
    zod.object({
      id: zod.string().uuid(),
      name: zod.string(),
      category: zod.enum(["entree", "plat", "dessert"]),
      description: zod.string().nullable(),
      price: zod.number().nullable(),
      allergens: zod.array(
        zod.object({
          id: zod.string().uuid(),
          name: zod.string(),
          icon: zod.string().nullable(),
        }),
      ),
    }),
  ),
  dietaryRegimes: zod.array(
    zod.object({
      id: zod.string().uuid(),
      name: zod.string(),
    }),
  ),
});

/**
 * @summary Menu - Update (admin)
 */
export const zodAdminMenuUpdateParams = zod.object({
  id: zod.string().uuid(),
});

export const zodAdminMenuUpdateBodyNameMax = 255;

export const zodAdminMenuUpdateBodyThemeMax = 255;

export const zodAdminMenuUpdateBodyPriceMin = 0;

export const zodAdminMenuUpdateBodyStockMin = 0;

export const zodAdminMenuUpdateBody = zod.object({
  name: zod.string().min(1).max(zodAdminMenuUpdateBodyNameMax).optional(),
  description: zod.string().nullish(),
  theme: zod.string().max(zodAdminMenuUpdateBodyThemeMax).nullish(),
  price: zod.number().min(zodAdminMenuUpdateBodyPriceMin).optional(),
  minPersons: zod.number().min(1).optional(),
  maxPersons: zod.number().min(1).nullish(),
  stock: zod.number().min(zodAdminMenuUpdateBodyStockMin).nullish(),
  conditions: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
  isAvailable: zod.boolean().optional(),
  dishIds: zod.array(zod.string().uuid()).optional(),
  dietaryRegimeIds: zod.array(zod.string().uuid()).optional(),
});

export const zodAdminMenuUpdateResponse = zod.object({
  id: zod.string().uuid(),
  name: zod.string(),
  description: zod.string().nullable(),
  theme: zod.string().nullable(),
  price: zod.number(),
  minPersons: zod.number(),
  maxPersons: zod.number().nullable(),
  stock: zod.number().nullable(),
  conditions: zod.string().nullable(),
  imageUrl: zod.string().nullable(),
  isAvailable: zod.boolean(),
  createdAt: zod.string().datetime({}),
  updatedAt: zod.string().datetime({}),
  dishes: zod.array(
    zod.object({
      id: zod.string().uuid(),
      name: zod.string(),
      category: zod.enum(["entree", "plat", "dessert"]),
      description: zod.string().nullable(),
      price: zod.number().nullable(),
      allergens: zod.array(
        zod.object({
          id: zod.string().uuid(),
          name: zod.string(),
          icon: zod.string().nullable(),
        }),
      ),
    }),
  ),
  dietaryRegimes: zod.array(
    zod.object({
      id: zod.string().uuid(),
      name: zod.string(),
    }),
  ),
});

/**
 * @summary Menu - Delete (admin)
 */
export const zodAdminMenuDeleteParams = zod.object({
  id: zod.string().uuid(),
});

export const zodAdminMenuDeleteResponse = zod.object({
  message: zod.string(),
  code: zod.string(),
});

/**
 * @summary Delivery zone - List zones (admin)
 */
export const zodAdminDeliveryZoneGetAllQueryLimitMax = 100;

export const zodAdminDeliveryZoneGetAllQueryOffsetMin = 0;

export const zodAdminDeliveryZoneGetAllQueryParams = zod.object({
  search: zod.string().optional(),
  isActive: zod.enum(["true", "false"]).optional(),
  limit: zod
    .number()
    .min(1)
    .max(zodAdminDeliveryZoneGetAllQueryLimitMax)
    .optional(),
  offset: zod.number().min(zodAdminDeliveryZoneGetAllQueryOffsetMin).nullish(),
  sortBy: zod.enum(["name", "city", "distanceKm", "createdAt"]).optional(),
  sortOrder: zod.enum(["ASC", "DESC"]).optional(),
});

export const zodAdminDeliveryZoneGetAllResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      name: zod.string(),
      postalCode: zod.string().nullable(),
      city: zod.string().nullable(),
      distanceKm: zod.number(),
      isActive: zod.boolean(),
      createdAt: zod.string().datetime({}),
    }),
  ),
  totalCount: zod.number(),
});

/**
 * @summary Delivery zone - Create (admin)
 */
export const zodAdminDeliveryZoneCreateBodyNameMax = 255;

export const zodAdminDeliveryZoneCreateBodyPostalCodeMax = 20;

export const zodAdminDeliveryZoneCreateBodyCityMax = 255;

export const zodAdminDeliveryZoneCreateBodyDistanceKmMin = 0;

export const zodAdminDeliveryZoneCreateBody = zod.object({
  name: zod.string().min(1).max(zodAdminDeliveryZoneCreateBodyNameMax),
  postalCode: zod
    .string()
    .max(zodAdminDeliveryZoneCreateBodyPostalCodeMax)
    .nullish(),
  city: zod.string().max(zodAdminDeliveryZoneCreateBodyCityMax).nullish(),
  distanceKm: zod
    .number()
    .min(zodAdminDeliveryZoneCreateBodyDistanceKmMin)
    .optional(),
  isActive: zod.boolean().optional(),
});

/**
 * @summary Delivery zone - Update (admin)
 */
export const zodAdminDeliveryZoneUpdateParams = zod.object({
  id: zod.string().uuid(),
});

export const zodAdminDeliveryZoneUpdateBodyNameMax = 255;

export const zodAdminDeliveryZoneUpdateBodyPostalCodeMax = 20;

export const zodAdminDeliveryZoneUpdateBodyCityMax = 255;

export const zodAdminDeliveryZoneUpdateBodyDistanceKmMin = 0;

export const zodAdminDeliveryZoneUpdateBody = zod.object({
  name: zod
    .string()
    .min(1)
    .max(zodAdminDeliveryZoneUpdateBodyNameMax)
    .optional(),
  postalCode: zod
    .string()
    .max(zodAdminDeliveryZoneUpdateBodyPostalCodeMax)
    .nullish(),
  city: zod.string().max(zodAdminDeliveryZoneUpdateBodyCityMax).nullish(),
  distanceKm: zod
    .number()
    .min(zodAdminDeliveryZoneUpdateBodyDistanceKmMin)
    .optional(),
  isActive: zod.boolean().optional(),
});

export const zodAdminDeliveryZoneUpdateResponse = zod.object({
  id: zod.string().uuid(),
  name: zod.string(),
  postalCode: zod.string().nullable(),
  city: zod.string().nullable(),
  distanceKm: zod.number(),
  isActive: zod.boolean(),
  createdAt: zod.string().datetime({}),
});

/**
 * @summary Delivery zone - Delete (admin)
 */
export const zodAdminDeliveryZoneDeleteParams = zod.object({
  id: zod.string().uuid(),
});

export const zodAdminDeliveryZoneDeleteResponse = zod.object({
  message: zod.string(),
  code: zod.string(),
});

/**
 * @summary Order - List (admin)
 */
export const zodAdminOrderGetAllQueryLimitMax = 100;

export const zodAdminOrderGetAllQueryOffsetMin = 0;

export const zodAdminOrderGetAllQueryParams = zod.object({
  status: zod
    .enum([
      "PENDING",
      "ACCEPTED",
      "PREPARING",
      "DELIVERING",
      "DELIVERED",
      "AWAITING_MATERIAL_RETURN",
      "COMPLETED",
      "REJECTED",
      "CANCELLED",
    ])
    .optional(),
  search: zod.string().optional(),
  limit: zod.number().min(1).max(zodAdminOrderGetAllQueryLimitMax).optional(),
  offset: zod.number().min(zodAdminOrderGetAllQueryOffsetMin).nullish(),
  sortBy: zod
    .enum(["createdAt", "updatedAt", "totalPrice", "status", "deliveryDate"])
    .optional(),
  sortOrder: zod.enum(["ASC", "DESC"]).optional(),
});

export const zodAdminOrderGetAllResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      status: zod.enum([
        "PENDING",
        "ACCEPTED",
        "PREPARING",
        "DELIVERING",
        "DELIVERED",
        "AWAITING_MATERIAL_RETURN",
        "COMPLETED",
        "REJECTED",
        "CANCELLED",
      ]),
      deliveryDate: zod.string().nullable(),
      deliveryFee: zod.number(),
      totalPrice: zod.number(),
      itemCount: zod.number(),
      createdAt: zod.string().datetime({}),
      userId: zod.string().uuid().nullable(),
      guestEmail: zod.string().nullable(),
      guestName: zod.string().nullable(),
      deliveryCity: zod.string().nullable(),
    }),
  ),
  totalCount: zod.number(),
});

/**
 * @summary Order - Get an order detail (admin)
 */
export const zodAdminOrderGetOneParams = zod.object({
  id: zod.string().uuid(),
});

export const zodAdminOrderGetOneResponse = zod.object({
  id: zod.string().uuid(),
  status: zod.enum([
    "PENDING",
    "ACCEPTED",
    "PREPARING",
    "DELIVERING",
    "DELIVERED",
    "AWAITING_MATERIAL_RETURN",
    "COMPLETED",
    "REJECTED",
    "CANCELLED",
  ]),
  userId: zod.string().uuid().nullable(),
  guestEmail: zod.string().nullable(),
  guestName: zod.string().nullable(),
  guestPhone: zod.string().nullable(),
  deliveryAddress: zod.string().nullable(),
  deliveryCity: zod.string().nullable(),
  deliveryPostalCode: zod.string().nullable(),
  deliveryZoneId: zod.string().uuid().nullable(),
  deliveryDate: zod.string().nullable(),
  deliveryFee: zod.number(),
  totalPrice: zod.number(),
  notes: zod.string().nullable(),
  createdAt: zod.string().datetime({}),
  updatedAt: zod.string().datetime({}),
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      menuId: zod.string().uuid(),
      menuName: zod.string().nullable(),
      quantity: zod.number(),
      unitPrice: zod.number(),
      lineTotal: zod.number(),
      discountApplied: zod.boolean(),
    }),
  ),
  rejectionReason: zod.string().nullable(),
  rejectedBy: zod.string().uuid().nullable(),
  rejectedAt: zod.string().datetime({}).nullable(),
  materialReturnDeadline: zod.string().datetime({}).nullable(),
  materialPenaltyApplied: zod.boolean(),
  penaltyAmount: zod.number().nullable(),
  history: zod.array(
    zod.object({
      id: zod.string().uuid(),
      oldStatus: zod
        .enum([
          "PENDING",
          "ACCEPTED",
          "PREPARING",
          "DELIVERING",
          "DELIVERED",
          "AWAITING_MATERIAL_RETURN",
          "COMPLETED",
          "REJECTED",
          "CANCELLED",
        ])
        .nullable(),
      newStatus: zod.enum([
        "PENDING",
        "ACCEPTED",
        "PREPARING",
        "DELIVERING",
        "DELIVERED",
        "AWAITING_MATERIAL_RETURN",
        "COMPLETED",
        "REJECTED",
        "CANCELLED",
      ]),
      changedBy: zod.string().uuid().nullable(),
      reason: zod.string().nullable(),
      contactMode: zod.string().nullable(),
      createdAt: zod.string().datetime({}),
    }),
  ),
});

/**
 * @summary Order - Update status (admin)
 */
export const zodAdminOrderUpdateStatusParams = zod.object({
  id: zod.string().uuid(),
});

export const zodAdminOrderUpdateStatusBody = zod.object({
  newStatus: zod.enum([
    "PENDING",
    "ACCEPTED",
    "PREPARING",
    "DELIVERING",
    "DELIVERED",
    "AWAITING_MATERIAL_RETURN",
    "COMPLETED",
    "REJECTED",
    "CANCELLED",
  ]),
  reason: zod.string().min(1).optional(),
  contactMode: zod.enum(["PHONE", "EMAIL"]).optional(),
});

export const zodAdminOrderUpdateStatusResponse = zod.object({
  id: zod.string().uuid(),
  status: zod.enum([
    "PENDING",
    "ACCEPTED",
    "PREPARING",
    "DELIVERING",
    "DELIVERED",
    "AWAITING_MATERIAL_RETURN",
    "COMPLETED",
    "REJECTED",
    "CANCELLED",
  ]),
  userId: zod.string().uuid().nullable(),
  guestEmail: zod.string().nullable(),
  guestName: zod.string().nullable(),
  guestPhone: zod.string().nullable(),
  deliveryAddress: zod.string().nullable(),
  deliveryCity: zod.string().nullable(),
  deliveryPostalCode: zod.string().nullable(),
  deliveryZoneId: zod.string().uuid().nullable(),
  deliveryDate: zod.string().nullable(),
  deliveryFee: zod.number(),
  totalPrice: zod.number(),
  notes: zod.string().nullable(),
  createdAt: zod.string().datetime({}),
  updatedAt: zod.string().datetime({}),
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      menuId: zod.string().uuid(),
      menuName: zod.string().nullable(),
      quantity: zod.number(),
      unitPrice: zod.number(),
      lineTotal: zod.number(),
      discountApplied: zod.boolean(),
    }),
  ),
  rejectionReason: zod.string().nullable(),
  rejectedBy: zod.string().uuid().nullable(),
  rejectedAt: zod.string().datetime({}).nullable(),
  materialReturnDeadline: zod.string().datetime({}).nullable(),
  materialPenaltyApplied: zod.boolean(),
  penaltyAmount: zod.number().nullable(),
  history: zod.array(
    zod.object({
      id: zod.string().uuid(),
      oldStatus: zod
        .enum([
          "PENDING",
          "ACCEPTED",
          "PREPARING",
          "DELIVERING",
          "DELIVERED",
          "AWAITING_MATERIAL_RETURN",
          "COMPLETED",
          "REJECTED",
          "CANCELLED",
        ])
        .nullable(),
      newStatus: zod.enum([
        "PENDING",
        "ACCEPTED",
        "PREPARING",
        "DELIVERING",
        "DELIVERED",
        "AWAITING_MATERIAL_RETURN",
        "COMPLETED",
        "REJECTED",
        "CANCELLED",
      ]),
      changedBy: zod.string().uuid().nullable(),
      reason: zod.string().nullable(),
      contactMode: zod.string().nullable(),
      createdAt: zod.string().datetime({}),
    }),
  ),
});

/**
 * @summary Review - List all reviews for moderation (staff)
 */
export const zodAdminReviewGetAllQueryLimitMax = 100;

export const zodAdminReviewGetAllQueryOffsetMin = 0;

export const zodAdminReviewGetAllQueryParams = zod.object({
  isApproved: zod.enum(["true", "false"]).optional(),
  limit: zod.number().min(1).max(zodAdminReviewGetAllQueryLimitMax).optional(),
  offset: zod.number().min(zodAdminReviewGetAllQueryOffsetMin).nullish(),
  sortBy: zod.enum(["createdAt", "updatedAt", "rating"]).optional(),
  sortOrder: zod.enum(["ASC", "DESC"]).optional(),
});

export const zodAdminReviewGetAllResponseItemsItemRatingMax = 5;

export const zodAdminReviewGetAllResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      userId: zod.string().uuid(),
      orderId: zod.string().uuid(),
      rating: zod
        .number()
        .min(1)
        .max(zodAdminReviewGetAllResponseItemsItemRatingMax),
      comment: zod.string().nullable(),
      isApproved: zod.boolean(),
      approvedBy: zod.string().uuid().nullable(),
      createdAt: zod.string().datetime({}),
      updatedAt: zod.string().datetime({}),
    }),
  ),
  totalCount: zod.number(),
});

/**
 * @summary Review - Approve a review (staff)
 */
export const zodAdminReviewApproveParams = zod.object({
  id: zod.string().uuid(),
});

export const zodAdminReviewApproveResponseRatingMax = 5;

export const zodAdminReviewApproveResponse = zod.object({
  id: zod.string().uuid(),
  userId: zod.string().uuid(),
  orderId: zod.string().uuid(),
  rating: zod.number().min(1).max(zodAdminReviewApproveResponseRatingMax),
  comment: zod.string().nullable(),
  isApproved: zod.boolean(),
  approvedBy: zod.string().uuid().nullable(),
  createdAt: zod.string().datetime({}),
  updatedAt: zod.string().datetime({}),
});

/**
 * @summary Review - Delete a review (staff)
 */
export const zodAdminReviewDeleteParams = zod.object({
  id: zod.string().uuid(),
});

export const zodAdminReviewDeleteResponse = zod.object({
  message: zod.string(),
  code: zod.string(),
});

/**
 * @summary Contact - List contact messages (staff)
 */
export const zodAdminContactMessageGetAllQueryLimitMax = 100;

export const zodAdminContactMessageGetAllQueryOffsetMin = 0;

export const zodAdminContactMessageGetAllQueryParams = zod.object({
  isRead: zod.enum(["true", "false"]).optional(),
  limit: zod
    .number()
    .min(1)
    .max(zodAdminContactMessageGetAllQueryLimitMax)
    .optional(),
  offset: zod
    .number()
    .min(zodAdminContactMessageGetAllQueryOffsetMin)
    .nullish(),
  sortOrder: zod.enum(["ASC", "DESC"]).optional(),
});

export const zodAdminContactMessageGetAllResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      name: zod.string(),
      email: zod.string(),
      phone: zod.string().nullable(),
      subject: zod.string().nullable(),
      message: zod.string(),
      isRead: zod.boolean(),
      createdAt: zod.string().datetime({}),
    }),
  ),
  totalCount: zod.number(),
});

/**
 * @summary Contact - Mark a message as read (staff)
 */
export const zodAdminContactMessageMarkReadParams = zod.object({
  id: zod.string().uuid(),
});

export const zodAdminContactMessageMarkReadResponse = zod.object({
  id: zod.string().uuid(),
  name: zod.string(),
  email: zod.string(),
  phone: zod.string().nullable(),
  subject: zod.string().nullable(),
  message: zod.string(),
  isRead: zod.boolean(),
  createdAt: zod.string().datetime({}),
});

/**
 * @summary Contact - Delete a message (staff)
 */
export const zodAdminContactMessageDeleteParams = zod.object({
  id: zod.string().uuid(),
});

export const zodAdminContactMessageDeleteResponse = zod.object({
  message: zod.string(),
  code: zod.string(),
});

/**
 * @summary CMS - List page content (staff)
 */
export const zodAdminPageContentGetAllQueryPageMax = 100;

export const zodAdminPageContentGetAllQueryParams = zod.object({
  page: zod
    .string()
    .min(1)
    .max(zodAdminPageContentGetAllQueryPageMax)
    .optional(),
});

export const zodAdminPageContentGetAllResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      page: zod.string(),
      section: zod.string(),
      content: zod.record(zod.string(), zod.unknown()),
      updatedAt: zod.string().datetime({}),
      updatedBy: zod.string().uuid().nullable(),
    }),
  ),
});

/**
 * @summary CMS - Upsert a page content section (staff)
 */
export const zodAdminPageContentUpsertBodyPageMax = 100;

export const zodAdminPageContentUpsertBodySectionMax = 100;

export const zodAdminPageContentUpsertBody = zod.object({
  page: zod.string().min(1).max(zodAdminPageContentUpsertBodyPageMax),
  section: zod.string().min(1).max(zodAdminPageContentUpsertBodySectionMax),
  content: zod.record(zod.string(), zod.unknown()),
});

export const zodAdminPageContentUpsertResponse = zod.object({
  id: zod.string().uuid(),
  page: zod.string(),
  section: zod.string(),
  content: zod.record(zod.string(), zod.unknown()),
  updatedAt: zod.string().datetime({}),
  updatedBy: zod.string().uuid().nullable(),
});

/**
 * @summary CMS - List operating hours (staff)
 */
export const zodAdminOperatingHoursGetAllResponseItemsItemDayOfWeekMin = 0;
export const zodAdminOperatingHoursGetAllResponseItemsItemDayOfWeekMax = 6;

export const zodAdminOperatingHoursGetAllResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      dayOfWeek: zod
        .number()
        .min(zodAdminOperatingHoursGetAllResponseItemsItemDayOfWeekMin)
        .max(zodAdminOperatingHoursGetAllResponseItemsItemDayOfWeekMax),
      openTime: zod.string().nullable(),
      closeTime: zod.string().nullable(),
      isClosed: zod.boolean(),
    }),
  ),
});

/**
 * @summary CMS - Upsert operating hours (staff)
 */
export const zodAdminOperatingHoursUpsertBodyDaysItemDayOfWeekMin = 0;
export const zodAdminOperatingHoursUpsertBodyDaysItemDayOfWeekMax = 6;

export const zodAdminOperatingHoursUpsertBodyDaysItemOpenTimeRegExp =
  new RegExp("^([01]\\d|2[0-3]):[0-5]\\d$");
export const zodAdminOperatingHoursUpsertBodyDaysItemCloseTimeRegExp =
  new RegExp("^([01]\\d|2[0-3]):[0-5]\\d$");

export const zodAdminOperatingHoursUpsertBody = zod.object({
  days: zod
    .array(
      zod.object({
        dayOfWeek: zod
          .number()
          .min(zodAdminOperatingHoursUpsertBodyDaysItemDayOfWeekMin)
          .max(zodAdminOperatingHoursUpsertBodyDaysItemDayOfWeekMax),
        openTime: zod
          .string()
          .regex(zodAdminOperatingHoursUpsertBodyDaysItemOpenTimeRegExp)
          .nullish(),
        closeTime: zod
          .string()
          .regex(zodAdminOperatingHoursUpsertBodyDaysItemCloseTimeRegExp)
          .nullish(),
        isClosed: zod.boolean().optional(),
      }),
    )
    .min(1),
});

export const zodAdminOperatingHoursUpsertResponseItemsItemDayOfWeekMin = 0;
export const zodAdminOperatingHoursUpsertResponseItemsItemDayOfWeekMax = 6;

export const zodAdminOperatingHoursUpsertResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      dayOfWeek: zod
        .number()
        .min(zodAdminOperatingHoursUpsertResponseItemsItemDayOfWeekMin)
        .max(zodAdminOperatingHoursUpsertResponseItemsItemDayOfWeekMax),
      openTime: zod.string().nullable(),
      closeTime: zod.string().nullable(),
      isClosed: zod.boolean(),
    }),
  ),
});
