/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminContactMessageDelete401ErrorsItem } from "./adminContactMessageDelete401ErrorsItem";

export type AdminContactMessageDelete401 = {
  message: string;
  code: string;
  errors?: AdminContactMessageDelete401ErrorsItem[];
};
