/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminEmployeeGetAllSortBy =
  (typeof AdminEmployeeGetAllSortBy)[keyof typeof AdminEmployeeGetAllSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminEmployeeGetAllSortBy = {
  email: "email",
  lastName: "lastName",
  firstName: "firstName",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
} as const;
