/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminContactMessageMarkRead200Phone } from "./adminContactMessageMarkRead200Phone";
import type { AdminContactMessageMarkRead200Subject } from "./adminContactMessageMarkRead200Subject";

export type AdminContactMessageMarkRead200 = {
  id: string;
  name: string;
  email: string;
  phone: AdminContactMessageMarkRead200Phone;
  subject: AdminContactMessageMarkRead200Subject;
  message: string;
  isRead: boolean;
  createdAt: string;
};
