/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderUpdateStatus200ItemsItemMenuName } from "./adminOrderUpdateStatus200ItemsItemMenuName";

export type AdminOrderUpdateStatus200ItemsItem = {
  id: string;
  menuId: string;
  menuName: AdminOrderUpdateStatus200ItemsItemMenuName;
  quantity: number;
  unitPrice: number;
  lineTotal: number;
  discountApplied: boolean;
};
