/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminReviewApprove200Comment } from "./adminReviewApprove200Comment";
import type { AdminReviewApprove200ApprovedBy } from "./adminReviewApprove200ApprovedBy";

export type AdminReviewApprove200 = {
  id: string;
  userId: string;
  orderId: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  comment: AdminReviewApprove200Comment;
  isApproved: boolean;
  approvedBy: AdminReviewApprove200ApprovedBy;
  createdAt: string;
  updatedAt: string;
};
