/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminContactMessageGetAll200ItemsItemPhone } from "./adminContactMessageGetAll200ItemsItemPhone";
import type { AdminContactMessageGetAll200ItemsItemSubject } from "./adminContactMessageGetAll200ItemsItemSubject";

export type AdminContactMessageGetAll200ItemsItem = {
  id: string;
  name: string;
  email: string;
  phone: AdminContactMessageGetAll200ItemsItemPhone;
  subject: AdminContactMessageGetAll200ItemsItemSubject;
  message: string;
  isRead: boolean;
  createdAt: string;
};
