/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDietaryRegimeGetAll403ErrorsItem } from "./adminDietaryRegimeGetAll403ErrorsItem";

export type AdminDietaryRegimeGetAll403 = {
  message: string;
  code: string;
  errors?: AdminDietaryRegimeGetAll403ErrorsItem[];
};
