/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminReviewGetAll401ErrorsItem } from "./adminReviewGetAll401ErrorsItem";

export type AdminReviewGetAll401 = {
  message: string;
  code: string;
  errors?: AdminReviewGetAll401ErrorsItem[];
};
