/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuGetAll200ItemsItemDescription } from "./adminMenuGetAll200ItemsItemDescription";
import type { AdminMenuGetAll200ItemsItemTheme } from "./adminMenuGetAll200ItemsItemTheme";
import type { AdminMenuGetAll200ItemsItemMaxPersons } from "./adminMenuGetAll200ItemsItemMaxPersons";
import type { AdminMenuGetAll200ItemsItemStock } from "./adminMenuGetAll200ItemsItemStock";
import type { AdminMenuGetAll200ItemsItemImageUrl } from "./adminMenuGetAll200ItemsItemImageUrl";

export type AdminMenuGetAll200ItemsItem = {
  id: string;
  name: string;
  description: AdminMenuGetAll200ItemsItemDescription;
  theme: AdminMenuGetAll200ItemsItemTheme;
  price: number;
  minPersons: number;
  maxPersons: AdminMenuGetAll200ItemsItemMaxPersons;
  stock: AdminMenuGetAll200ItemsItemStock;
  isAvailable: boolean;
  imageUrl: AdminMenuGetAll200ItemsItemImageUrl;
};
