/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminDeliveryZoneGetAllSortOrder =
  (typeof AdminDeliveryZoneGetAllSortOrder)[keyof typeof AdminDeliveryZoneGetAllSortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminDeliveryZoneGetAllSortOrder = {
  ASC: "ASC",
  DESC: "DESC",
} as const;
