/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDishDelete401ErrorsItem } from "./adminDishDelete401ErrorsItem";

export type AdminDishDelete401 = {
  message: string;
  code: string;
  errors?: AdminDishDelete401ErrorsItem[];
};
