/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDishCreate201Description } from "./adminDishCreate201Description";
import type { AdminDishCreate201Category } from "./adminDishCreate201Category";
import type { AdminDishCreate201Price } from "./adminDishCreate201Price";
import type { AdminDishCreate201ImageUrl } from "./adminDishCreate201ImageUrl";
import type { AdminDishCreate201AllergensItem } from "./adminDishCreate201AllergensItem";

export type AdminDishCreate201 = {
  id: string;
  name: string;
  description: AdminDishCreate201Description;
  category: AdminDishCreate201Category;
  price: AdminDishCreate201Price;
  imageUrl: AdminDishCreate201ImageUrl;
  isAvailable: boolean;
  createdAt: string;
  updatedAt: string;
  allergens: AdminDishCreate201AllergensItem[];
};
