/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDeliveryZoneGetAll200ItemsItem } from "./adminDeliveryZoneGetAll200ItemsItem";

export type AdminDeliveryZoneGetAll200 = {
  items: AdminDeliveryZoneGetAll200ItemsItem[];
  totalCount: number;
};
