/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDishGetOne403ErrorsItem } from "./adminDishGetOne403ErrorsItem";

export type AdminDishGetOne403 = {
  message: string;
  code: string;
  errors?: AdminDishGetOne403ErrorsItem[];
};
