/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOperatingHoursUpsertBodyDaysItemOpenTime } from "./adminOperatingHoursUpsertBodyDaysItemOpenTime";
import type { AdminOperatingHoursUpsertBodyDaysItemCloseTime } from "./adminOperatingHoursUpsertBodyDaysItemCloseTime";

export type AdminOperatingHoursUpsertBodyDaysItem = {
  /**
   * @minimum 0
   * @maximum 6
   */
  dayOfWeek: number;
  /** @pattern ^([01]\d|2[0-3]):[0-5]\d$ */
  openTime?: AdminOperatingHoursUpsertBodyDaysItemOpenTime;
  /** @pattern ^([01]\d|2[0-3]):[0-5]\d$ */
  closeTime?: AdminOperatingHoursUpsertBodyDaysItemCloseTime;
  isClosed?: boolean;
};
