/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @pattern ^([01]\d|2[0-3]):[0-5]\d$
 */
export type AdminOperatingHoursUpsertBodyDaysItemCloseTime = string | null;
