/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminAllergenUpdateBodyIcon } from "./adminAllergenUpdateBodyIcon";

export type AdminAllergenUpdateBody = {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name?: string;
  /** @maxLength 255 */
  icon?: AdminAllergenUpdateBodyIcon;
};
