/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminAllergenUpdate401ErrorsItem } from "./adminAllergenUpdate401ErrorsItem";

export type AdminAllergenUpdate401 = {
  message: string;
  code: string;
  errors?: AdminAllergenUpdate401ErrorsItem[];
};
