/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDeliveryZoneUpdate400ErrorsItem } from "./adminDeliveryZoneUpdate400ErrorsItem";

export type AdminDeliveryZoneUpdate400 = {
  message: string;
  code: string;
  errors?: AdminDeliveryZoneUpdate400ErrorsItem[];
};
