/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDeliveryZoneDelete401ErrorsItem } from "./adminDeliveryZoneDelete401ErrorsItem";

export type AdminDeliveryZoneDelete401 = {
  message: string;
  code: string;
  errors?: AdminDeliveryZoneDelete401ErrorsItem[];
};
