/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDishDelete404ErrorsItem } from "./adminDishDelete404ErrorsItem";

export type AdminDishDelete404 = {
  message: string;
  code: string;
  errors?: AdminDishDelete404ErrorsItem[];
};
