/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminReviewDelete404ErrorsItem } from "./adminReviewDelete404ErrorsItem";

export type AdminReviewDelete404 = {
  message: string;
  code: string;
  errors?: AdminReviewDelete404ErrorsItem[];
};
