/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminDishCreate201Category =
  (typeof AdminDishCreate201Category)[keyof typeof AdminDishCreate201Category];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminDishCreate201Category = {
  entree: "entree",
  plat: "plat",
  dessert: "dessert",
} as const;
