/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDietaryRegimeUpdate200Description } from "./adminDietaryRegimeUpdate200Description";

export type AdminDietaryRegimeUpdate200 = {
  id: string;
  name: string;
  description: AdminDietaryRegimeUpdate200Description;
  createdAt: string;
};
