/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderUpdateStatus200Status } from "./adminOrderUpdateStatus200Status";
import type { AdminOrderUpdateStatus200UserId } from "./adminOrderUpdateStatus200UserId";
import type { AdminOrderUpdateStatus200GuestEmail } from "./adminOrderUpdateStatus200GuestEmail";
import type { AdminOrderUpdateStatus200GuestName } from "./adminOrderUpdateStatus200GuestName";
import type { AdminOrderUpdateStatus200GuestPhone } from "./adminOrderUpdateStatus200GuestPhone";
import type { AdminOrderUpdateStatus200DeliveryAddress } from "./adminOrderUpdateStatus200DeliveryAddress";
import type { AdminOrderUpdateStatus200DeliveryCity } from "./adminOrderUpdateStatus200DeliveryCity";
import type { AdminOrderUpdateStatus200DeliveryPostalCode } from "./adminOrderUpdateStatus200DeliveryPostalCode";
import type { AdminOrderUpdateStatus200DeliveryZoneId } from "./adminOrderUpdateStatus200DeliveryZoneId";
import type { AdminOrderUpdateStatus200DeliveryDate } from "./adminOrderUpdateStatus200DeliveryDate";
import type { AdminOrderUpdateStatus200Notes } from "./adminOrderUpdateStatus200Notes";
import type { AdminOrderUpdateStatus200ItemsItem } from "./adminOrderUpdateStatus200ItemsItem";
import type { AdminOrderUpdateStatus200RejectionReason } from "./adminOrderUpdateStatus200RejectionReason";
import type { AdminOrderUpdateStatus200RejectedBy } from "./adminOrderUpdateStatus200RejectedBy";
import type { AdminOrderUpdateStatus200RejectedAt } from "./adminOrderUpdateStatus200RejectedAt";
import type { AdminOrderUpdateStatus200MaterialReturnDeadline } from "./adminOrderUpdateStatus200MaterialReturnDeadline";
import type { AdminOrderUpdateStatus200PenaltyAmount } from "./adminOrderUpdateStatus200PenaltyAmount";
import type { AdminOrderUpdateStatus200HistoryItem } from "./adminOrderUpdateStatus200HistoryItem";

export type AdminOrderUpdateStatus200 = {
  id: string;
  status: AdminOrderUpdateStatus200Status;
  userId: AdminOrderUpdateStatus200UserId;
  guestEmail: AdminOrderUpdateStatus200GuestEmail;
  guestName: AdminOrderUpdateStatus200GuestName;
  guestPhone: AdminOrderUpdateStatus200GuestPhone;
  deliveryAddress: AdminOrderUpdateStatus200DeliveryAddress;
  deliveryCity: AdminOrderUpdateStatus200DeliveryCity;
  deliveryPostalCode: AdminOrderUpdateStatus200DeliveryPostalCode;
  deliveryZoneId: AdminOrderUpdateStatus200DeliveryZoneId;
  deliveryDate: AdminOrderUpdateStatus200DeliveryDate;
  deliveryFee: number;
  totalPrice: number;
  notes: AdminOrderUpdateStatus200Notes;
  createdAt: string;
  updatedAt: string;
  items: AdminOrderUpdateStatus200ItemsItem[];
  rejectionReason: AdminOrderUpdateStatus200RejectionReason;
  rejectedBy: AdminOrderUpdateStatus200RejectedBy;
  rejectedAt: AdminOrderUpdateStatus200RejectedAt;
  materialReturnDeadline: AdminOrderUpdateStatus200MaterialReturnDeadline;
  materialPenaltyApplied: boolean;
  penaltyAmount: AdminOrderUpdateStatus200PenaltyAmount;
  history: AdminOrderUpdateStatus200HistoryItem[];
};
