/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDishDelete403ErrorsItem } from "./adminDishDelete403ErrorsItem";

export type AdminDishDelete403 = {
  message: string;
  code: string;
  errors?: AdminDishDelete403ErrorsItem[];
};
