/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminAllergenDelete403ErrorsItem } from "./adminAllergenDelete403ErrorsItem";

export type AdminAllergenDelete403 = {
  message: string;
  code: string;
  errors?: AdminAllergenDelete403ErrorsItem[];
};
