/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDeliveryZoneUpdate401ErrorsItem } from "./adminDeliveryZoneUpdate401ErrorsItem";

export type AdminDeliveryZoneUpdate401 = {
  message: string;
  code: string;
  errors?: AdminDeliveryZoneUpdate401ErrorsItem[];
};
