/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderUpdateStatusBodyNewStatus } from "./adminOrderUpdateStatusBodyNewStatus";
import type { AdminOrderUpdateStatusBodyContactMode } from "./adminOrderUpdateStatusBodyContactMode";

export type AdminOrderUpdateStatusBody = {
  newStatus: AdminOrderUpdateStatusBodyNewStatus;
  /** @minLength 1 */
  reason?: string;
  contactMode?: AdminOrderUpdateStatusBodyContactMode;
};
