/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderGetAll200ItemsItemStatus } from "./adminOrderGetAll200ItemsItemStatus";
import type { AdminOrderGetAll200ItemsItemDeliveryDate } from "./adminOrderGetAll200ItemsItemDeliveryDate";
import type { AdminOrderGetAll200ItemsItemUserId } from "./adminOrderGetAll200ItemsItemUserId";
import type { AdminOrderGetAll200ItemsItemGuestEmail } from "./adminOrderGetAll200ItemsItemGuestEmail";
import type { AdminOrderGetAll200ItemsItemGuestName } from "./adminOrderGetAll200ItemsItemGuestName";
import type { AdminOrderGetAll200ItemsItemDeliveryCity } from "./adminOrderGetAll200ItemsItemDeliveryCity";

export type AdminOrderGetAll200ItemsItem = {
  id: string;
  status: AdminOrderGetAll200ItemsItemStatus;
  deliveryDate: AdminOrderGetAll200ItemsItemDeliveryDate;
  deliveryFee: number;
  totalPrice: number;
  itemCount: number;
  createdAt: string;
  userId: AdminOrderGetAll200ItemsItemUserId;
  guestEmail: AdminOrderGetAll200ItemsItemGuestEmail;
  guestName: AdminOrderGetAll200ItemsItemGuestName;
  deliveryCity: AdminOrderGetAll200ItemsItemDeliveryCity;
};
