/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOperatingHoursUpsert403ErrorsItem } from "./adminOperatingHoursUpsert403ErrorsItem";

export type AdminOperatingHoursUpsert403 = {
  message: string;
  code: string;
  errors?: AdminOperatingHoursUpsert403ErrorsItem[];
};
