/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderUpdateStatus400ErrorsItem } from "./adminOrderUpdateStatus400ErrorsItem";

export type AdminOrderUpdateStatus400 = {
  message: string;
  code: string;
  errors?: AdminOrderUpdateStatus400ErrorsItem[];
};
