/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminContactMessageGetAll403ErrorsItem } from "./adminContactMessageGetAll403ErrorsItem";

export type AdminContactMessageGetAll403 = {
  message: string;
  code: string;
  errors?: AdminContactMessageGetAll403ErrorsItem[];
};
