/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuUpdate401ErrorsItem } from "./adminMenuUpdate401ErrorsItem";

export type AdminMenuUpdate401 = {
  message: string;
  code: string;
  errors?: AdminMenuUpdate401ErrorsItem[];
};
