/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDishGetAll200ItemsItemDescription } from "./adminDishGetAll200ItemsItemDescription";
import type { AdminDishGetAll200ItemsItemCategory } from "./adminDishGetAll200ItemsItemCategory";
import type { AdminDishGetAll200ItemsItemPrice } from "./adminDishGetAll200ItemsItemPrice";
import type { AdminDishGetAll200ItemsItemImageUrl } from "./adminDishGetAll200ItemsItemImageUrl";

export type AdminDishGetAll200ItemsItem = {
  id: string;
  name: string;
  description: AdminDishGetAll200ItemsItemDescription;
  category: AdminDishGetAll200ItemsItemCategory;
  price: AdminDishGetAll200ItemsItemPrice;
  imageUrl: AdminDishGetAll200ItemsItemImageUrl;
  isAvailable: boolean;
  createdAt: string;
  updatedAt: string;
};
