/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPageContentUpsert200Content } from "./adminPageContentUpsert200Content";
import type { AdminPageContentUpsert200UpdatedBy } from "./adminPageContentUpsert200UpdatedBy";

export type AdminPageContentUpsert200 = {
  id: string;
  page: string;
  section: string;
  content: AdminPageContentUpsert200Content;
  updatedAt: string;
  updatedBy: AdminPageContentUpsert200UpdatedBy;
};
