/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminAllergenUpdate403ErrorsItem } from "./adminAllergenUpdate403ErrorsItem";

export type AdminAllergenUpdate403 = {
  message: string;
  code: string;
  errors?: AdminAllergenUpdate403ErrorsItem[];
};
