/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPageContentGetAll401ErrorsItem } from "./adminPageContentGetAll401ErrorsItem";

export type AdminPageContentGetAll401 = {
  message: string;
  code: string;
  errors?: AdminPageContentGetAll401ErrorsItem[];
};
