/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminAllergenUpdate200Icon } from "./adminAllergenUpdate200Icon";

export type AdminAllergenUpdate200 = {
  id: string;
  name: string;
  icon: AdminAllergenUpdate200Icon;
  createdAt: string;
};
