/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDietaryRegimeDelete401ErrorsItem } from "./adminDietaryRegimeDelete401ErrorsItem";

export type AdminDietaryRegimeDelete401 = {
  message: string;
  code: string;
  errors?: AdminDietaryRegimeDelete401ErrorsItem[];
};
