/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminContactMessageMarkRead404ErrorsItem } from "./adminContactMessageMarkRead404ErrorsItem";

export type AdminContactMessageMarkRead404 = {
  message: string;
  code: string;
  errors?: AdminContactMessageMarkRead404ErrorsItem[];
};
