/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminAllergenGetAll403ErrorsItem } from "./adminAllergenGetAll403ErrorsItem";

export type AdminAllergenGetAll403 = {
  message: string;
  code: string;
  errors?: AdminAllergenGetAll403ErrorsItem[];
};
