/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuGetOne200Description } from "./adminMenuGetOne200Description";
import type { AdminMenuGetOne200Theme } from "./adminMenuGetOne200Theme";
import type { AdminMenuGetOne200MaxPersons } from "./adminMenuGetOne200MaxPersons";
import type { AdminMenuGetOne200Stock } from "./adminMenuGetOne200Stock";
import type { AdminMenuGetOne200Conditions } from "./adminMenuGetOne200Conditions";
import type { AdminMenuGetOne200ImageUrl } from "./adminMenuGetOne200ImageUrl";
import type { AdminMenuGetOne200DishesItem } from "./adminMenuGetOne200DishesItem";
import type { AdminMenuGetOne200DietaryRegimesItem } from "./adminMenuGetOne200DietaryRegimesItem";

export type AdminMenuGetOne200 = {
  id: string;
  name: string;
  description: AdminMenuGetOne200Description;
  theme: AdminMenuGetOne200Theme;
  price: number;
  minPersons: number;
  maxPersons: AdminMenuGetOne200MaxPersons;
  stock: AdminMenuGetOne200Stock;
  conditions: AdminMenuGetOne200Conditions;
  imageUrl: AdminMenuGetOne200ImageUrl;
  isAvailable: boolean;
  createdAt: string;
  updatedAt: string;
  dishes: AdminMenuGetOne200DishesItem[];
  dietaryRegimes: AdminMenuGetOne200DietaryRegimesItem[];
};
