/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDietaryRegimeGetAll200ItemsItem } from "./adminDietaryRegimeGetAll200ItemsItem";

export type AdminDietaryRegimeGetAll200 = {
  items: AdminDietaryRegimeGetAll200ItemsItem[];
  totalCount: number;
};
