/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminContactMessageGetAllSortOrder =
  (typeof AdminContactMessageGetAllSortOrder)[keyof typeof AdminContactMessageGetAllSortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminContactMessageGetAllSortOrder = {
  ASC: "ASC",
  DESC: "DESC",
} as const;
