/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderGetOne200Status } from "./adminOrderGetOne200Status";
import type { AdminOrderGetOne200UserId } from "./adminOrderGetOne200UserId";
import type { AdminOrderGetOne200GuestEmail } from "./adminOrderGetOne200GuestEmail";
import type { AdminOrderGetOne200GuestName } from "./adminOrderGetOne200GuestName";
import type { AdminOrderGetOne200GuestPhone } from "./adminOrderGetOne200GuestPhone";
import type { AdminOrderGetOne200DeliveryAddress } from "./adminOrderGetOne200DeliveryAddress";
import type { AdminOrderGetOne200DeliveryCity } from "./adminOrderGetOne200DeliveryCity";
import type { AdminOrderGetOne200DeliveryPostalCode } from "./adminOrderGetOne200DeliveryPostalCode";
import type { AdminOrderGetOne200DeliveryZoneId } from "./adminOrderGetOne200DeliveryZoneId";
import type { AdminOrderGetOne200DeliveryDate } from "./adminOrderGetOne200DeliveryDate";
import type { AdminOrderGetOne200Notes } from "./adminOrderGetOne200Notes";
import type { AdminOrderGetOne200ItemsItem } from "./adminOrderGetOne200ItemsItem";
import type { AdminOrderGetOne200RejectionReason } from "./adminOrderGetOne200RejectionReason";
import type { AdminOrderGetOne200RejectedBy } from "./adminOrderGetOne200RejectedBy";
import type { AdminOrderGetOne200RejectedAt } from "./adminOrderGetOne200RejectedAt";
import type { AdminOrderGetOne200MaterialReturnDeadline } from "./adminOrderGetOne200MaterialReturnDeadline";
import type { AdminOrderGetOne200PenaltyAmount } from "./adminOrderGetOne200PenaltyAmount";
import type { AdminOrderGetOne200HistoryItem } from "./adminOrderGetOne200HistoryItem";

export type AdminOrderGetOne200 = {
  id: string;
  status: AdminOrderGetOne200Status;
  userId: AdminOrderGetOne200UserId;
  guestEmail: AdminOrderGetOne200GuestEmail;
  guestName: AdminOrderGetOne200GuestName;
  guestPhone: AdminOrderGetOne200GuestPhone;
  deliveryAddress: AdminOrderGetOne200DeliveryAddress;
  deliveryCity: AdminOrderGetOne200DeliveryCity;
  deliveryPostalCode: AdminOrderGetOne200DeliveryPostalCode;
  deliveryZoneId: AdminOrderGetOne200DeliveryZoneId;
  deliveryDate: AdminOrderGetOne200DeliveryDate;
  deliveryFee: number;
  totalPrice: number;
  notes: AdminOrderGetOne200Notes;
  createdAt: string;
  updatedAt: string;
  items: AdminOrderGetOne200ItemsItem[];
  rejectionReason: AdminOrderGetOne200RejectionReason;
  rejectedBy: AdminOrderGetOne200RejectedBy;
  rejectedAt: AdminOrderGetOne200RejectedAt;
  materialReturnDeadline: AdminOrderGetOne200MaterialReturnDeadline;
  materialPenaltyApplied: boolean;
  penaltyAmount: AdminOrderGetOne200PenaltyAmount;
  history: AdminOrderGetOne200HistoryItem[];
};
