/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOperatingHoursUpsert200ItemsItem } from "./adminOperatingHoursUpsert200ItemsItem";

export type AdminOperatingHoursUpsert200 = {
  items: AdminOperatingHoursUpsert200ItemsItem[];
};
