/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminEmployeeDeactivate200Role =
  (typeof AdminEmployeeDeactivate200Role)[keyof typeof AdminEmployeeDeactivate200Role];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminEmployeeDeactivate200Role = {
  USER: "USER",
  EMPLOYEE: "EMPLOYEE",
  ADMIN: "ADMIN",
} as const;
