/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminEmployeeReactivate403ErrorsItem } from "./adminEmployeeReactivate403ErrorsItem";

export type AdminEmployeeReactivate403 = {
  message: string;
  code: string;
  errors?: AdminEmployeeReactivate403ErrorsItem[];
};
