/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminReviewGetAll200ItemsItemComment } from "./adminReviewGetAll200ItemsItemComment";
import type { AdminReviewGetAll200ItemsItemApprovedBy } from "./adminReviewGetAll200ItemsItemApprovedBy";

export type AdminReviewGetAll200ItemsItem = {
  id: string;
  userId: string;
  orderId: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  comment: AdminReviewGetAll200ItemsItemComment;
  isApproved: boolean;
  approvedBy: AdminReviewGetAll200ItemsItemApprovedBy;
  createdAt: string;
  updatedAt: string;
};
