/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDishGetAllCategory } from "./adminDishGetAllCategory";
import type { AdminDishGetAllIsAvailable } from "./adminDishGetAllIsAvailable";
import type { AdminDishGetAllSortBy } from "./adminDishGetAllSortBy";
import type { AdminDishGetAllSortOrder } from "./adminDishGetAllSortOrder";

export type AdminDishGetAllParams = {
  category?: AdminDishGetAllCategory;
  isAvailable?: AdminDishGetAllIsAvailable;
  search?: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset?: number | null;
  sortBy?: AdminDishGetAllSortBy;
  sortOrder?: AdminDishGetAllSortOrder;
};
