/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminMenuCreate201DishesItemCategory =
  (typeof AdminMenuCreate201DishesItemCategory)[keyof typeof AdminMenuCreate201DishesItemCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminMenuCreate201DishesItemCategory = {
  entree: "entree",
  plat: "plat",
  dessert: "dessert",
} as const;
