/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuCreate400ErrorsItem } from "./adminMenuCreate400ErrorsItem";

export type AdminMenuCreate400 = {
  message: string;
  code: string;
  errors?: AdminMenuCreate400ErrorsItem[];
};
