/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminEmployeeReactivate401ErrorsItem } from "./adminEmployeeReactivate401ErrorsItem";

export type AdminEmployeeReactivate401 = {
  message: string;
  code: string;
  errors?: AdminEmployeeReactivate401ErrorsItem[];
};
