/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDishUpdate401ErrorsItem } from "./adminDishUpdate401ErrorsItem";

export type AdminDishUpdate401 = {
  message: string;
  code: string;
  errors?: AdminDishUpdate401ErrorsItem[];
};
