/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDishGetAll200ItemsItem } from "./adminDishGetAll200ItemsItem";

export type AdminDishGetAll200 = {
  items: AdminDishGetAll200ItemsItem[];
  totalCount: number;
};
