/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderGetOne403ErrorsItem } from "./adminOrderGetOne403ErrorsItem";

export type AdminOrderGetOne403 = {
  message: string;
  code: string;
  errors?: AdminOrderGetOne403ErrorsItem[];
};
