/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminMenuGetOne200DishesItemCategory =
  (typeof AdminMenuGetOne200DishesItemCategory)[keyof typeof AdminMenuGetOne200DishesItemCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminMenuGetOne200DishesItemCategory = {
  entree: "entree",
  plat: "plat",
  dessert: "dessert",
} as const;
