/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDishGetAll401ErrorsItem } from "./adminDishGetAll401ErrorsItem";

export type AdminDishGetAll401 = {
  message: string;
  code: string;
  errors?: AdminDishGetAll401ErrorsItem[];
};
