/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPageContentGetAll200ItemsItemContent } from "./adminPageContentGetAll200ItemsItemContent";
import type { AdminPageContentGetAll200ItemsItemUpdatedBy } from "./adminPageContentGetAll200ItemsItemUpdatedBy";

export type AdminPageContentGetAll200ItemsItem = {
  id: string;
  page: string;
  section: string;
  content: AdminPageContentGetAll200ItemsItemContent;
  updatedAt: string;
  updatedBy: AdminPageContentGetAll200ItemsItemUpdatedBy;
};
