/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminDietaryRegimeGetAllSortOrder =
  (typeof AdminDietaryRegimeGetAllSortOrder)[keyof typeof AdminDietaryRegimeGetAllSortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminDietaryRegimeGetAllSortOrder = {
  ASC: "ASC",
  DESC: "DESC",
} as const;
