/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuUpdateBodyDescription } from "./adminMenuUpdateBodyDescription";
import type { AdminMenuUpdateBodyTheme } from "./adminMenuUpdateBodyTheme";
import type { AdminMenuUpdateBodyMaxPersons } from "./adminMenuUpdateBodyMaxPersons";
import type { AdminMenuUpdateBodyStock } from "./adminMenuUpdateBodyStock";
import type { AdminMenuUpdateBodyConditions } from "./adminMenuUpdateBodyConditions";
import type { AdminMenuUpdateBodyImageUrl } from "./adminMenuUpdateBodyImageUrl";

export type AdminMenuUpdateBody = {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name?: string;
  description?: AdminMenuUpdateBodyDescription;
  /** @maxLength 255 */
  theme?: AdminMenuUpdateBodyTheme;
  /** @minimum 0 */
  price?: number;
  /** @minimum 1 */
  minPersons?: number;
  /** @minimum 1 */
  maxPersons?: AdminMenuUpdateBodyMaxPersons;
  /** @minimum 0 */
  stock?: AdminMenuUpdateBodyStock;
  conditions?: AdminMenuUpdateBodyConditions;
  imageUrl?: AdminMenuUpdateBodyImageUrl;
  isAvailable?: boolean;
  dishIds?: string[];
  dietaryRegimeIds?: string[];
};
