/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminDeliveryZoneGetAllSortBy =
  (typeof AdminDeliveryZoneGetAllSortBy)[keyof typeof AdminDeliveryZoneGetAllSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminDeliveryZoneGetAllSortBy = {
  name: "name",
  city: "city",
  distanceKm: "distanceKm",
  createdAt: "createdAt",
} as const;
