/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDeliveryZoneCreate201PostalCode } from "./adminDeliveryZoneCreate201PostalCode";
import type { AdminDeliveryZoneCreate201City } from "./adminDeliveryZoneCreate201City";

export type AdminDeliveryZoneCreate201 = {
  id: string;
  name: string;
  postalCode: AdminDeliveryZoneCreate201PostalCode;
  city: AdminDeliveryZoneCreate201City;
  distanceKm: number;
  isActive: boolean;
  createdAt: string;
};
