/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOperatingHoursGetAll200ItemsItemOpenTime } from "./adminOperatingHoursGetAll200ItemsItemOpenTime";
import type { AdminOperatingHoursGetAll200ItemsItemCloseTime } from "./adminOperatingHoursGetAll200ItemsItemCloseTime";

export type AdminOperatingHoursGetAll200ItemsItem = {
  id: string;
  /**
   * @minimum 0
   * @maximum 6
   */
  dayOfWeek: number;
  openTime: AdminOperatingHoursGetAll200ItemsItemOpenTime;
  closeTime: AdminOperatingHoursGetAll200ItemsItemCloseTime;
  isClosed: boolean;
};
