/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDeliveryZoneCreateBodyPostalCode } from "./adminDeliveryZoneCreateBodyPostalCode";
import type { AdminDeliveryZoneCreateBodyCity } from "./adminDeliveryZoneCreateBodyCity";

export type AdminDeliveryZoneCreateBody = {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** @maxLength 20 */
  postalCode?: AdminDeliveryZoneCreateBodyPostalCode;
  /** @maxLength 255 */
  city?: AdminDeliveryZoneCreateBodyCity;
  /** @minimum 0 */
  distanceKm?: number;
  isActive?: boolean;
};
