/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuUpdate200DishesItemCategory } from "./adminMenuUpdate200DishesItemCategory";
import type { AdminMenuUpdate200DishesItemDescription } from "./adminMenuUpdate200DishesItemDescription";
import type { AdminMenuUpdate200DishesItemPrice } from "./adminMenuUpdate200DishesItemPrice";
import type { AdminMenuUpdate200DishesItemAllergensItem } from "./adminMenuUpdate200DishesItemAllergensItem";

export type AdminMenuUpdate200DishesItem = {
  id: string;
  name: string;
  category: AdminMenuUpdate200DishesItemCategory;
  description: AdminMenuUpdate200DishesItemDescription;
  price: AdminMenuUpdate200DishesItemPrice;
  allergens: AdminMenuUpdate200DishesItemAllergensItem[];
};
