/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminContactMessageDelete404ErrorsItem } from "./adminContactMessageDelete404ErrorsItem";

export type AdminContactMessageDelete404 = {
  message: string;
  code: string;
  errors?: AdminContactMessageDelete404ErrorsItem[];
};
