/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuGetOne404ErrorsItem } from "./adminMenuGetOne404ErrorsItem";

export type AdminMenuGetOne404 = {
  message: string;
  code: string;
  errors?: AdminMenuGetOne404ErrorsItem[];
};
