/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDietaryRegimeUpdate400ErrorsItem } from "./adminDietaryRegimeUpdate400ErrorsItem";

export type AdminDietaryRegimeUpdate400 = {
  message: string;
  code: string;
  errors?: AdminDietaryRegimeUpdate400ErrorsItem[];
};
