/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuUpdate400ErrorsItem } from "./adminMenuUpdate400ErrorsItem";

export type AdminMenuUpdate400 = {
  message: string;
  code: string;
  errors?: AdminMenuUpdate400ErrorsItem[];
};
