/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminReviewApprove404ErrorsItem } from "./adminReviewApprove404ErrorsItem";

export type AdminReviewApprove404 = {
  message: string;
  code: string;
  errors?: AdminReviewApprove404ErrorsItem[];
};
