/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDietaryRegimeGetAllSortBy } from "./adminDietaryRegimeGetAllSortBy";
import type { AdminDietaryRegimeGetAllSortOrder } from "./adminDietaryRegimeGetAllSortOrder";

export type AdminDietaryRegimeGetAllParams = {
  search?: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset?: number | null;
  sortBy?: AdminDietaryRegimeGetAllSortBy;
  sortOrder?: AdminDietaryRegimeGetAllSortOrder;
};
