/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDishUpdate403ErrorsItem } from "./adminDishUpdate403ErrorsItem";

export type AdminDishUpdate403 = {
  message: string;
  code: string;
  errors?: AdminDishUpdate403ErrorsItem[];
};
