/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminStatsRevenueByMenu401ErrorsItem } from "./adminStatsRevenueByMenu401ErrorsItem";

export type AdminStatsRevenueByMenu401 = {
  message: string;
  code: string;
  errors?: AdminStatsRevenueByMenu401ErrorsItem[];
};
