/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOperatingHoursGetAll403ErrorsItem } from "./adminOperatingHoursGetAll403ErrorsItem";

export type AdminOperatingHoursGetAll403 = {
  message: string;
  code: string;
  errors?: AdminOperatingHoursGetAll403ErrorsItem[];
};
