/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPageContentGetAll403ErrorsItem } from "./adminPageContentGetAll403ErrorsItem";

export type AdminPageContentGetAll403 = {
  message: string;
  code: string;
  errors?: AdminPageContentGetAll403ErrorsItem[];
};
