/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminContactMessageGetAll401ErrorsItem } from "./adminContactMessageGetAll401ErrorsItem";

export type AdminContactMessageGetAll401 = {
  message: string;
  code: string;
  errors?: AdminContactMessageGetAll401ErrorsItem[];
};
