/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderGetAll401ErrorsItem } from "./adminOrderGetAll401ErrorsItem";

export type AdminOrderGetAll401 = {
  message: string;
  code: string;
  errors?: AdminOrderGetAll401ErrorsItem[];
};
