/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDeliveryZoneDelete403ErrorsItem } from "./adminDeliveryZoneDelete403ErrorsItem";

export type AdminDeliveryZoneDelete403 = {
  message: string;
  code: string;
  errors?: AdminDeliveryZoneDelete403ErrorsItem[];
};
