/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminEmployeeCreate409ErrorsItem } from "./adminEmployeeCreate409ErrorsItem";

export type AdminEmployeeCreate409 = {
  message: string;
  code: string;
  errors?: AdminEmployeeCreate409ErrorsItem[];
};
