/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderUpdateStatus403ErrorsItem } from "./adminOrderUpdateStatus403ErrorsItem";

export type AdminOrderUpdateStatus403 = {
  message: string;
  code: string;
  errors?: AdminOrderUpdateStatus403ErrorsItem[];
};
