/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminEmployeeDeactivate401ErrorsItem } from "./adminEmployeeDeactivate401ErrorsItem";

export type AdminEmployeeDeactivate401 = {
  message: string;
  code: string;
  errors?: AdminEmployeeDeactivate401ErrorsItem[];
};
