/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderGetAllStatus } from "./adminOrderGetAllStatus";
import type { AdminOrderGetAllSortBy } from "./adminOrderGetAllSortBy";
import type { AdminOrderGetAllSortOrder } from "./adminOrderGetAllSortOrder";

export type AdminOrderGetAllParams = {
  status?: AdminOrderGetAllStatus;
  search?: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset?: number | null;
  sortBy?: AdminOrderGetAllSortBy;
  sortOrder?: AdminOrderGetAllSortOrder;
};
