/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminMenuGetAllSortOrder =
  (typeof AdminMenuGetAllSortOrder)[keyof typeof AdminMenuGetAllSortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminMenuGetAllSortOrder = {
  ASC: "ASC",
  DESC: "DESC",
} as const;
