/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuGetOne401ErrorsItem } from "./adminMenuGetOne401ErrorsItem";

export type AdminMenuGetOne401 = {
  message: string;
  code: string;
  errors?: AdminMenuGetOne401ErrorsItem[];
};
