/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminStatsRevenueByMenu403ErrorsItem } from "./adminStatsRevenueByMenu403ErrorsItem";

export type AdminStatsRevenueByMenu403 = {
  message: string;
  code: string;
  errors?: AdminStatsRevenueByMenu403ErrorsItem[];
};
