/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminReviewApprove401ErrorsItem } from "./adminReviewApprove401ErrorsItem";

export type AdminReviewApprove401 = {
  message: string;
  code: string;
  errors?: AdminReviewApprove401ErrorsItem[];
};
