/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminEmployeeGetAllIsActive =
  (typeof AdminEmployeeGetAllIsActive)[keyof typeof AdminEmployeeGetAllIsActive];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminEmployeeGetAllIsActive = {
  true: "true",
  false: "false",
} as const;
