/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminStatsOrdersByMenu403ErrorsItem } from "./adminStatsOrdersByMenu403ErrorsItem";

export type AdminStatsOrdersByMenu403 = {
  message: string;
  code: string;
  errors?: AdminStatsOrdersByMenu403ErrorsItem[];
};
