/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDietaryRegimeUpdate401ErrorsItem } from "./adminDietaryRegimeUpdate401ErrorsItem";

export type AdminDietaryRegimeUpdate401 = {
  message: string;
  code: string;
  errors?: AdminDietaryRegimeUpdate401ErrorsItem[];
};
