/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDeliveryZoneCreate400ErrorsItem } from "./adminDeliveryZoneCreate400ErrorsItem";

export type AdminDeliveryZoneCreate400 = {
  message: string;
  code: string;
  errors?: AdminDeliveryZoneCreate400ErrorsItem[];
};
