/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderGetOne200HistoryItemOldStatus } from "./adminOrderGetOne200HistoryItemOldStatus";
import type { AdminOrderGetOne200HistoryItemNewStatus } from "./adminOrderGetOne200HistoryItemNewStatus";
import type { AdminOrderGetOne200HistoryItemChangedBy } from "./adminOrderGetOne200HistoryItemChangedBy";
import type { AdminOrderGetOne200HistoryItemReason } from "./adminOrderGetOne200HistoryItemReason";
import type { AdminOrderGetOne200HistoryItemContactMode } from "./adminOrderGetOne200HistoryItemContactMode";

export type AdminOrderGetOne200HistoryItem = {
  id: string;
  oldStatus: AdminOrderGetOne200HistoryItemOldStatus;
  newStatus: AdminOrderGetOne200HistoryItemNewStatus;
  changedBy: AdminOrderGetOne200HistoryItemChangedBy;
  reason: AdminOrderGetOne200HistoryItemReason;
  contactMode: AdminOrderGetOne200HistoryItemContactMode;
  createdAt: string;
};
