/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuGetAll401ErrorsItem } from "./adminMenuGetAll401ErrorsItem";

export type AdminMenuGetAll401 = {
  message: string;
  code: string;
  errors?: AdminMenuGetAll401ErrorsItem[];
};
