/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderUpdateStatus200HistoryItemOldStatus } from "./adminOrderUpdateStatus200HistoryItemOldStatus";
import type { AdminOrderUpdateStatus200HistoryItemNewStatus } from "./adminOrderUpdateStatus200HistoryItemNewStatus";
import type { AdminOrderUpdateStatus200HistoryItemChangedBy } from "./adminOrderUpdateStatus200HistoryItemChangedBy";
import type { AdminOrderUpdateStatus200HistoryItemReason } from "./adminOrderUpdateStatus200HistoryItemReason";
import type { AdminOrderUpdateStatus200HistoryItemContactMode } from "./adminOrderUpdateStatus200HistoryItemContactMode";

export type AdminOrderUpdateStatus200HistoryItem = {
  id: string;
  oldStatus: AdminOrderUpdateStatus200HistoryItemOldStatus;
  newStatus: AdminOrderUpdateStatus200HistoryItemNewStatus;
  changedBy: AdminOrderUpdateStatus200HistoryItemChangedBy;
  reason: AdminOrderUpdateStatus200HistoryItemReason;
  contactMode: AdminOrderUpdateStatus200HistoryItemContactMode;
  createdAt: string;
};
