/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDishCreateBodyDescription } from "./adminDishCreateBodyDescription";
import type { AdminDishCreateBodyCategory } from "./adminDishCreateBodyCategory";
import type { AdminDishCreateBodyPrice } from "./adminDishCreateBodyPrice";
import type { AdminDishCreateBodyImageUrl } from "./adminDishCreateBodyImageUrl";

export type AdminDishCreateBody = {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  description?: AdminDishCreateBodyDescription;
  category: AdminDishCreateBodyCategory;
  /** @minimum 0 */
  price?: AdminDishCreateBodyPrice;
  imageUrl?: AdminDishCreateBodyImageUrl;
  isAvailable?: boolean;
  allergenIds?: string[];
};
