/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminMenuGetAllSortBy =
  (typeof AdminMenuGetAllSortBy)[keyof typeof AdminMenuGetAllSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminMenuGetAllSortBy = {
  name: "name",
  price: "price",
  minPersons: "minPersons",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
} as const;
