/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminAllergenCreate400ErrorsItem } from "./adminAllergenCreate400ErrorsItem";

export type AdminAllergenCreate400 = {
  message: string;
  code: string;
  errors?: AdminAllergenCreate400ErrorsItem[];
};
