/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminEmployeeGetAll403ErrorsItem } from "./adminEmployeeGetAll403ErrorsItem";

export type AdminEmployeeGetAll403 = {
  message: string;
  code: string;
  errors?: AdminEmployeeGetAll403ErrorsItem[];
};
