/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOperatingHoursUpsert401ErrorsItem } from "./adminOperatingHoursUpsert401ErrorsItem";

export type AdminOperatingHoursUpsert401 = {
  message: string;
  code: string;
  errors?: AdminOperatingHoursUpsert401ErrorsItem[];
};
