/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOperatingHoursUpsert200ItemsItemOpenTime } from "./adminOperatingHoursUpsert200ItemsItemOpenTime";
import type { AdminOperatingHoursUpsert200ItemsItemCloseTime } from "./adminOperatingHoursUpsert200ItemsItemCloseTime";

export type AdminOperatingHoursUpsert200ItemsItem = {
  id: string;
  /**
   * @minimum 0
   * @maximum 6
   */
  dayOfWeek: number;
  openTime: AdminOperatingHoursUpsert200ItemsItemOpenTime;
  closeTime: AdminOperatingHoursUpsert200ItemsItemCloseTime;
  isClosed: boolean;
};
