/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminEmployeeGetAll401ErrorsItem } from "./adminEmployeeGetAll401ErrorsItem";

export type AdminEmployeeGetAll401 = {
  message: string;
  code: string;
  errors?: AdminEmployeeGetAll401ErrorsItem[];
};
