/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDishGetOne401ErrorsItem } from "./adminDishGetOne401ErrorsItem";

export type AdminDishGetOne401 = {
  message: string;
  code: string;
  errors?: AdminDishGetOne401ErrorsItem[];
};
