/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminStatsOrdersByMenu401ErrorsItem } from "./adminStatsOrdersByMenu401ErrorsItem";

export type AdminStatsOrdersByMenu401 = {
  message: string;
  code: string;
  errors?: AdminStatsOrdersByMenu401ErrorsItem[];
};
