/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminEmployeeDeactivate200Role } from "./adminEmployeeDeactivate200Role";
import type { AdminEmployeeDeactivate200Phone } from "./adminEmployeeDeactivate200Phone";
import type { AdminEmployeeDeactivate200Address } from "./adminEmployeeDeactivate200Address";
import type { AdminEmployeeDeactivate200City } from "./adminEmployeeDeactivate200City";
import type { AdminEmployeeDeactivate200PostalCode } from "./adminEmployeeDeactivate200PostalCode";
import type { AdminEmployeeDeactivate200LastLoginAt } from "./adminEmployeeDeactivate200LastLoginAt";

export type AdminEmployeeDeactivate200 = {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: AdminEmployeeDeactivate200Role;
  admin: boolean;
  phone: AdminEmployeeDeactivate200Phone;
  address: AdminEmployeeDeactivate200Address;
  city: AdminEmployeeDeactivate200City;
  postalCode: AdminEmployeeDeactivate200PostalCode;
  isActive: boolean;
  emailVerified: boolean;
  preferredLanguage: string;
  lastLoginAt: AdminEmployeeDeactivate200LastLoginAt;
  createdAt: string;
  updatedAt: string;
};
