/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDishCreate401ErrorsItem } from "./adminDishCreate401ErrorsItem";

export type AdminDishCreate401 = {
  message: string;
  code: string;
  errors?: AdminDishCreate401ErrorsItem[];
};
