/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderGetAll200ItemsItem } from "./adminOrderGetAll200ItemsItem";

export type AdminOrderGetAll200 = {
  items: AdminOrderGetAll200ItemsItem[];
  totalCount: number;
};
