/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuCreateBodyDescription } from "./adminMenuCreateBodyDescription";
import type { AdminMenuCreateBodyTheme } from "./adminMenuCreateBodyTheme";
import type { AdminMenuCreateBodyMaxPersons } from "./adminMenuCreateBodyMaxPersons";
import type { AdminMenuCreateBodyStock } from "./adminMenuCreateBodyStock";
import type { AdminMenuCreateBodyConditions } from "./adminMenuCreateBodyConditions";
import type { AdminMenuCreateBodyImageUrl } from "./adminMenuCreateBodyImageUrl";

export type AdminMenuCreateBody = {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  description?: AdminMenuCreateBodyDescription;
  /** @maxLength 255 */
  theme?: AdminMenuCreateBodyTheme;
  /** @minimum 0 */
  price: number;
  /** @minimum 1 */
  minPersons?: number;
  /** @minimum 1 */
  maxPersons?: AdminMenuCreateBodyMaxPersons;
  /** @minimum 0 */
  stock?: AdminMenuCreateBodyStock;
  conditions?: AdminMenuCreateBodyConditions;
  imageUrl?: AdminMenuCreateBodyImageUrl;
  isAvailable?: boolean;
  dishIds?: string[];
  dietaryRegimeIds?: string[];
};
