/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDietaryRegimeUpdateBodyDescription } from "./adminDietaryRegimeUpdateBodyDescription";

export type AdminDietaryRegimeUpdateBody = {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name?: string;
  description?: AdminDietaryRegimeUpdateBodyDescription;
};
