/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminDishGetAll200ItemsItemCategory =
  (typeof AdminDishGetAll200ItemsItemCategory)[keyof typeof AdminDishGetAll200ItemsItemCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminDishGetAll200ItemsItemCategory = {
  entree: "entree",
  plat: "plat",
  dessert: "dessert",
} as const;
