/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminAllergenUpdate400ErrorsItem } from "./adminAllergenUpdate400ErrorsItem";

export type AdminAllergenUpdate400 = {
  message: string;
  code: string;
  errors?: AdminAllergenUpdate400ErrorsItem[];
};
