/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderGetOne404ErrorsItem } from "./adminOrderGetOne404ErrorsItem";

export type AdminOrderGetOne404 = {
  message: string;
  code: string;
  errors?: AdminOrderGetOne404ErrorsItem[];
};
