/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminOrderUpdateStatusBodyContactMode =
  (typeof AdminOrderUpdateStatusBodyContactMode)[keyof typeof AdminOrderUpdateStatusBodyContactMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminOrderUpdateStatusBodyContactMode = {
  PHONE: "PHONE",
  EMAIL: "EMAIL",
} as const;
