/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuGetOne200DishesItemAllergensItemIcon } from "./adminMenuGetOne200DishesItemAllergensItemIcon";

export type AdminMenuGetOne200DishesItemAllergensItem = {
  id: string;
  name: string;
  icon: AdminMenuGetOne200DishesItemAllergensItemIcon;
};
