/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminAllergenUpdate404ErrorsItem } from "./adminAllergenUpdate404ErrorsItem";

export type AdminAllergenUpdate404 = {
  message: string;
  code: string;
  errors?: AdminAllergenUpdate404ErrorsItem[];
};
