/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminEmployeeCreate201Role } from "./adminEmployeeCreate201Role";
import type { AdminEmployeeCreate201Phone } from "./adminEmployeeCreate201Phone";
import type { AdminEmployeeCreate201Address } from "./adminEmployeeCreate201Address";
import type { AdminEmployeeCreate201City } from "./adminEmployeeCreate201City";
import type { AdminEmployeeCreate201PostalCode } from "./adminEmployeeCreate201PostalCode";
import type { AdminEmployeeCreate201LastLoginAt } from "./adminEmployeeCreate201LastLoginAt";

export type AdminEmployeeCreate201 = {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: AdminEmployeeCreate201Role;
  admin: boolean;
  phone: AdminEmployeeCreate201Phone;
  address: AdminEmployeeCreate201Address;
  city: AdminEmployeeCreate201City;
  postalCode: AdminEmployeeCreate201PostalCode;
  isActive: boolean;
  emailVerified: boolean;
  preferredLanguage: string;
  lastLoginAt: AdminEmployeeCreate201LastLoginAt;
  createdAt: string;
  updatedAt: string;
};
