/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminStatsOrdersByMenu200ItemsItem } from "./adminStatsOrdersByMenu200ItemsItem";

export type AdminStatsOrdersByMenu200 = {
  items: AdminStatsOrdersByMenu200ItemsItem[];
};
