/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuCreate401ErrorsItem } from "./adminMenuCreate401ErrorsItem";

export type AdminMenuCreate401 = {
  message: string;
  code: string;
  errors?: AdminMenuCreate401ErrorsItem[];
};
