/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDietaryRegimeCreate403ErrorsItem } from "./adminDietaryRegimeCreate403ErrorsItem";

export type AdminDietaryRegimeCreate403 = {
  message: string;
  code: string;
  errors?: AdminDietaryRegimeCreate403ErrorsItem[];
};
