/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminOrderGetAllSortOrder =
  (typeof AdminOrderGetAllSortOrder)[keyof typeof AdminOrderGetAllSortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminOrderGetAllSortOrder = {
  ASC: "ASC",
  DESC: "DESC",
} as const;
