/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDietaryRegimeCreate400ErrorsItem } from "./adminDietaryRegimeCreate400ErrorsItem";

export type AdminDietaryRegimeCreate400 = {
  message: string;
  code: string;
  errors?: AdminDietaryRegimeCreate400ErrorsItem[];
};
