/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuDelete401ErrorsItem } from "./adminMenuDelete401ErrorsItem";

export type AdminMenuDelete401 = {
  message: string;
  code: string;
  errors?: AdminMenuDelete401ErrorsItem[];
};
