/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminReviewGetAllSortBy =
  (typeof AdminReviewGetAllSortBy)[keyof typeof AdminReviewGetAllSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminReviewGetAllSortBy = {
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  rating: "rating",
} as const;
