/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminOrderGetAllSortBy =
  (typeof AdminOrderGetAllSortBy)[keyof typeof AdminOrderGetAllSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminOrderGetAllSortBy = {
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  totalPrice: "totalPrice",
  status: "status",
  deliveryDate: "deliveryDate",
} as const;
