/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminEmployeeGetAll200ItemsItemRole } from "./adminEmployeeGetAll200ItemsItemRole";

export type AdminEmployeeGetAll200ItemsItem = {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: AdminEmployeeGetAll200ItemsItemRole;
  isActive: boolean;
  emailVerified: boolean;
  createdAt: string;
  updatedAt: string;
};
