/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminAllergenGetAllSortOrder =
  (typeof AdminAllergenGetAllSortOrder)[keyof typeof AdminAllergenGetAllSortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminAllergenGetAllSortOrder = {
  ASC: "ASC",
  DESC: "DESC",
} as const;
