/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDeliveryZoneGetAll403ErrorsItem } from "./adminDeliveryZoneGetAll403ErrorsItem";

export type AdminDeliveryZoneGetAll403 = {
  message: string;
  code: string;
  errors?: AdminDeliveryZoneGetAll403ErrorsItem[];
};
