/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDietaryRegimeDelete404ErrorsItem } from "./adminDietaryRegimeDelete404ErrorsItem";

export type AdminDietaryRegimeDelete404 = {
  message: string;
  code: string;
  errors?: AdminDietaryRegimeDelete404ErrorsItem[];
};
