/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminEmployeeGetAll200ItemsItemRole =
  (typeof AdminEmployeeGetAll200ItemsItemRole)[keyof typeof AdminEmployeeGetAll200ItemsItemRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminEmployeeGetAll200ItemsItemRole = {
  USER: "USER",
  EMPLOYEE: "EMPLOYEE",
  ADMIN: "ADMIN",
} as const;
