/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuUpdate200DishesItemAllergensItemIcon } from "./adminMenuUpdate200DishesItemAllergensItemIcon";

export type AdminMenuUpdate200DishesItemAllergensItem = {
  id: string;
  name: string;
  icon: AdminMenuUpdate200DishesItemAllergensItemIcon;
};
