/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminAllergenGetAll200ItemsItemIcon } from "./adminAllergenGetAll200ItemsItemIcon";

export type AdminAllergenGetAll200ItemsItem = {
  id: string;
  name: string;
  icon: AdminAllergenGetAll200ItemsItemIcon;
  createdAt: string;
};
