/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPageContentUpsert403ErrorsItem } from "./adminPageContentUpsert403ErrorsItem";

export type AdminPageContentUpsert403 = {
  message: string;
  code: string;
  errors?: AdminPageContentUpsert403ErrorsItem[];
};
