/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOperatingHoursGetAll401ErrorsItem } from "./adminOperatingHoursGetAll401ErrorsItem";

export type AdminOperatingHoursGetAll401 = {
  message: string;
  code: string;
  errors?: AdminOperatingHoursGetAll401ErrorsItem[];
};
