/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuGetAll200ItemsItem } from "./adminMenuGetAll200ItemsItem";

export type AdminMenuGetAll200 = {
  items: AdminMenuGetAll200ItemsItem[];
  totalCount: number;
};
