/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminEmployeeCreate401ErrorsItem } from "./adminEmployeeCreate401ErrorsItem";

export type AdminEmployeeCreate401 = {
  message: string;
  code: string;
  errors?: AdminEmployeeCreate401ErrorsItem[];
};
