/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuDelete403ErrorsItem } from "./adminMenuDelete403ErrorsItem";

export type AdminMenuDelete403 = {
  message: string;
  code: string;
  errors?: AdminMenuDelete403ErrorsItem[];
};
