/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminEmployeeDeactivate404ErrorsItem } from "./adminEmployeeDeactivate404ErrorsItem";

export type AdminEmployeeDeactivate404 = {
  message: string;
  code: string;
  errors?: AdminEmployeeDeactivate404ErrorsItem[];
};
