/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminReviewGetAll200ItemsItem } from "./adminReviewGetAll200ItemsItem";

export type AdminReviewGetAll200 = {
  items: AdminReviewGetAll200ItemsItem[];
  totalCount: number;
};
