/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminAllergenGetAll401ErrorsItem } from "./adminAllergenGetAll401ErrorsItem";

export type AdminAllergenGetAll401 = {
  message: string;
  code: string;
  errors?: AdminAllergenGetAll401ErrorsItem[];
};
