/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminAllergenCreate201Icon } from "./adminAllergenCreate201Icon";

export type AdminAllergenCreate201 = {
  id: string;
  name: string;
  icon: AdminAllergenCreate201Icon;
  createdAt: string;
};
