/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminReviewApprove403ErrorsItem } from "./adminReviewApprove403ErrorsItem";

export type AdminReviewApprove403 = {
  message: string;
  code: string;
  errors?: AdminReviewApprove403ErrorsItem[];
};
