/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPageContentUpsert401ErrorsItem } from "./adminPageContentUpsert401ErrorsItem";

export type AdminPageContentUpsert401 = {
  message: string;
  code: string;
  errors?: AdminPageContentUpsert401ErrorsItem[];
};
