/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminEmployeeDeactivate403ErrorsItem } from "./adminEmployeeDeactivate403ErrorsItem";

export type AdminEmployeeDeactivate403 = {
  message: string;
  code: string;
  errors?: AdminEmployeeDeactivate403ErrorsItem[];
};
