/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminDishGetOne200Category =
  (typeof AdminDishGetOne200Category)[keyof typeof AdminDishGetOne200Category];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminDishGetOne200Category = {
  entree: "entree",
  plat: "plat",
  dessert: "dessert",
} as const;
