/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDishUpdate200Description } from "./adminDishUpdate200Description";
import type { AdminDishUpdate200Category } from "./adminDishUpdate200Category";
import type { AdminDishUpdate200Price } from "./adminDishUpdate200Price";
import type { AdminDishUpdate200ImageUrl } from "./adminDishUpdate200ImageUrl";
import type { AdminDishUpdate200AllergensItem } from "./adminDishUpdate200AllergensItem";

export type AdminDishUpdate200 = {
  id: string;
  name: string;
  description: AdminDishUpdate200Description;
  category: AdminDishUpdate200Category;
  price: AdminDishUpdate200Price;
  imageUrl: AdminDishUpdate200ImageUrl;
  isAvailable: boolean;
  createdAt: string;
  updatedAt: string;
  allergens: AdminDishUpdate200AllergensItem[];
};
