/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuCreate201DishesItemCategory } from "./adminMenuCreate201DishesItemCategory";
import type { AdminMenuCreate201DishesItemDescription } from "./adminMenuCreate201DishesItemDescription";
import type { AdminMenuCreate201DishesItemPrice } from "./adminMenuCreate201DishesItemPrice";
import type { AdminMenuCreate201DishesItemAllergensItem } from "./adminMenuCreate201DishesItemAllergensItem";

export type AdminMenuCreate201DishesItem = {
  id: string;
  name: string;
  category: AdminMenuCreate201DishesItemCategory;
  description: AdminMenuCreate201DishesItemDescription;
  price: AdminMenuCreate201DishesItemPrice;
  allergens: AdminMenuCreate201DishesItemAllergensItem[];
};
