/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminEmployeeCreate403ErrorsItem } from "./adminEmployeeCreate403ErrorsItem";

export type AdminEmployeeCreate403 = {
  message: string;
  code: string;
  errors?: AdminEmployeeCreate403ErrorsItem[];
};
