/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @maxLength 255
 */
export type AdminMenuCreateBodyTheme = string | null;
