/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDeliveryZoneCreate401ErrorsItem } from "./adminDeliveryZoneCreate401ErrorsItem";

export type AdminDeliveryZoneCreate401 = {
  message: string;
  code: string;
  errors?: AdminDeliveryZoneCreate401ErrorsItem[];
};
