/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderGetOne200ItemsItemMenuName } from "./adminOrderGetOne200ItemsItemMenuName";

export type AdminOrderGetOne200ItemsItem = {
  id: string;
  menuId: string;
  menuName: AdminOrderGetOne200ItemsItemMenuName;
  quantity: number;
  unitPrice: number;
  lineTotal: number;
  discountApplied: boolean;
};
