/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuCreate201Description } from "./adminMenuCreate201Description";
import type { AdminMenuCreate201Theme } from "./adminMenuCreate201Theme";
import type { AdminMenuCreate201MaxPersons } from "./adminMenuCreate201MaxPersons";
import type { AdminMenuCreate201Stock } from "./adminMenuCreate201Stock";
import type { AdminMenuCreate201Conditions } from "./adminMenuCreate201Conditions";
import type { AdminMenuCreate201ImageUrl } from "./adminMenuCreate201ImageUrl";
import type { AdminMenuCreate201DishesItem } from "./adminMenuCreate201DishesItem";
import type { AdminMenuCreate201DietaryRegimesItem } from "./adminMenuCreate201DietaryRegimesItem";

export type AdminMenuCreate201 = {
  id: string;
  name: string;
  description: AdminMenuCreate201Description;
  theme: AdminMenuCreate201Theme;
  price: number;
  minPersons: number;
  maxPersons: AdminMenuCreate201MaxPersons;
  stock: AdminMenuCreate201Stock;
  conditions: AdminMenuCreate201Conditions;
  imageUrl: AdminMenuCreate201ImageUrl;
  isAvailable: boolean;
  createdAt: string;
  updatedAt: string;
  dishes: AdminMenuCreate201DishesItem[];
  dietaryRegimes: AdminMenuCreate201DietaryRegimesItem[];
};
