/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuGetAllIsAvailable } from "./adminMenuGetAllIsAvailable";
import type { AdminMenuGetAllSortBy } from "./adminMenuGetAllSortBy";
import type { AdminMenuGetAllSortOrder } from "./adminMenuGetAllSortOrder";

export type AdminMenuGetAllParams = {
  theme?: string;
  dietaryRegimeId?: string;
  priceMax?: number | null;
  priceMin?: number | null;
  maxMinPersons?: number | null;
  search?: string;
  isAvailable?: AdminMenuGetAllIsAvailable;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset?: number | null;
  sortBy?: AdminMenuGetAllSortBy;
  sortOrder?: AdminMenuGetAllSortOrder;
};
