/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDishGetOne200Description } from "./adminDishGetOne200Description";
import type { AdminDishGetOne200Category } from "./adminDishGetOne200Category";
import type { AdminDishGetOne200Price } from "./adminDishGetOne200Price";
import type { AdminDishGetOne200ImageUrl } from "./adminDishGetOne200ImageUrl";
import type { AdminDishGetOne200AllergensItem } from "./adminDishGetOne200AllergensItem";

export type AdminDishGetOne200 = {
  id: string;
  name: string;
  description: AdminDishGetOne200Description;
  category: AdminDishGetOne200Category;
  price: AdminDishGetOne200Price;
  imageUrl: AdminDishGetOne200ImageUrl;
  isAvailable: boolean;
  createdAt: string;
  updatedAt: string;
  allergens: AdminDishGetOne200AllergensItem[];
};
