/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderUpdateStatus404ErrorsItem } from "./adminOrderUpdateStatus404ErrorsItem";

export type AdminOrderUpdateStatus404 = {
  message: string;
  code: string;
  errors?: AdminOrderUpdateStatus404ErrorsItem[];
};
