/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminDishGetAllCategory =
  (typeof AdminDishGetAllCategory)[keyof typeof AdminDishGetAllCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminDishGetAllCategory = {
  entree: "entree",
  plat: "plat",
  dessert: "dessert",
} as const;
