/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDietaryRegimeUpdate404ErrorsItem } from "./adminDietaryRegimeUpdate404ErrorsItem";

export type AdminDietaryRegimeUpdate404 = {
  message: string;
  code: string;
  errors?: AdminDietaryRegimeUpdate404ErrorsItem[];
};
