/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @minLength 1
 * @maxLength 50
 */
export type AdminEmployeeCreateBodyPhone = string | null;
