/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDietaryRegimeDelete403ErrorsItem } from "./adminDietaryRegimeDelete403ErrorsItem";

export type AdminDietaryRegimeDelete403 = {
  message: string;
  code: string;
  errors?: AdminDietaryRegimeDelete403ErrorsItem[];
};
