/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuCreate201DishesItemAllergensItemIcon } from "./adminMenuCreate201DishesItemAllergensItemIcon";

export type AdminMenuCreate201DishesItemAllergensItem = {
  id: string;
  name: string;
  icon: AdminMenuCreate201DishesItemAllergensItemIcon;
};
