/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDietaryRegimeCreate201Description } from "./adminDietaryRegimeCreate201Description";

export type AdminDietaryRegimeCreate201 = {
  id: string;
  name: string;
  description: AdminDietaryRegimeCreate201Description;
  createdAt: string;
};
