/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDishGetOne200AllergensItemIcon } from "./adminDishGetOne200AllergensItemIcon";

export type AdminDishGetOne200AllergensItem = {
  id: string;
  name: string;
  icon: AdminDishGetOne200AllergensItemIcon;
};
