/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminContactMessageGetAllIsRead } from "./adminContactMessageGetAllIsRead";
import type { AdminContactMessageGetAllSortOrder } from "./adminContactMessageGetAllSortOrder";

export type AdminContactMessageGetAllParams = {
  isRead?: AdminContactMessageGetAllIsRead;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset?: number | null;
  sortOrder?: AdminContactMessageGetAllSortOrder;
};
