/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDeliveryZoneUpdateBodyPostalCode } from "./adminDeliveryZoneUpdateBodyPostalCode";
import type { AdminDeliveryZoneUpdateBodyCity } from "./adminDeliveryZoneUpdateBodyCity";

export type AdminDeliveryZoneUpdateBody = {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name?: string;
  /** @maxLength 20 */
  postalCode?: AdminDeliveryZoneUpdateBodyPostalCode;
  /** @maxLength 255 */
  city?: AdminDeliveryZoneUpdateBodyCity;
  /** @minimum 0 */
  distanceKm?: number;
  isActive?: boolean;
};
