/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminAllergenCreate401ErrorsItem } from "./adminAllergenCreate401ErrorsItem";

export type AdminAllergenCreate401 = {
  message: string;
  code: string;
  errors?: AdminAllergenCreate401ErrorsItem[];
};
