/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDietaryRegimeGetAll401ErrorsItem } from "./adminDietaryRegimeGetAll401ErrorsItem";

export type AdminDietaryRegimeGetAll401 = {
  message: string;
  code: string;
  errors?: AdminDietaryRegimeGetAll401ErrorsItem[];
};
