/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminReviewGetAllIsApproved } from "./adminReviewGetAllIsApproved";
import type { AdminReviewGetAllSortBy } from "./adminReviewGetAllSortBy";
import type { AdminReviewGetAllSortOrder } from "./adminReviewGetAllSortOrder";

export type AdminReviewGetAllParams = {
  isApproved?: AdminReviewGetAllIsApproved;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset?: number | null;
  sortBy?: AdminReviewGetAllSortBy;
  sortOrder?: AdminReviewGetAllSortOrder;
};
