/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminReviewGetAll403ErrorsItem } from "./adminReviewGetAll403ErrorsItem";

export type AdminReviewGetAll403 = {
  message: string;
  code: string;
  errors?: AdminReviewGetAll403ErrorsItem[];
};
