/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDeliveryZoneCreate403ErrorsItem } from "./adminDeliveryZoneCreate403ErrorsItem";

export type AdminDeliveryZoneCreate403 = {
  message: string;
  code: string;
  errors?: AdminDeliveryZoneCreate403ErrorsItem[];
};
