/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDeliveryZoneUpdate200PostalCode } from "./adminDeliveryZoneUpdate200PostalCode";
import type { AdminDeliveryZoneUpdate200City } from "./adminDeliveryZoneUpdate200City";

export type AdminDeliveryZoneUpdate200 = {
  id: string;
  name: string;
  postalCode: AdminDeliveryZoneUpdate200PostalCode;
  city: AdminDeliveryZoneUpdate200City;
  distanceKm: number;
  isActive: boolean;
  createdAt: string;
};
