/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDeliveryZoneGetAll401ErrorsItem } from "./adminDeliveryZoneGetAll401ErrorsItem";

export type AdminDeliveryZoneGetAll401 = {
  message: string;
  code: string;
  errors?: AdminDeliveryZoneGetAll401ErrorsItem[];
};
