/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPageContentUpsertBodyContent } from "./adminPageContentUpsertBodyContent";

export type AdminPageContentUpsertBody = {
  /**
   * @minLength 1
   * @maxLength 100
   */
  page: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  section: string;
  content: AdminPageContentUpsertBodyContent;
};
