/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminAllergenGetAll200ItemsItem } from "./adminAllergenGetAll200ItemsItem";

export type AdminAllergenGetAll200 = {
  items: AdminAllergenGetAll200ItemsItem[];
  totalCount: number;
};
