/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderGetOne401ErrorsItem } from "./adminOrderGetOne401ErrorsItem";

export type AdminOrderGetOne401 = {
  message: string;
  code: string;
  errors?: AdminOrderGetOne401ErrorsItem[];
};
