/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDishGetAll403ErrorsItem } from "./adminDishGetAll403ErrorsItem";

export type AdminDishGetAll403 = {
  message: string;
  code: string;
  errors?: AdminDishGetAll403ErrorsItem[];
};
