/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDeliveryZoneGetAll200ItemsItemPostalCode } from "./adminDeliveryZoneGetAll200ItemsItemPostalCode";
import type { AdminDeliveryZoneGetAll200ItemsItemCity } from "./adminDeliveryZoneGetAll200ItemsItemCity";

export type AdminDeliveryZoneGetAll200ItemsItem = {
  id: string;
  name: string;
  postalCode: AdminDeliveryZoneGetAll200ItemsItemPostalCode;
  city: AdminDeliveryZoneGetAll200ItemsItemCity;
  distanceKm: number;
  isActive: boolean;
  createdAt: string;
};
