/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminOrderGetOne200HistoryItemOldStatus =
  | "PENDING"
  | "ACCEPTED"
  | "PREPARING"
  | "DELIVERING"
  | "DELIVERED"
  | "AWAITING_MATERIAL_RETURN"
  | "COMPLETED"
  | "REJECTED"
  | "CANCELLED"
  | null;
