/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminEmployeeReactivate200Role } from "./adminEmployeeReactivate200Role";
import type { AdminEmployeeReactivate200Phone } from "./adminEmployeeReactivate200Phone";
import type { AdminEmployeeReactivate200Address } from "./adminEmployeeReactivate200Address";
import type { AdminEmployeeReactivate200City } from "./adminEmployeeReactivate200City";
import type { AdminEmployeeReactivate200PostalCode } from "./adminEmployeeReactivate200PostalCode";
import type { AdminEmployeeReactivate200LastLoginAt } from "./adminEmployeeReactivate200LastLoginAt";

export type AdminEmployeeReactivate200 = {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: AdminEmployeeReactivate200Role;
  admin: boolean;
  phone: AdminEmployeeReactivate200Phone;
  address: AdminEmployeeReactivate200Address;
  city: AdminEmployeeReactivate200City;
  postalCode: AdminEmployeeReactivate200PostalCode;
  isActive: boolean;
  emailVerified: boolean;
  preferredLanguage: string;
  lastLoginAt: AdminEmployeeReactivate200LastLoginAt;
  createdAt: string;
  updatedAt: string;
};
