/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDishUpdate200AllergensItemIcon } from "./adminDishUpdate200AllergensItemIcon";

export type AdminDishUpdate200AllergensItem = {
  id: string;
  name: string;
  icon: AdminDishUpdate200AllergensItemIcon;
};
