/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminContactMessageMarkRead403ErrorsItem } from "./adminContactMessageMarkRead403ErrorsItem";

export type AdminContactMessageMarkRead403 = {
  message: string;
  code: string;
  errors?: AdminContactMessageMarkRead403ErrorsItem[];
};
