/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDeliveryZoneGetAllIsActive } from "./adminDeliveryZoneGetAllIsActive";
import type { AdminDeliveryZoneGetAllSortBy } from "./adminDeliveryZoneGetAllSortBy";
import type { AdminDeliveryZoneGetAllSortOrder } from "./adminDeliveryZoneGetAllSortOrder";

export type AdminDeliveryZoneGetAllParams = {
  search?: string;
  isActive?: AdminDeliveryZoneGetAllIsActive;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset?: number | null;
  sortBy?: AdminDeliveryZoneGetAllSortBy;
  sortOrder?: AdminDeliveryZoneGetAllSortOrder;
};
