/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminReviewDelete401ErrorsItem } from "./adminReviewDelete401ErrorsItem";

export type AdminReviewDelete401 = {
  message: string;
  code: string;
  errors?: AdminReviewDelete401ErrorsItem[];
};
