/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminEmployeeReactivate400ErrorsItem } from "./adminEmployeeReactivate400ErrorsItem";

export type AdminEmployeeReactivate400 = {
  message: string;
  code: string;
  errors?: AdminEmployeeReactivate400ErrorsItem[];
};
