/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminDietaryRegimeGetAllSortBy =
  (typeof AdminDietaryRegimeGetAllSortBy)[keyof typeof AdminDietaryRegimeGetAllSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminDietaryRegimeGetAllSortBy = {
  name: "name",
  createdAt: "createdAt",
} as const;
