/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDietaryRegimeCreate401ErrorsItem } from "./adminDietaryRegimeCreate401ErrorsItem";

export type AdminDietaryRegimeCreate401 = {
  message: string;
  code: string;
  errors?: AdminDietaryRegimeCreate401ErrorsItem[];
};
