/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminAllergenCreate403ErrorsItem } from "./adminAllergenCreate403ErrorsItem";

export type AdminAllergenCreate403 = {
  message: string;
  code: string;
  errors?: AdminAllergenCreate403ErrorsItem[];
};
