/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminEmployeeGetAllIsActive } from "./adminEmployeeGetAllIsActive";
import type { AdminEmployeeGetAllSortBy } from "./adminEmployeeGetAllSortBy";
import type { AdminEmployeeGetAllSortOrder } from "./adminEmployeeGetAllSortOrder";

export type AdminEmployeeGetAllParams = {
  isActive?: AdminEmployeeGetAllIsActive;
  search?: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset?: number | null;
  sortBy?: AdminEmployeeGetAllSortBy;
  sortOrder?: AdminEmployeeGetAllSortOrder;
};
