/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuUpdate200Description } from "./adminMenuUpdate200Description";
import type { AdminMenuUpdate200Theme } from "./adminMenuUpdate200Theme";
import type { AdminMenuUpdate200MaxPersons } from "./adminMenuUpdate200MaxPersons";
import type { AdminMenuUpdate200Stock } from "./adminMenuUpdate200Stock";
import type { AdminMenuUpdate200Conditions } from "./adminMenuUpdate200Conditions";
import type { AdminMenuUpdate200ImageUrl } from "./adminMenuUpdate200ImageUrl";
import type { AdminMenuUpdate200DishesItem } from "./adminMenuUpdate200DishesItem";
import type { AdminMenuUpdate200DietaryRegimesItem } from "./adminMenuUpdate200DietaryRegimesItem";

export type AdminMenuUpdate200 = {
  id: string;
  name: string;
  description: AdminMenuUpdate200Description;
  theme: AdminMenuUpdate200Theme;
  price: number;
  minPersons: number;
  maxPersons: AdminMenuUpdate200MaxPersons;
  stock: AdminMenuUpdate200Stock;
  conditions: AdminMenuUpdate200Conditions;
  imageUrl: AdminMenuUpdate200ImageUrl;
  isAvailable: boolean;
  createdAt: string;
  updatedAt: string;
  dishes: AdminMenuUpdate200DishesItem[];
  dietaryRegimes: AdminMenuUpdate200DietaryRegimesItem[];
};
