/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminAllergenGetAllSortBy } from "./adminAllergenGetAllSortBy";
import type { AdminAllergenGetAllSortOrder } from "./adminAllergenGetAllSortOrder";

export type AdminAllergenGetAllParams = {
  search?: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset?: number | null;
  sortBy?: AdminAllergenGetAllSortBy;
  sortOrder?: AdminAllergenGetAllSortOrder;
};
