/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDeliveryZoneDelete404ErrorsItem } from "./adminDeliveryZoneDelete404ErrorsItem";

export type AdminDeliveryZoneDelete404 = {
  message: string;
  code: string;
  errors?: AdminDeliveryZoneDelete404ErrorsItem[];
};
