/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminMenuGetAllIsAvailable =
  (typeof AdminMenuGetAllIsAvailable)[keyof typeof AdminMenuGetAllIsAvailable];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminMenuGetAllIsAvailable = {
  true: "true",
  false: "false",
} as const;
