/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDishUpdateBodyDescription } from "./adminDishUpdateBodyDescription";
import type { AdminDishUpdateBodyCategory } from "./adminDishUpdateBodyCategory";
import type { AdminDishUpdateBodyPrice } from "./adminDishUpdateBodyPrice";
import type { AdminDishUpdateBodyImageUrl } from "./adminDishUpdateBodyImageUrl";

export type AdminDishUpdateBody = {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name?: string;
  description?: AdminDishUpdateBodyDescription;
  category?: AdminDishUpdateBodyCategory;
  /** @minimum 0 */
  price?: AdminDishUpdateBodyPrice;
  imageUrl?: AdminDishUpdateBodyImageUrl;
  isAvailable?: boolean;
  allergenIds?: string[];
};
