/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminContactMessageGetAll200ItemsItem } from "./adminContactMessageGetAll200ItemsItem";

export type AdminContactMessageGetAll200 = {
  items: AdminContactMessageGetAll200ItemsItem[];
  totalCount: number;
};
