/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuCreate403ErrorsItem } from "./adminMenuCreate403ErrorsItem";

export type AdminMenuCreate403 = {
  message: string;
  code: string;
  errors?: AdminMenuCreate403ErrorsItem[];
};
