/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDietaryRegimeUpdate403ErrorsItem } from "./adminDietaryRegimeUpdate403ErrorsItem";

export type AdminDietaryRegimeUpdate403 = {
  message: string;
  code: string;
  errors?: AdminDietaryRegimeUpdate403ErrorsItem[];
};
