/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDishCreate201AllergensItemIcon } from "./adminDishCreate201AllergensItemIcon";

export type AdminDishCreate201AllergensItem = {
  id: string;
  name: string;
  icon: AdminDishCreate201AllergensItemIcon;
};
