/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderUpdateStatus401ErrorsItem } from "./adminOrderUpdateStatus401ErrorsItem";

export type AdminOrderUpdateStatus401 = {
  message: string;
  code: string;
  errors?: AdminOrderUpdateStatus401ErrorsItem[];
};
