/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuGetOne200DishesItemCategory } from "./adminMenuGetOne200DishesItemCategory";
import type { AdminMenuGetOne200DishesItemDescription } from "./adminMenuGetOne200DishesItemDescription";
import type { AdminMenuGetOne200DishesItemPrice } from "./adminMenuGetOne200DishesItemPrice";
import type { AdminMenuGetOne200DishesItemAllergensItem } from "./adminMenuGetOne200DishesItemAllergensItem";

export type AdminMenuGetOne200DishesItem = {
  id: string;
  name: string;
  category: AdminMenuGetOne200DishesItemCategory;
  description: AdminMenuGetOne200DishesItemDescription;
  price: AdminMenuGetOne200DishesItemPrice;
  allergens: AdminMenuGetOne200DishesItemAllergensItem[];
};
