/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminEmployeeCreate201Role =
  (typeof AdminEmployeeCreate201Role)[keyof typeof AdminEmployeeCreate201Role];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminEmployeeCreate201Role = {
  USER: "USER",
  EMPLOYEE: "EMPLOYEE",
  ADMIN: "ADMIN",
} as const;
