/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPageContentGetAll200ItemsItem } from "./adminPageContentGetAll200ItemsItem";

export type AdminPageContentGetAll200 = {
  items: AdminPageContentGetAll200ItemsItem[];
};
