/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMenuGetOne403ErrorsItem } from "./adminMenuGetOne403ErrorsItem";

export type AdminMenuGetOne403 = {
  message: string;
  code: string;
  errors?: AdminMenuGetOne403ErrorsItem[];
};
