/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminDishGetAllSortBy =
  (typeof AdminDishGetAllSortBy)[keyof typeof AdminDishGetAllSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminDishGetAllSortBy = {
  name: "name",
  price: "price",
  category: "category",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
} as const;
