/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminEmployeeCreateBodyPhone } from "./adminEmployeeCreateBodyPhone";

export type AdminEmployeeCreateBody = {
  email: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  firstName: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  lastName: string;
  /**
   * @minLength 1
   * @maxLength 50
   */
  phone?: AdminEmployeeCreateBodyPhone;
};
