/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDietaryRegimeGetAll200ItemsItemDescription } from "./adminDietaryRegimeGetAll200ItemsItemDescription";

export type AdminDietaryRegimeGetAll200ItemsItem = {
  id: string;
  name: string;
  description: AdminDietaryRegimeGetAll200ItemsItemDescription;
  createdAt: string;
};
