/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type AdminAllergenGetAllSortBy =
  (typeof AdminAllergenGetAllSortBy)[keyof typeof AdminAllergenGetAllSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminAllergenGetAllSortBy = {
  name: "name",
  createdAt: "createdAt",
} as const;
