/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedUserUpdateMe400ErrorsItem } from "./protectedUserUpdateMe400ErrorsItem";

export type ProtectedUserUpdateMe400 = {
  message: string;
  code: string;
  errors?: ProtectedUserUpdateMe400ErrorsItem[];
};
