/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedReviewCreate404ErrorsItem } from "./protectedReviewCreate404ErrorsItem";

export type ProtectedReviewCreate404 = {
  message: string;
  code: string;
  errors?: ProtectedReviewCreate404ErrorsItem[];
};
