/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedOrderGetOne404ErrorsItem } from "./protectedOrderGetOne404ErrorsItem";

export type ProtectedOrderGetOne404 = {
  message: string;
  code: string;
  errors?: ProtectedOrderGetOne404ErrorsItem[];
};
