/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedOrderCreate409ErrorsItem } from "./protectedOrderCreate409ErrorsItem";

export type ProtectedOrderCreate409 = {
  message: string;
  code: string;
  errors?: ProtectedOrderCreate409ErrorsItem[];
};
