/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedUserGetMe404ErrorsItem } from "./protectedUserGetMe404ErrorsItem";

export type ProtectedUserGetMe404 = {
  message: string;
  code: string;
  errors?: ProtectedUserGetMe404ErrorsItem[];
};
