/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedOrderGetOne403ErrorsItem } from "./protectedOrderGetOne403ErrorsItem";

export type ProtectedOrderGetOne403 = {
  message: string;
  code: string;
  errors?: ProtectedOrderGetOne403ErrorsItem[];
};
