/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedUserUpdateMe401ErrorsItem } from "./protectedUserUpdateMe401ErrorsItem";

export type ProtectedUserUpdateMe401 = {
  message: string;
  code: string;
  errors?: ProtectedUserUpdateMe401ErrorsItem[];
};
