/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedOrderGetOne200Status } from "./protectedOrderGetOne200Status";
import type { ProtectedOrderGetOne200UserId } from "./protectedOrderGetOne200UserId";
import type { ProtectedOrderGetOne200GuestEmail } from "./protectedOrderGetOne200GuestEmail";
import type { ProtectedOrderGetOne200GuestName } from "./protectedOrderGetOne200GuestName";
import type { ProtectedOrderGetOne200GuestPhone } from "./protectedOrderGetOne200GuestPhone";
import type { ProtectedOrderGetOne200DeliveryAddress } from "./protectedOrderGetOne200DeliveryAddress";
import type { ProtectedOrderGetOne200DeliveryCity } from "./protectedOrderGetOne200DeliveryCity";
import type { ProtectedOrderGetOne200DeliveryPostalCode } from "./protectedOrderGetOne200DeliveryPostalCode";
import type { ProtectedOrderGetOne200DeliveryZoneId } from "./protectedOrderGetOne200DeliveryZoneId";
import type { ProtectedOrderGetOne200DeliveryDate } from "./protectedOrderGetOne200DeliveryDate";
import type { ProtectedOrderGetOne200Notes } from "./protectedOrderGetOne200Notes";
import type { ProtectedOrderGetOne200ItemsItem } from "./protectedOrderGetOne200ItemsItem";

export type ProtectedOrderGetOne200 = {
  id: string;
  status: ProtectedOrderGetOne200Status;
  userId: ProtectedOrderGetOne200UserId;
  guestEmail: ProtectedOrderGetOne200GuestEmail;
  guestName: ProtectedOrderGetOne200GuestName;
  guestPhone: ProtectedOrderGetOne200GuestPhone;
  deliveryAddress: ProtectedOrderGetOne200DeliveryAddress;
  deliveryCity: ProtectedOrderGetOne200DeliveryCity;
  deliveryPostalCode: ProtectedOrderGetOne200DeliveryPostalCode;
  deliveryZoneId: ProtectedOrderGetOne200DeliveryZoneId;
  deliveryDate: ProtectedOrderGetOne200DeliveryDate;
  deliveryFee: number;
  totalPrice: number;
  notes: ProtectedOrderGetOne200Notes;
  createdAt: string;
  updatedAt: string;
  items: ProtectedOrderGetOne200ItemsItem[];
};
