/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type ProtectedUserGetMe200Role =
  (typeof ProtectedUserGetMe200Role)[keyof typeof ProtectedUserGetMe200Role];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProtectedUserGetMe200Role = {
  USER: "USER",
  EMPLOYEE: "EMPLOYEE",
  ADMIN: "ADMIN",
} as const;
