/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type ProtectedReviewCreateBody = {
  orderId: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  /** @maxLength 2000 */
  comment?: string;
};
