/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedUserGetMe200Role } from "./protectedUserGetMe200Role";
import type { ProtectedUserGetMe200Phone } from "./protectedUserGetMe200Phone";
import type { ProtectedUserGetMe200Address } from "./protectedUserGetMe200Address";
import type { ProtectedUserGetMe200City } from "./protectedUserGetMe200City";
import type { ProtectedUserGetMe200PostalCode } from "./protectedUserGetMe200PostalCode";
import type { ProtectedUserGetMe200LastLoginAt } from "./protectedUserGetMe200LastLoginAt";

export type ProtectedUserGetMe200 = {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: ProtectedUserGetMe200Role;
  admin: boolean;
  phone: ProtectedUserGetMe200Phone;
  address: ProtectedUserGetMe200Address;
  city: ProtectedUserGetMe200City;
  postalCode: ProtectedUserGetMe200PostalCode;
  isActive: boolean;
  emailVerified: boolean;
  preferredLanguage: string;
  lastLoginAt: ProtectedUserGetMe200LastLoginAt;
  createdAt: string;
  updatedAt: string;
};
