/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedReviewCreate400ErrorsItem } from "./protectedReviewCreate400ErrorsItem";

export type ProtectedReviewCreate400 = {
  message: string;
  code: string;
  errors?: ProtectedReviewCreate400ErrorsItem[];
};
