/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedReviewCreate409ErrorsItem } from "./protectedReviewCreate409ErrorsItem";

export type ProtectedReviewCreate409 = {
  message: string;
  code: string;
  errors?: ProtectedReviewCreate409ErrorsItem[];
};
