/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedUserUpdateMeBodyPhone } from "./protectedUserUpdateMeBodyPhone";
import type { ProtectedUserUpdateMeBodyAddress } from "./protectedUserUpdateMeBodyAddress";
import type { ProtectedUserUpdateMeBodyCity } from "./protectedUserUpdateMeBodyCity";
import type { ProtectedUserUpdateMeBodyPostalCode } from "./protectedUserUpdateMeBodyPostalCode";

export type ProtectedUserUpdateMeBody = {
  /**
   * @minLength 1
   * @maxLength 100
   */
  firstName?: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  lastName?: string;
  phone?: ProtectedUserUpdateMeBodyPhone;
  /** @minLength 1 */
  address?: ProtectedUserUpdateMeBodyAddress;
  /** @minLength 1 */
  city?: ProtectedUserUpdateMeBodyCity;
  postalCode?: ProtectedUserUpdateMeBodyPostalCode;
};
