/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedOrderGetOne401ErrorsItem } from "./protectedOrderGetOne401ErrorsItem";

export type ProtectedOrderGetOne401 = {
  message: string;
  code: string;
  errors?: ProtectedOrderGetOne401ErrorsItem[];
};
