/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedOrderGetAll401ErrorsItem } from "./protectedOrderGetAll401ErrorsItem";

export type ProtectedOrderGetAll401 = {
  message: string;
  code: string;
  errors?: ProtectedOrderGetAll401ErrorsItem[];
};
