/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type ProtectedOrderGetOne200Status =
  (typeof ProtectedOrderGetOne200Status)[keyof typeof ProtectedOrderGetOne200Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProtectedOrderGetOne200Status = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  PREPARING: "PREPARING",
  DELIVERING: "DELIVERING",
  DELIVERED: "DELIVERED",
  AWAITING_MATERIAL_RETURN: "AWAITING_MATERIAL_RETURN",
  COMPLETED: "COMPLETED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
} as const;
