/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedOrderCreate404ErrorsItem } from "./protectedOrderCreate404ErrorsItem";

export type ProtectedOrderCreate404 = {
  message: string;
  code: string;
  errors?: ProtectedOrderCreate404ErrorsItem[];
};
