/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedReviewCreate201Comment } from "./protectedReviewCreate201Comment";
import type { ProtectedReviewCreate201ApprovedBy } from "./protectedReviewCreate201ApprovedBy";

export type ProtectedReviewCreate201 = {
  id: string;
  userId: string;
  orderId: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  comment: ProtectedReviewCreate201Comment;
  isApproved: boolean;
  approvedBy: ProtectedReviewCreate201ApprovedBy;
  createdAt: string;
  updatedAt: string;
};
