/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedOrderCreate201ItemsItemMenuName } from "./protectedOrderCreate201ItemsItemMenuName";

export type ProtectedOrderCreate201ItemsItem = {
  id: string;
  menuId: string;
  menuName: ProtectedOrderCreate201ItemsItemMenuName;
  quantity: number;
  unitPrice: number;
  lineTotal: number;
  discountApplied: boolean;
};
