/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedReviewGetMine200ItemsItem } from "./protectedReviewGetMine200ItemsItem";

export type ProtectedReviewGetMine200 = {
  items: ProtectedReviewGetMine200ItemsItem[];
};
