/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedOrderCreate401ErrorsItem } from "./protectedOrderCreate401ErrorsItem";

export type ProtectedOrderCreate401 = {
  message: string;
  code: string;
  errors?: ProtectedOrderCreate401ErrorsItem[];
};
