/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedOrderCreateBodyItemsItem } from "./protectedOrderCreateBodyItemsItem";

export type ProtectedOrderCreateBody = {
  /** @minItems 1 */
  items: ProtectedOrderCreateBodyItemsItem[];
  deliveryZoneId?: string;
  /**
   * @minLength 1
   * @maxLength 20
   */
  deliveryPostalCode?: string;
  /** @maxLength 255 */
  deliveryAddress?: string;
  /** @maxLength 255 */
  deliveryCity?: string;
  deliveryDate?: string;
  /** @maxLength 2000 */
  notes?: string;
};
