/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedUserUpdateMe200Role } from "./protectedUserUpdateMe200Role";
import type { ProtectedUserUpdateMe200Phone } from "./protectedUserUpdateMe200Phone";
import type { ProtectedUserUpdateMe200Address } from "./protectedUserUpdateMe200Address";
import type { ProtectedUserUpdateMe200City } from "./protectedUserUpdateMe200City";
import type { ProtectedUserUpdateMe200PostalCode } from "./protectedUserUpdateMe200PostalCode";
import type { ProtectedUserUpdateMe200LastLoginAt } from "./protectedUserUpdateMe200LastLoginAt";

export type ProtectedUserUpdateMe200 = {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: ProtectedUserUpdateMe200Role;
  admin: boolean;
  phone: ProtectedUserUpdateMe200Phone;
  address: ProtectedUserUpdateMe200Address;
  city: ProtectedUserUpdateMe200City;
  postalCode: ProtectedUserUpdateMe200PostalCode;
  isActive: boolean;
  emailVerified: boolean;
  preferredLanguage: string;
  lastLoginAt: ProtectedUserUpdateMe200LastLoginAt;
  createdAt: string;
  updatedAt: string;
};
