/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedReviewCreate403ErrorsItem } from "./protectedReviewCreate403ErrorsItem";

export type ProtectedReviewCreate403 = {
  message: string;
  code: string;
  errors?: ProtectedReviewCreate403ErrorsItem[];
};
