/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedUserUpdateMe404ErrorsItem } from "./protectedUserUpdateMe404ErrorsItem";

export type ProtectedUserUpdateMe404 = {
  message: string;
  code: string;
  errors?: ProtectedUserUpdateMe404ErrorsItem[];
};
