/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type ProtectedOrderGetAllStatus =
  (typeof ProtectedOrderGetAllStatus)[keyof typeof ProtectedOrderGetAllStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProtectedOrderGetAllStatus = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  PREPARING: "PREPARING",
  DELIVERING: "DELIVERING",
  DELIVERED: "DELIVERED",
  AWAITING_MATERIAL_RETURN: "AWAITING_MATERIAL_RETURN",
  COMPLETED: "COMPLETED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
} as const;
