/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedUserGetMe401ErrorsItem } from "./protectedUserGetMe401ErrorsItem";

export type ProtectedUserGetMe401 = {
  message: string;
  code: string;
  errors?: ProtectedUserGetMe401ErrorsItem[];
};
