/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedReviewGetMine200ItemsItemComment } from "./protectedReviewGetMine200ItemsItemComment";
import type { ProtectedReviewGetMine200ItemsItemApprovedBy } from "./protectedReviewGetMine200ItemsItemApprovedBy";

export type ProtectedReviewGetMine200ItemsItem = {
  id: string;
  userId: string;
  orderId: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  comment: ProtectedReviewGetMine200ItemsItemComment;
  isApproved: boolean;
  approvedBy: ProtectedReviewGetMine200ItemsItemApprovedBy;
  createdAt: string;
  updatedAt: string;
};
