/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedOrderGetOne200ItemsItemMenuName } from "./protectedOrderGetOne200ItemsItemMenuName";

export type ProtectedOrderGetOne200ItemsItem = {
  id: string;
  menuId: string;
  menuName: ProtectedOrderGetOne200ItemsItemMenuName;
  quantity: number;
  unitPrice: number;
  lineTotal: number;
  discountApplied: boolean;
};
