/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedReviewCreate401ErrorsItem } from "./protectedReviewCreate401ErrorsItem";

export type ProtectedReviewCreate401 = {
  message: string;
  code: string;
  errors?: ProtectedReviewCreate401ErrorsItem[];
};
