/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedOrderGetAllStatus } from "./protectedOrderGetAllStatus";
import type { ProtectedOrderGetAllSortBy } from "./protectedOrderGetAllSortBy";
import type { ProtectedOrderGetAllSortOrder } from "./protectedOrderGetAllSortOrder";

export type ProtectedOrderGetAllParams = {
  status?: ProtectedOrderGetAllStatus;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset?: number | null;
  sortBy?: ProtectedOrderGetAllSortBy;
  sortOrder?: ProtectedOrderGetAllSortOrder;
};
