/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedOrderCreate201Status } from "./protectedOrderCreate201Status";
import type { ProtectedOrderCreate201UserId } from "./protectedOrderCreate201UserId";
import type { ProtectedOrderCreate201GuestEmail } from "./protectedOrderCreate201GuestEmail";
import type { ProtectedOrderCreate201GuestName } from "./protectedOrderCreate201GuestName";
import type { ProtectedOrderCreate201GuestPhone } from "./protectedOrderCreate201GuestPhone";
import type { ProtectedOrderCreate201DeliveryAddress } from "./protectedOrderCreate201DeliveryAddress";
import type { ProtectedOrderCreate201DeliveryCity } from "./protectedOrderCreate201DeliveryCity";
import type { ProtectedOrderCreate201DeliveryPostalCode } from "./protectedOrderCreate201DeliveryPostalCode";
import type { ProtectedOrderCreate201DeliveryZoneId } from "./protectedOrderCreate201DeliveryZoneId";
import type { ProtectedOrderCreate201DeliveryDate } from "./protectedOrderCreate201DeliveryDate";
import type { ProtectedOrderCreate201Notes } from "./protectedOrderCreate201Notes";
import type { ProtectedOrderCreate201ItemsItem } from "./protectedOrderCreate201ItemsItem";

export type ProtectedOrderCreate201 = {
  id: string;
  status: ProtectedOrderCreate201Status;
  userId: ProtectedOrderCreate201UserId;
  guestEmail: ProtectedOrderCreate201GuestEmail;
  guestName: ProtectedOrderCreate201GuestName;
  guestPhone: ProtectedOrderCreate201GuestPhone;
  deliveryAddress: ProtectedOrderCreate201DeliveryAddress;
  deliveryCity: ProtectedOrderCreate201DeliveryCity;
  deliveryPostalCode: ProtectedOrderCreate201DeliveryPostalCode;
  deliveryZoneId: ProtectedOrderCreate201DeliveryZoneId;
  deliveryDate: ProtectedOrderCreate201DeliveryDate;
  deliveryFee: number;
  totalPrice: number;
  notes: ProtectedOrderCreate201Notes;
  createdAt: string;
  updatedAt: string;
  items: ProtectedOrderCreate201ItemsItem[];
};
