/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedOrderGetAll200ItemsItemStatus } from "./protectedOrderGetAll200ItemsItemStatus";
import type { ProtectedOrderGetAll200ItemsItemDeliveryDate } from "./protectedOrderGetAll200ItemsItemDeliveryDate";

export type ProtectedOrderGetAll200ItemsItem = {
  id: string;
  status: ProtectedOrderGetAll200ItemsItemStatus;
  deliveryDate: ProtectedOrderGetAll200ItemsItemDeliveryDate;
  deliveryFee: number;
  totalPrice: number;
  itemCount: number;
  createdAt: string;
};
