/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedUserGetMe403ErrorsItem } from "./protectedUserGetMe403ErrorsItem";

export type ProtectedUserGetMe403 = {
  message: string;
  code: string;
  errors?: ProtectedUserGetMe403ErrorsItem[];
};
