/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedOrderCreate400ErrorsItem } from "./protectedOrderCreate400ErrorsItem";

export type ProtectedOrderCreate400 = {
  message: string;
  code: string;
  errors?: ProtectedOrderCreate400ErrorsItem[];
};
