/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { ProtectedOrderGetAll200ItemsItem } from "./protectedOrderGetAll200ItemsItem";

export type ProtectedOrderGetAll200 = {
  items: ProtectedOrderGetAll200ItemsItem[];
  totalCount: number;
};
