/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicAuthValidateAccount401ErrorsItem } from "./publicAuthValidateAccount401ErrorsItem";

export type PublicAuthValidateAccount401 = {
  message: string;
  code: string;
  errors?: PublicAuthValidateAccount401ErrorsItem[];
};
