/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicAuthResetPassword401ErrorsItem } from "./publicAuthResetPassword401ErrorsItem";

export type PublicAuthResetPassword401 = {
  message: string;
  code: string;
  errors?: PublicAuthResetPassword401ErrorsItem[];
};
