/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicAllergenGetAll200ItemsItem } from "./publicAllergenGetAll200ItemsItem";

export type PublicAllergenGetAll200 = {
  items: PublicAllergenGetAll200ItemsItem[];
  totalCount: number;
};
