/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicMenuGetAll200ItemsItemDescription } from "./publicMenuGetAll200ItemsItemDescription";
import type { PublicMenuGetAll200ItemsItemTheme } from "./publicMenuGetAll200ItemsItemTheme";
import type { PublicMenuGetAll200ItemsItemMaxPersons } from "./publicMenuGetAll200ItemsItemMaxPersons";
import type { PublicMenuGetAll200ItemsItemStock } from "./publicMenuGetAll200ItemsItemStock";
import type { PublicMenuGetAll200ItemsItemImageUrl } from "./publicMenuGetAll200ItemsItemImageUrl";
import type { PublicMenuGetAll200ItemsItemDietaryRegimesItem } from "./publicMenuGetAll200ItemsItemDietaryRegimesItem";

export type PublicMenuGetAll200ItemsItem = {
  id: string;
  name: string;
  description: PublicMenuGetAll200ItemsItemDescription;
  theme: PublicMenuGetAll200ItemsItemTheme;
  price: number;
  minPersons: number;
  maxPersons: PublicMenuGetAll200ItemsItemMaxPersons;
  stock: PublicMenuGetAll200ItemsItemStock;
  isAvailable: boolean;
  imageUrl: PublicMenuGetAll200ItemsItemImageUrl;
  dietaryRegimes: PublicMenuGetAll200ItemsItemDietaryRegimesItem[];
};
