/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicAuthRefresh400ErrorsItem } from "./publicAuthRefresh400ErrorsItem";

export type PublicAuthRefresh400 = {
  message: string;
  code: string;
  errors?: PublicAuthRefresh400ErrorsItem[];
};
