/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicReviewGetApproved200ItemsItemFirstName } from "./publicReviewGetApproved200ItemsItemFirstName";
import type { PublicReviewGetApproved200ItemsItemComment } from "./publicReviewGetApproved200ItemsItemComment";

export type PublicReviewGetApproved200ItemsItem = {
  id: string;
  firstName: PublicReviewGetApproved200ItemsItemFirstName;
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  comment: PublicReviewGetApproved200ItemsItemComment;
  createdAt: string;
};
