/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicAuthRefresh401ErrorsItem } from "./publicAuthRefresh401ErrorsItem";

export type PublicAuthRefresh401 = {
  message: string;
  code: string;
  errors?: PublicAuthRefresh401ErrorsItem[];
};
