/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicContactSend201Phone } from "./publicContactSend201Phone";
import type { PublicContactSend201Subject } from "./publicContactSend201Subject";

export type PublicContactSend201 = {
  id: string;
  name: string;
  email: string;
  phone: PublicContactSend201Phone;
  subject: PublicContactSend201Subject;
  message: string;
  isRead: boolean;
  createdAt: string;
};
