/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicAuthSetEmployeePassword401ErrorsItem } from "./publicAuthSetEmployeePassword401ErrorsItem";

export type PublicAuthSetEmployeePassword401 = {
  message: string;
  code: string;
  errors?: PublicAuthSetEmployeePassword401ErrorsItem[];
};
