/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicDeliveryZoneCalculatePrice200City } from "./publicDeliveryZoneCalculatePrice200City";

export type PublicDeliveryZoneCalculatePrice200 = {
  zoneId: string;
  zoneName: string;
  city: PublicDeliveryZoneCalculatePrice200City;
  distanceKm: number;
  deliveryFee: number;
};
