/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicAuthValidateAccount400ErrorsItem } from "./publicAuthValidateAccount400ErrorsItem";

export type PublicAuthValidateAccount400 = {
  message: string;
  code: string;
  errors?: PublicAuthValidateAccount400ErrorsItem[];
};
