/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicDietaryRegimeGetAll200ItemsItemDescription } from "./publicDietaryRegimeGetAll200ItemsItemDescription";

export type PublicDietaryRegimeGetAll200ItemsItem = {
  id: string;
  name: string;
  description: PublicDietaryRegimeGetAll200ItemsItemDescription;
  createdAt: string;
};
