/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicAuthResetPassword400ErrorsItem } from "./publicAuthResetPassword400ErrorsItem";

export type PublicAuthResetPassword400 = {
  message: string;
  code: string;
  errors?: PublicAuthResetPassword400ErrorsItem[];
};
