/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicAuthRegister400ErrorsItem } from "./publicAuthRegister400ErrorsItem";

export type PublicAuthRegister400 = {
  message: string;
  code: string;
  errors?: PublicAuthRegister400ErrorsItem[];
};
