/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicAuthResendValidation409ErrorsItem } from "./publicAuthResendValidation409ErrorsItem";

export type PublicAuthResendValidation409 = {
  message: string;
  code: string;
  errors?: PublicAuthResendValidation409ErrorsItem[];
};
