/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicDeliveryZoneCalculatePrice400ErrorsItem } from "./publicDeliveryZoneCalculatePrice400ErrorsItem";

export type PublicDeliveryZoneCalculatePrice400 = {
  message: string;
  code: string;
  errors?: PublicDeliveryZoneCalculatePrice400ErrorsItem[];
};
