/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicMenuGetAll200ItemsItem } from "./publicMenuGetAll200ItemsItem";

export type PublicMenuGetAll200 = {
  items: PublicMenuGetAll200ItemsItem[];
  totalCount: number;
};
