/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicOrderCreateGuest201Status } from "./publicOrderCreateGuest201Status";
import type { PublicOrderCreateGuest201UserId } from "./publicOrderCreateGuest201UserId";
import type { PublicOrderCreateGuest201GuestEmail } from "./publicOrderCreateGuest201GuestEmail";
import type { PublicOrderCreateGuest201GuestName } from "./publicOrderCreateGuest201GuestName";
import type { PublicOrderCreateGuest201GuestPhone } from "./publicOrderCreateGuest201GuestPhone";
import type { PublicOrderCreateGuest201DeliveryAddress } from "./publicOrderCreateGuest201DeliveryAddress";
import type { PublicOrderCreateGuest201DeliveryCity } from "./publicOrderCreateGuest201DeliveryCity";
import type { PublicOrderCreateGuest201DeliveryPostalCode } from "./publicOrderCreateGuest201DeliveryPostalCode";
import type { PublicOrderCreateGuest201DeliveryZoneId } from "./publicOrderCreateGuest201DeliveryZoneId";
import type { PublicOrderCreateGuest201DeliveryDate } from "./publicOrderCreateGuest201DeliveryDate";
import type { PublicOrderCreateGuest201Notes } from "./publicOrderCreateGuest201Notes";
import type { PublicOrderCreateGuest201ItemsItem } from "./publicOrderCreateGuest201ItemsItem";

export type PublicOrderCreateGuest201 = {
  id: string;
  status: PublicOrderCreateGuest201Status;
  userId: PublicOrderCreateGuest201UserId;
  guestEmail: PublicOrderCreateGuest201GuestEmail;
  guestName: PublicOrderCreateGuest201GuestName;
  guestPhone: PublicOrderCreateGuest201GuestPhone;
  deliveryAddress: PublicOrderCreateGuest201DeliveryAddress;
  deliveryCity: PublicOrderCreateGuest201DeliveryCity;
  deliveryPostalCode: PublicOrderCreateGuest201DeliveryPostalCode;
  deliveryZoneId: PublicOrderCreateGuest201DeliveryZoneId;
  deliveryDate: PublicOrderCreateGuest201DeliveryDate;
  deliveryFee: number;
  totalPrice: number;
  notes: PublicOrderCreateGuest201Notes;
  createdAt: string;
  updatedAt: string;
  items: PublicOrderCreateGuest201ItemsItem[];
};
