/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicAuthLogin404ErrorsItem } from "./publicAuthLogin404ErrorsItem";

export type PublicAuthLogin404 = {
  message: string;
  code: string;
  errors?: PublicAuthLogin404ErrorsItem[];
};
