/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicOrderCreateGuest409ErrorsItem } from "./publicOrderCreateGuest409ErrorsItem";

export type PublicOrderCreateGuest409 = {
  message: string;
  code: string;
  errors?: PublicOrderCreateGuest409ErrorsItem[];
};
