/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicAuthSetEmployeePassword400ErrorsItem } from "./publicAuthSetEmployeePassword400ErrorsItem";

export type PublicAuthSetEmployeePassword400 = {
  message: string;
  code: string;
  errors?: PublicAuthSetEmployeePassword400ErrorsItem[];
};
