/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicAuthRegister409ErrorsItem } from "./publicAuthRegister409ErrorsItem";

export type PublicAuthRegister409 = {
  message: string;
  code: string;
  errors?: PublicAuthRegister409ErrorsItem[];
};
