/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicOrderCreateGuestBodyItemsItem } from "./publicOrderCreateGuestBodyItemsItem";

export type PublicOrderCreateGuestBody = {
  /** @minItems 1 */
  items: PublicOrderCreateGuestBodyItemsItem[];
  guestEmail: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  guestName: string;
  /** @maxLength 50 */
  guestPhone?: string;
  deliveryZoneId?: string;
  /**
   * @minLength 1
   * @maxLength 20
   */
  deliveryPostalCode?: string;
  /** @maxLength 255 */
  deliveryAddress?: string;
  /** @maxLength 255 */
  deliveryCity?: string;
  deliveryDate?: string;
  /** @maxLength 2000 */
  notes?: string;
};
