/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicOperatingHoursGetAll200ItemsItem } from "./publicOperatingHoursGetAll200ItemsItem";

export type PublicOperatingHoursGetAll200 = {
  items: PublicOperatingHoursGetAll200ItemsItem[];
};
