/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicOrderCreateGuest400ErrorsItem } from "./publicOrderCreateGuest400ErrorsItem";

export type PublicOrderCreateGuest400 = {
  message: string;
  code: string;
  errors?: PublicOrderCreateGuest400ErrorsItem[];
};
