/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type PublicMenuGetOne200DishesItemCategory =
  (typeof PublicMenuGetOne200DishesItemCategory)[keyof typeof PublicMenuGetOne200DishesItemCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PublicMenuGetOne200DishesItemCategory = {
  entree: "entree",
  plat: "plat",
  dessert: "dessert",
} as const;
