/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type PublicDeliveryZoneCalculatePriceBody = {
  deliveryZoneId?: string;
  /**
   * @minLength 1
   * @maxLength 20
   */
  postalCode?: string;
};
