/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicAuthValidateAccount409ErrorsItem } from "./publicAuthValidateAccount409ErrorsItem";

export type PublicAuthValidateAccount409 = {
  message: string;
  code: string;
  errors?: PublicAuthValidateAccount409ErrorsItem[];
};
