/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicMenuGetOne200DishesItemAllergensItemIcon } from "./publicMenuGetOne200DishesItemAllergensItemIcon";

export type PublicMenuGetOne200DishesItemAllergensItem = {
  id: string;
  name: string;
  icon: PublicMenuGetOne200DishesItemAllergensItemIcon;
};
