/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type PublicDeliveryZoneCalculatePrice404ErrorsItem = {
  message: string;
  code: string;
  path: string[];
};
