/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicOperatingHoursGetAll200ItemsItemOpenTime } from "./publicOperatingHoursGetAll200ItemsItemOpenTime";
import type { PublicOperatingHoursGetAll200ItemsItemCloseTime } from "./publicOperatingHoursGetAll200ItemsItemCloseTime";

export type PublicOperatingHoursGetAll200ItemsItem = {
  id: string;
  /**
   * @minimum 0
   * @maximum 6
   */
  dayOfWeek: number;
  openTime: PublicOperatingHoursGetAll200ItemsItemOpenTime;
  closeTime: PublicOperatingHoursGetAll200ItemsItemCloseTime;
  isClosed: boolean;
};
