/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicMenuGetOne404ErrorsItem } from "./publicMenuGetOne404ErrorsItem";

export type PublicMenuGetOne404 = {
  message: string;
  code: string;
  errors?: PublicMenuGetOne404ErrorsItem[];
};
