/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicAllergenGetAll200ItemsItemIcon } from "./publicAllergenGetAll200ItemsItemIcon";

export type PublicAllergenGetAll200ItemsItem = {
  id: string;
  name: string;
  icon: PublicAllergenGetAll200ItemsItemIcon;
  createdAt: string;
};
