/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicDietaryRegimeGetAll200ItemsItem } from "./publicDietaryRegimeGetAll200ItemsItem";

export type PublicDietaryRegimeGetAll200 = {
  items: PublicDietaryRegimeGetAll200ItemsItem[];
  totalCount: number;
};
