/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicAuthLogin400ErrorsItem } from "./publicAuthLogin400ErrorsItem";

export type PublicAuthLogin400 = {
  message: string;
  code: string;
  errors?: PublicAuthLogin400ErrorsItem[];
};
