/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicMenuGetAllSortBy } from "./publicMenuGetAllSortBy";
import type { PublicMenuGetAllSortOrder } from "./publicMenuGetAllSortOrder";

export type PublicMenuGetAllParams = {
  theme?: string;
  dietaryRegimeId?: string;
  priceMax?: number | null;
  priceMin?: number | null;
  maxMinPersons?: number | null;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset?: number | null;
  sortBy?: PublicMenuGetAllSortBy;
  sortOrder?: PublicMenuGetAllSortOrder;
};
