/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicPageContentGet200ItemsItem } from "./publicPageContentGet200ItemsItem";

export type PublicPageContentGet200 = {
  items: PublicPageContentGet200ItemsItem[];
};
