/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicAuthResendValidation400ErrorsItem } from "./publicAuthResendValidation400ErrorsItem";

export type PublicAuthResendValidation400 = {
  message: string;
  code: string;
  errors?: PublicAuthResendValidation400ErrorsItem[];
};
