/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicDeliveryZoneCalculatePrice404ErrorsItem } from "./publicDeliveryZoneCalculatePrice404ErrorsItem";

export type PublicDeliveryZoneCalculatePrice404 = {
  message: string;
  code: string;
  errors?: PublicDeliveryZoneCalculatePrice404ErrorsItem[];
};
