/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type PublicContactSendBody = {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** @maxLength 255 */
  email: string;
  /** @maxLength 50 */
  phone?: string;
  /** @maxLength 255 */
  subject?: string;
  /**
   * @minLength 1
   * @maxLength 5000
   */
  message: string;
};
