/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type PublicAuthSetEmployeePasswordBody = {
  /** @minLength 1 */
  token: string;
  /** @pattern ^(?=.*[a-z])(?=.*[A-Z])(?=.*[\d\W_])[a-zA-Z\d\W_]{8,}$ */
  newPassword: string;
};
