/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicOrderCreateGuest201ItemsItemMenuName } from "./publicOrderCreateGuest201ItemsItemMenuName";

export type PublicOrderCreateGuest201ItemsItem = {
  id: string;
  menuId: string;
  menuName: PublicOrderCreateGuest201ItemsItemMenuName;
  quantity: number;
  unitPrice: number;
  lineTotal: number;
  discountApplied: boolean;
};
