/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicDeliveryZoneGetAll200ItemsItemPostalCode } from "./publicDeliveryZoneGetAll200ItemsItemPostalCode";
import type { PublicDeliveryZoneGetAll200ItemsItemCity } from "./publicDeliveryZoneGetAll200ItemsItemCity";

export type PublicDeliveryZoneGetAll200ItemsItem = {
  id: string;
  name: string;
  postalCode: PublicDeliveryZoneGetAll200ItemsItemPostalCode;
  city: PublicDeliveryZoneGetAll200ItemsItemCity;
  distanceKm: number;
  isActive: boolean;
  createdAt: string;
};
