/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicMenuGetOne200DishesItemCategory } from "./publicMenuGetOne200DishesItemCategory";
import type { PublicMenuGetOne200DishesItemDescription } from "./publicMenuGetOne200DishesItemDescription";
import type { PublicMenuGetOne200DishesItemPrice } from "./publicMenuGetOne200DishesItemPrice";
import type { PublicMenuGetOne200DishesItemAllergensItem } from "./publicMenuGetOne200DishesItemAllergensItem";

export type PublicMenuGetOne200DishesItem = {
  id: string;
  name: string;
  category: PublicMenuGetOne200DishesItemCategory;
  description: PublicMenuGetOne200DishesItemDescription;
  price: PublicMenuGetOne200DishesItemPrice;
  allergens: PublicMenuGetOne200DishesItemAllergensItem[];
};
