/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicAuthRegisterBodyPhone } from "./publicAuthRegisterBodyPhone";
import type { PublicAuthRegisterBodyAddress } from "./publicAuthRegisterBodyAddress";
import type { PublicAuthRegisterBodyCity } from "./publicAuthRegisterBodyCity";
import type { PublicAuthRegisterBodyPostalCode } from "./publicAuthRegisterBodyPostalCode";

export type PublicAuthRegisterBody = {
  email: string;
  /** @pattern ^(?=.*[a-z])(?=.*[A-Z])(?=.*[\d\W_])[a-zA-Z\d\W_]{8,}$ */
  password: string;
  /** @minLength 1 */
  firstName: string;
  /** @minLength 1 */
  lastName: string;
  phone?: PublicAuthRegisterBodyPhone;
  address?: PublicAuthRegisterBodyAddress;
  city?: PublicAuthRegisterBodyCity;
  postalCode?: PublicAuthRegisterBodyPostalCode;
};
