/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */

export type PublicMenuGetAllSortBy =
  (typeof PublicMenuGetAllSortBy)[keyof typeof PublicMenuGetAllSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PublicMenuGetAllSortBy = {
  name: "name",
  price: "price",
  minPersons: "minPersons",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
} as const;
