/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicPageContentGet200ItemsItemContent } from "./publicPageContentGet200ItemsItemContent";
import type { PublicPageContentGet200ItemsItemUpdatedBy } from "./publicPageContentGet200ItemsItemUpdatedBy";

export type PublicPageContentGet200ItemsItem = {
  id: string;
  page: string;
  section: string;
  content: PublicPageContentGet200ItemsItemContent;
  updatedAt: string;
  updatedBy: PublicPageContentGet200ItemsItemUpdatedBy;
};
