/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicReviewGetApproved200ItemsItem } from "./publicReviewGetApproved200ItemsItem";

export type PublicReviewGetApproved200 = {
  items: PublicReviewGetApproved200ItemsItem[];
};
