/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicMenuGetOne200Description } from "./publicMenuGetOne200Description";
import type { PublicMenuGetOne200Theme } from "./publicMenuGetOne200Theme";
import type { PublicMenuGetOne200MaxPersons } from "./publicMenuGetOne200MaxPersons";
import type { PublicMenuGetOne200Stock } from "./publicMenuGetOne200Stock";
import type { PublicMenuGetOne200Conditions } from "./publicMenuGetOne200Conditions";
import type { PublicMenuGetOne200ImageUrl } from "./publicMenuGetOne200ImageUrl";
import type { PublicMenuGetOne200DishesItem } from "./publicMenuGetOne200DishesItem";
import type { PublicMenuGetOne200DietaryRegimesItem } from "./publicMenuGetOne200DietaryRegimesItem";

export type PublicMenuGetOne200 = {
  id: string;
  name: string;
  description: PublicMenuGetOne200Description;
  theme: PublicMenuGetOne200Theme;
  price: number;
  minPersons: number;
  maxPersons: PublicMenuGetOne200MaxPersons;
  stock: PublicMenuGetOne200Stock;
  conditions: PublicMenuGetOne200Conditions;
  imageUrl: PublicMenuGetOne200ImageUrl;
  isAvailable: boolean;
  createdAt: string;
  updatedAt: string;
  dishes: PublicMenuGetOne200DishesItem[];
  dietaryRegimes: PublicMenuGetOne200DietaryRegimesItem[];
};
