/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { PublicContactSend400ErrorsItem } from "./publicContactSend400ErrorsItem";

export type PublicContactSend400 = {
  message: string;
  code: string;
  errors?: PublicContactSend400ErrorsItem[];
};
