/**
 * Valid HTTP error prefixes for AppErrorCodes.
 * Each prefix maps to a specific HTTP status code.
 */
export type HttpErrorPrefix =
  | 'INTERNAL_SERVER_ERROR'
  | 'DEPENDENCY_FAILED'
  | 'BAD_REQUEST'
  | 'UNAUTHORIZED'
  | 'FORBIDDEN'
  | 'NOT_FOUND'
  | 'CONFLICT'
  | 'PAYMENT_REQUIRED'
  | 'TOO_MANY_REQUESTS';

/**
 * Valid error code format: PREFIX or PREFIX_SUBCODE
 * TypeScript will enforce this pattern at compile time.
 */
type ValidErrorCode = HttpErrorPrefix | `${HttpErrorPrefix}_${string}`;

/**
 * AppErrorCodes with compile-time naming validation.
 * Convention: {HTTP_PREFIX}_{SUBCODE}
 *
 * The `satisfies` ensures all values match the ValidErrorCode pattern.
 * The HTTP status is derived from the prefix (see httpErrorMapping.ts).
 */
export const AppErrorCodes = {
  // INTERNAL_SERVER_ERROR (500 equivalent)
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  // BAD_REQUEST (400 equivalent)
  BAD_REQUEST: 'BAD_REQUEST',
  BAD_REQUEST_INVALID_DATA: 'BAD_REQUEST_INVALID_DATA',
  BAD_REQUEST_INVALID_PASSWORD_COMPLEXITY: 'BAD_REQUEST_INVALID_PASSWORD_COMPLEXITY',

  // UNAUTHORIZED (401 equivalent)
  UNAUTHORIZED: 'UNAUTHORIZED',
  UNAUTHORIZED_INVALID_JWT: 'UNAUTHORIZED_INVALID_JWT',
  UNAUTHORIZED_INVALID_TOKEN: 'UNAUTHORIZED_INVALID_TOKEN',
  UNAUTHORIZED_TOKEN_NOT_FOUND: 'UNAUTHORIZED_TOKEN_NOT_FOUND',
  UNAUTHORIZED_TOKEN_EXPIRED: 'UNAUTHORIZED_TOKEN_EXPIRED',
  UNAUTHORIZED_CURRENT_USER_NOT_FOUND: 'UNAUTHORIZED_CURRENT_USER_NOT_FOUND',
  UNAUTHORIZED_ACCOUNT_DISABLED: 'UNAUTHORIZED_ACCOUNT_DISABLED',

  // FORBIDDEN (403 equivalent)
  FORBIDDEN: 'FORBIDDEN',
  FORBIDDEN_NOT_ALLOWED: 'FORBIDDEN_NOT_ALLOWED',
  FORBIDDEN_TOKEN_TYPE_MISMATCH: 'FORBIDDEN_TOKEN_TYPE_MISMATCH',
  FORBIDDEN_TOKEN_USER_MISMATCH: 'FORBIDDEN_TOKEN_USER_MISMATCH',

  // NOT_FOUND (404 equivalent)
  NOT_FOUND: 'NOT_FOUND',
  NOT_FOUND_USER: 'NOT_FOUND_USER',
  NOT_FOUND_LOGIN: 'NOT_FOUND_LOGIN',
  NOT_FOUND_ALLERGEN: 'NOT_FOUND_ALLERGEN',
  NOT_FOUND_DIETARY_REGIME: 'NOT_FOUND_DIETARY_REGIME',
  NOT_FOUND_DISH: 'NOT_FOUND_DISH',
  NOT_FOUND_MENU: 'NOT_FOUND_MENU',

  // CONFLICT (409 equivalent)
  CONFLICT: 'CONFLICT',
  CONFLICT_EMAIL_TAKEN: 'CONFLICT_EMAIL_TAKEN',
  CONFLICT_ACCOUNT_ALREADY_VALIDATED: 'CONFLICT_ACCOUNT_ALREADY_VALIDATED',

  // TOO_MANY_REQUESTS (429 equivalent)
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
} as const satisfies Record<string, ValidErrorCode>;

/**
 * Type representing any valid AppErrorCode value.
 */
export type AppErrorCodes = (typeof AppErrorCodes)[keyof typeof AppErrorCodes];
