/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

/**
 * @summary User - Get current user details
 */
export const zodProtectedUserGetMeResponse = zod.object({
  id: zod.string().uuid(),
  email: zod.string().email(),
  firstName: zod.string(),
  lastName: zod.string(),
  role: zod.enum(["USER", "EMPLOYEE", "ADMIN"]),
  admin: zod.boolean(),
  phone: zod.string().nullable(),
  address: zod.string().nullable(),
  city: zod.string().nullable(),
  postalCode: zod.string().nullable(),
  isActive: zod.boolean(),
  emailVerified: zod.boolean(),
  preferredLanguage: zod.string(),
  lastLoginAt: zod.string().datetime({}).nullable(),
  createdAt: zod.string().datetime({}),
  updatedAt: zod.string().datetime({}),
});

/**
 * @summary User - Update current user profile
 */
export const zodProtectedUserUpdateMeBodyFirstNameMax = 100;

export const zodProtectedUserUpdateMeBodyLastNameMax = 100;

export const zodProtectedUserUpdateMeBody = zod.object({
  firstName: zod
    .string()
    .min(1)
    .max(zodProtectedUserUpdateMeBodyFirstNameMax)
    .optional(),
  lastName: zod
    .string()
    .min(1)
    .max(zodProtectedUserUpdateMeBodyLastNameMax)
    .optional(),
  phone: zod.string().nullish(),
  address: zod.string().min(1).nullish(),
  city: zod.string().min(1).nullish(),
  postalCode: zod.string().nullish(),
});

export const zodProtectedUserUpdateMeResponse = zod.object({
  id: zod.string().uuid(),
  email: zod.string().email(),
  firstName: zod.string(),
  lastName: zod.string(),
  role: zod.enum(["USER", "EMPLOYEE", "ADMIN"]),
  admin: zod.boolean(),
  phone: zod.string().nullable(),
  address: zod.string().nullable(),
  city: zod.string().nullable(),
  postalCode: zod.string().nullable(),
  isActive: zod.boolean(),
  emailVerified: zod.boolean(),
  preferredLanguage: zod.string(),
  lastLoginAt: zod.string().datetime({}).nullable(),
  createdAt: zod.string().datetime({}),
  updatedAt: zod.string().datetime({}),
});

/**
 * @summary Order - Create an order (authenticated)
 */

export const zodProtectedOrderCreateBodyDeliveryPostalCodeMax = 20;

export const zodProtectedOrderCreateBodyDeliveryAddressMax = 255;

export const zodProtectedOrderCreateBodyDeliveryCityMax = 255;

export const zodProtectedOrderCreateBodyNotesMax = 2000;

export const zodProtectedOrderCreateBody = zod.object({
  items: zod
    .array(
      zod.object({
        menuId: zod.string().uuid(),
        quantity: zod.number().min(1),
      }),
    )
    .min(1),
  deliveryZoneId: zod.string().uuid().optional(),
  deliveryPostalCode: zod
    .string()
    .min(1)
    .max(zodProtectedOrderCreateBodyDeliveryPostalCodeMax)
    .optional(),
  deliveryAddress: zod
    .string()
    .max(zodProtectedOrderCreateBodyDeliveryAddressMax)
    .optional(),
  deliveryCity: zod
    .string()
    .max(zodProtectedOrderCreateBodyDeliveryCityMax)
    .optional(),
  deliveryDate: zod.string().date().optional(),
  notes: zod.string().max(zodProtectedOrderCreateBodyNotesMax).optional(),
});

/**
 * @summary Order - List the current user orders (authenticated)
 */
export const zodProtectedOrderGetAllQueryLimitMax = 100;

export const zodProtectedOrderGetAllQueryOffsetMin = 0;

export const zodProtectedOrderGetAllQueryParams = zod.object({
  status: zod
    .enum([
      "PENDING",
      "ACCEPTED",
      "PREPARING",
      "DELIVERING",
      "DELIVERED",
      "AWAITING_MATERIAL_RETURN",
      "COMPLETED",
      "REJECTED",
      "CANCELLED",
    ])
    .optional(),
  limit: zod
    .number()
    .min(1)
    .max(zodProtectedOrderGetAllQueryLimitMax)
    .optional(),
  offset: zod.number().min(zodProtectedOrderGetAllQueryOffsetMin).nullish(),
  sortBy: zod
    .enum(["createdAt", "updatedAt", "totalPrice", "status", "deliveryDate"])
    .optional(),
  sortOrder: zod.enum(["ASC", "DESC"]).optional(),
});

export const zodProtectedOrderGetAllResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      status: zod.enum([
        "PENDING",
        "ACCEPTED",
        "PREPARING",
        "DELIVERING",
        "DELIVERED",
        "AWAITING_MATERIAL_RETURN",
        "COMPLETED",
        "REJECTED",
        "CANCELLED",
      ]),
      deliveryDate: zod.string().nullable(),
      deliveryFee: zod.number(),
      totalPrice: zod.number(),
      itemCount: zod.number(),
      createdAt: zod.string().datetime({}),
    }),
  ),
  totalCount: zod.number(),
});

/**
 * @summary Order - Get an order detail (authenticated, owner or staff)
 */
export const zodProtectedOrderGetOneParams = zod.object({
  id: zod.string().uuid(),
});

export const zodProtectedOrderGetOneResponse = zod.object({
  id: zod.string().uuid(),
  status: zod.enum([
    "PENDING",
    "ACCEPTED",
    "PREPARING",
    "DELIVERING",
    "DELIVERED",
    "AWAITING_MATERIAL_RETURN",
    "COMPLETED",
    "REJECTED",
    "CANCELLED",
  ]),
  userId: zod.string().uuid().nullable(),
  guestEmail: zod.string().nullable(),
  guestName: zod.string().nullable(),
  guestPhone: zod.string().nullable(),
  deliveryAddress: zod.string().nullable(),
  deliveryCity: zod.string().nullable(),
  deliveryPostalCode: zod.string().nullable(),
  deliveryZoneId: zod.string().uuid().nullable(),
  deliveryDate: zod.string().nullable(),
  deliveryFee: zod.number(),
  totalPrice: zod.number(),
  notes: zod.string().nullable(),
  createdAt: zod.string().datetime({}),
  updatedAt: zod.string().datetime({}),
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      menuId: zod.string().uuid(),
      menuName: zod.string().nullable(),
      quantity: zod.number(),
      unitPrice: zod.number(),
      lineTotal: zod.number(),
      discountApplied: zod.boolean(),
    }),
  ),
});

/**
 * @summary Review - Create a review (authenticated)
 */
export const zodProtectedReviewCreateBodyRatingMax = 5;

export const zodProtectedReviewCreateBodyCommentMax = 2000;

export const zodProtectedReviewCreateBody = zod.object({
  orderId: zod.string().uuid(),
  rating: zod.number().min(1).max(zodProtectedReviewCreateBodyRatingMax),
  comment: zod.string().max(zodProtectedReviewCreateBodyCommentMax).optional(),
});

/**
 * @summary Review - List the current user reviews (authenticated)
 */
export const zodProtectedReviewGetMineResponseItemsItemRatingMax = 5;

export const zodProtectedReviewGetMineResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.string().uuid(),
      userId: zod.string().uuid(),
      orderId: zod.string().uuid(),
      rating: zod
        .number()
        .min(1)
        .max(zodProtectedReviewGetMineResponseItemsItemRatingMax),
      comment: zod.string().nullable(),
      isApproved: zod.boolean(),
      approvedBy: zod.string().uuid().nullable(),
      createdAt: zod.string().datetime({}),
      updatedAt: zod.string().datetime({}),
    }),
  ),
});
