/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Vite et Gourmand API
 * OpenAPI spec version: 1.0.0
 */
import type { AxiosRequestConfig, AxiosResponse, AxiosInstance } from "axios";

import type {
  ProtectedOrderCreate201,
  ProtectedOrderCreateBody,
  ProtectedOrderGetAll200,
  ProtectedOrderGetAllParams,
  ProtectedOrderGetOne200,
  ProtectedReviewCreate201,
  ProtectedReviewCreateBody,
  ProtectedReviewGetMine200,
  ProtectedUserGetMe200,
  ProtectedUserUpdateMe200,
  ProtectedUserUpdateMeBody,
} from ".././models";

export const getProtectedApiCollection = (axios: AxiosInstance) => {
  /**
   * @summary User - Get current user details
   */
  const protectedUserGetMe = <TData = AxiosResponse<ProtectedUserGetMe200>>(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/protected/user/me`, options);
  };
  /**
   * @summary User - Update current user profile
   */
  const protectedUserUpdateMe = <
    TData = AxiosResponse<ProtectedUserUpdateMe200>,
  >(
    protectedUserUpdateMeBody: ProtectedUserUpdateMeBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.put(
      `/api/protected/user/me`,
      protectedUserUpdateMeBody,
      options,
    );
  };
  /**
   * @summary Order - Create an order (authenticated)
   */
  const protectedOrderCreate = <TData = AxiosResponse<ProtectedOrderCreate201>>(
    protectedOrderCreateBody: ProtectedOrderCreateBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(
      `/api/protected/order`,
      protectedOrderCreateBody,
      options,
    );
  };
  /**
   * @summary Order - List the current user orders (authenticated)
   */
  const protectedOrderGetAll = <TData = AxiosResponse<ProtectedOrderGetAll200>>(
    params?: ProtectedOrderGetAllParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/protected/order`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  /**
   * @summary Order - Get an order detail (authenticated, owner or staff)
   */
  const protectedOrderGetOne = <TData = AxiosResponse<ProtectedOrderGetOne200>>(
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/protected/order/${id}`, options);
  };
  /**
   * @summary Review - Create a review (authenticated)
   */
  const protectedReviewCreate = <
    TData = AxiosResponse<ProtectedReviewCreate201>,
  >(
    protectedReviewCreateBody: ProtectedReviewCreateBody,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(
      `/api/protected/review`,
      protectedReviewCreateBody,
      options,
    );
  };
  /**
   * @summary Review - List the current user reviews (authenticated)
   */
  const protectedReviewGetMine = <
    TData = AxiosResponse<ProtectedReviewGetMine200>,
  >(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/protected/review`, options);
  };
  return {
    protectedUserGetMe,
    protectedUserUpdateMe,
    protectedOrderCreate,
    protectedOrderGetAll,
    protectedOrderGetOne,
    protectedReviewCreate,
    protectedReviewGetMine,
  };
};
export type ProtectedUserGetMeResult = AxiosResponse<ProtectedUserGetMe200>;
export type ProtectedUserUpdateMeResult =
  AxiosResponse<ProtectedUserUpdateMe200>;
export type ProtectedOrderCreateResult = AxiosResponse<ProtectedOrderCreate201>;
export type ProtectedOrderGetAllResult = AxiosResponse<ProtectedOrderGetAll200>;
export type ProtectedOrderGetOneResult = AxiosResponse<ProtectedOrderGetOne200>;
export type ProtectedReviewCreateResult =
  AxiosResponse<ProtectedReviewCreate201>;
export type ProtectedReviewGetMineResult =
  AxiosResponse<ProtectedReviewGetMine200>;
